"""Pattern catalog indexer — generate `org/runtime/pattern_catalog.yaml`.

Reads SKILL.md-formatted pattern files from `org/patterns/*.md`, extracts
YAML frontmatter, aggregates into `org/runtime/pattern_catalog.yaml`.

Generated index, never hand-edited. Run after any pattern change:

    python -m src.ztare.orchestration.pattern_catalog_indexer

Per `org/INTERFACE.md`, `org/` source files MUST NOT import ZTARE-specific
modules. This indexer lives in `src/ztare/orchestration/` and consumes
`org/` (one-direction dependency, never reverse).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except ImportError:  # pragma: no cover - graceful degradation
    yaml = None  # noqa: N816


REPO_ROOT = Path(__file__).resolve().parents[3]
PATTERNS_DIR = REPO_ROOT / "org" / "patterns"
RUNTIME_DIR = REPO_ROOT / "org" / "runtime"
CATALOG_PATH = RUNTIME_DIR / "pattern_catalog.yaml"
NON_PATTERN_FILES = frozenset({"INDEX.md"})


def extract_frontmatter(md_path: Path) -> dict[str, Any]:
    """Extract YAML frontmatter from a SKILL.md-style file.

    Frontmatter is delimited by `---` lines at the start. Returns a
    dict on success, raises ValueError on malformed input.
    """
    text = md_path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{md_path} missing frontmatter delimiter at start")
    rest = text[len("---\n"):]
    end_idx = rest.find("\n---\n")
    if end_idx < 0:
        raise ValueError(f"{md_path} missing frontmatter end delimiter")
    fm_text = rest[:end_idx]
    if yaml is None:
        raise RuntimeError("PyYAML required to parse frontmatter")
    parsed = yaml.safe_load(fm_text)
    if not isinstance(parsed, dict):
        raise ValueError(f"{md_path} frontmatter must be a YAML dict")
    return parsed


def build_catalog(patterns_dir: Path) -> dict[str, Any]:
    """Build the aggregated catalog dict from all *.md files."""
    if not patterns_dir.is_dir():
        raise FileNotFoundError(f"patterns dir missing: {patterns_dir}")
    pattern_files = [
        path
        for path in sorted(patterns_dir.glob("*.md"))
        if path.name not in NON_PATTERN_FILES
    ]
    entries: dict[str, dict[str, Any]] = {}
    for md_path in pattern_files:
        try:
            fm = extract_frontmatter(md_path)
        except (ValueError, RuntimeError) as exc:
            print(f"WARN: {md_path.name}: {exc}", file=sys.stderr)
            continue
        pid = fm.get("id")
        if not pid:
            print(f"WARN: {md_path.name}: missing 'id' in frontmatter", file=sys.stderr)
            continue
        # Required keys
        for required in ("name", "version", "triggers"):
            if required not in fm:
                print(f"WARN: {md_path.name}: missing '{required}'", file=sys.stderr)
        entries[pid] = {
            "source_file": md_path.relative_to(REPO_ROOT).as_posix(),
            **fm,
        }
    return {
        "spec_version": 1,
        "generated_by": "src.ztare.orchestration.pattern_catalog_indexer",
        "patterns": entries,
    }


def write_catalog(catalog: dict[str, Any], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if yaml is None:
        # Fallback: write JSON instead of YAML
        json_path = output_path.with_suffix(".json")
        json_path.write_text(json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
        print(f"PyYAML missing — wrote JSON fallback: {json_path}", file=sys.stderr)
        return
    output_path.write_text(
        "# GENERATED by src.ztare.orchestration.pattern_catalog_indexer — do not hand-edit\n"
        "# Source: org/patterns/*.md\n"
        "\n"
        + yaml.safe_dump(catalog, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate org/runtime/pattern_catalog.yaml from org/patterns/*.md"
    )
    parser.add_argument(
        "--patterns-dir",
        type=Path,
        default=PATTERNS_DIR,
        help="Directory containing pattern *.md files (default: org/patterns/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=CATALOG_PATH,
        help="Output catalog path (default: org/runtime/pattern_catalog.yaml)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print catalog to stdout without writing",
    )
    args = parser.parse_args()

    try:
        catalog = build_catalog(args.patterns_dir)
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.dry_run:
        if yaml is not None:
            print(yaml.safe_dump(catalog, sort_keys=False))
        else:
            print(json.dumps(catalog, indent=2))
        return 0

    write_catalog(catalog, args.output)
    print(f"wrote {args.output} ({len(catalog['patterns'])} patterns)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
