#!/usr/bin/env python3
"""trace_ledger.py — APRIL-style governance-clean trace ledger.

GPT-5.5 verdict §10 step 2: every failed/closed proof attempt becomes a
trace — failed tactic → Lean error → proof state → diagnosis → repair →
eventual closure/gap outcome — PLUS governance verdict + residual +
cost. This is the prerequisite for ANY future learned probe-priority
model (§10 step 5: "don't train yet; first collect hundreds of governed
candidate-action traces"). The differentiator the SITREP/cold-review named is
exactly this: governance-clean, OOD-by-construction supervision
generated by Lean itself.

Honest scope (no fabrication): the pilot ran codex as a black-box
agent, so per-TACTIC step traces (tactic→error→repair) were not
structurally captured. This backfills the OUTCOME-level trace richly
from data we have (corpus + ckpt + residual ledger) and marks
tactic-level fields null with capture_status, so the schema is ready
and future instrumented runs append step-level traces. Machine-safe:
pure Python on collected data; does NOT touch hardened-30.

Learning target (per cold review, NOT source-tactic imitation):
label = closure_or_exact_gap outcome under governance; features =
(goal/gold_steps/arm/residual/why/cost). First model later = logistic/
GBM over frozen features, then cross-encoder, GNN only last.
"""
from __future__ import annotations

import collections
import json
import os
from pathlib import Path

CORPUS = "/tmp/rung1/mcb_corpus_v2.json"
CKPTS = ["/tmp/rung1/codex_pilot_ckpt.jsonl",
         "/tmp/rung1/codex_pilot_hardened.jsonl"]
RESID = "/tmp/rung1/pilot_residual_ledger.jsonl"
OUT = "/tmp/rung1/april_trace_ledger.jsonl"

SCHEMA_VERSION = "april-gov-v1"


def _why_to_diagnosis(why: str) -> str:
    if not why:
        return "unknown"
    if why.startswith("clean"):
        return "closed_clean"
    if why.startswith("timeout"):
        return "budget_search_exhausted"
    if why.startswith("errs") or "sorry=" in why:
        return "composition_wrong_proof"
    if why.startswith("leak"):
        return "governance_rejected_leak"
    if "blind_bad_output" in why:
        return "blind_malformed_output"
    return f"other:{why[:32]}"


def main() -> int:
    corpus = {r["id"]: r for r in
              json.load(open(CORPUS))["rows"]} if os.path.exists(CORPUS) else {}
    resid = {}
    if os.path.exists(RESID):
        for ln in Path(RESID).read_text().splitlines():
            try:
                d = json.loads(ln)
                resid[(d["id"], d["arm"])] = d
            except Exception:
                pass

    traces = []
    for ck in CKPTS:
        if not os.path.exists(ck):
            continue
        src = Path(ck).name
        for ln in Path(ck).read_text().splitlines():
            try:
                row = json.loads(ln)
            except Exception:
                continue
            rid = row["id"]
            c = corpus.get(rid, {})
            for arm in ("stateful", "blind"):
                solved = row.get(f"{arm}_solved")
                a = row.get(arm, {}) or {}
                why = a.get("why", "") or ""
                rl = resid.get((rid, arm), {})
                outcome = ("closure_candidate" if solved else
                           "exact_gap" if "sorry=" in why and
                           "errs=" not in why else "no_closure")
                traces.append({
                    "schema": SCHEMA_VERSION,
                    "trace_id": f"{rid}::{arm}::{src}",
                    "target": rid,
                    "source_module": (c.get("source") or {}).get("file"),
                    "arm": arm,
                    "gold_n_steps": c.get("gold_n_steps"),
                    "goal_excerpt": (c.get("goal", "") or "")[:160],
                    # APRIL fields — outcome-level populated; step-level
                    # null (codex black-box; future instrumented runs
                    # fill these). capture_status states this honestly.
                    "failed_tactic": None,
                    "lean_error": None,
                    "proof_state_at_failure": None,
                    "repair_attempt": None,
                    "capture_status": "outcome_only_backfill",
                    "diagnosis": _why_to_diagnosis(why),
                    # governance-clean supervision (the differentiator)
                    "outcome": outcome,
                    "governed_solved": bool(solved),
                    "governance_residual_class":
                        rl.get("residual_class"),
                    "next_lever": rl.get("next_lever"),
                    "cost_secs": a.get("secs"),
                    "open_s": a.get("open_s"),
                    # learning label (NOT source-tactic imitation):
                    # 1 iff governed closure_or_exact_gap.
                    "label_closure_or_exact_gap":
                        1 if (solved or outcome == "exact_gap") else 0,
                })

    Path(OUT).write_text("\n".join(json.dumps(t) for t in traces))
    n = len(traces)
    pos = sum(t["label_closure_or_exact_gap"] for t in traces)
    by_diag = collections.Counter(t["diagnosis"] for t in traces)
    by_arm_lbl = collections.Counter(
        (t["arm"], t["label_closure_or_exact_gap"]) for t in traces)
    print(json.dumps({
        "trace_ledger": OUT,
        "n_traces": n,
        "positive_label (governed closure_or_exact_gap)": pos,
        "base_rate": round(pos / n, 3) if n else 0,
        "diagnosis_distribution": dict(by_diag),
        "by_arm_label": {f"{a}|label{l}": c
                         for (a, l), c in sorted(by_arm_lbl.items())},
        "capture_status": "outcome_only_backfill — step-level "
        "(tactic/error/repair) null; schema ready; future "
        "instrumented runs append step-level traces",
        "use": "frozen-feature logistic/GBM probe-priority model "
        "ONLY after trace volume + ONLY if deterministic policy "
        "leaves residuals (cold-review §10 step 5); label is "
        "governed outcome, NOT source-tactic imitation",
    }, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
