"""Workbench API/action contract registry.

The local Workbench server owns HTTP adaptation. This module owns the product
contract metadata: labels, routes, write-path templates, confirmation policy,
and compatibility route flags.
"""
from __future__ import annotations

from typing import Any


def build_action_contracts(
    *,
    env_path: str,
    source_actions: dict[str, dict[str, Any]],
    evidence_prepare_command_template: str,
    evidence_fetch_command_template: str,
    evidence_fetch_write_path_templates: list[str],
) -> dict[str, dict[str, Any]]:
    contracts = {
        "settings": {
            "label": "Settings",
            "route": "GET /api/settings -> POST /api/settings",
            "mode": "writes local env settings",
            "write_path_templates": [env_path],
            "writes_project_files": False,
            "writes_repo_files": True,
            "writes_saved_record": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "project_inventory": {
            "label": "Projects",
            "route": "GET /api/projects",
            "mode": "read-only",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "capabilities": {
            "label": "Reasoning capabilities",
            "route": "GET /api/capabilities",
            "mode": "read-only",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "principles": {
            "label": "Workbench principles",
            "route": "GET /api/principles",
            "mode": "read-only",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "project_recovery_draft": {
            "label": "Draft project brief from folder",
            "route": "GET /api/project-recovery-draft",
            "mode": "read-only",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "snapshot": {
            "label": "Project data",
            "route": "GET /api/snapshot",
            "mode": "read-only",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "workflow": {
            "label": "Project path",
            "route": "GET /api/workflow",
            "mode": "read-only",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "evidence_support": {
            "label": "Evidence support",
            "route": "GET /api/evidence-support",
            "mode": "read-only",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "project_create": {
            "label": "Create or connect project",
            "route": "POST /api/project-create",
            "mode": "writes project files",
            "write_path_templates": [
                "projects/{project}",
                "projects/{project}/raw",
                "projects/{project}/workspace",
                "projects/{project}/raw/source_type_map.json",
                "projects/{project}/project_charter.md",
                "projects/{project}/{project}_intake.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "charter_edit": {
            "label": "Project charter save",
            "route": "POST /api/charter",
            "mode": "writes project files",
            "write_path_templates": [
                "projects/{project}/project_charter.md",
                "projects/{project}/workspace/forensic_workbench_charter_edits.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_charter_edit.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "intake_edit": {
            "label": "Project brief save",
            "route": "POST /api/intake",
            "mode": "writes project files",
            "write_path_templates": [
                "{intake}",
                "projects/{project}/workspace/forensic_workbench_intake_edits.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_intake_edit.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "source_import": {
            "label": "Add file",
            "route": "POST /api/source-import",
            "mode": "writes project files",
            "write_path_templates": [
                "projects/{project}/raw/{filename}",
                "projects/{project}/raw/source_type_map.json",
                "projects/{project}/workspace/forensic_workbench_source_imports.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_source_import.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "source_edit": {
            "label": "Save file",
            "route": "POST /api/source-edit",
            "mode": "writes project files",
            "write_path_templates": [
                "projects/{project}/raw/{relative}",
                "projects/{project}/raw/source_type_map.json",
                "projects/{project}/workspace/forensic_workbench_source_edits.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_source_edit.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "source_check": {
            "label": source_actions["source_check"]["label"],
            "route": "POST /api/source-action",
            "action": "source_check",
            "command_template": source_actions["source_check"]["display"],
            "write_path_templates": source_actions["source_check"]["write_path_templates"],
            "mode": "read-only",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "source_index": {
            "label": source_actions["source_index"]["label"],
            "route": "POST /api/source-action",
            "action": "source_index",
            "command_template": source_actions["source_index"]["display"],
            "write_path_templates": source_actions["source_index"]["write_path_templates"],
            "mode": "writes file index",
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "evidence_bind": {
            "label": source_actions["evidence_bind"]["label"],
            "route": "POST /api/source-action",
            "action": "evidence_bind",
            "command_template": source_actions["evidence_bind"]["display"],
            "write_path_templates": source_actions["evidence_bind"]["write_path_templates"],
            "mode": "saves evidence connection",
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "evidence_prepare": {
            "label": source_actions["evidence_prepare"]["label"],
            "route": "POST /api/source-action",
            "action": "evidence_prepare",
            "command_template": evidence_prepare_command_template,
            "write_path_templates": source_actions["evidence_prepare"]["write_path_templates"],
            "mode": "asks before preparing evidence",
            "writes_project_files": True,
            "requires_confirmation": True,
            "browser_writes": False,
        },
        "evidence_replay": {
            "label": source_actions["evidence_replay"]["label"],
            "route": "POST /api/source-action",
            "action": "evidence_replay",
            "command_template": source_actions["evidence_replay"]["display"],
            "write_path_templates": source_actions["evidence_replay"]["write_path_templates"],
            "mode": "read-only",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "evidence_gaps": {
            "label": "Evidence gaps",
            "route": "GET /api/evidence-gaps",
            "mode": "read-only",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "leanmill": {
            "label": "LeanMill",
            "route": "GET /api/leanmill",
            "mode": "proof-search view",
            "writes_project_files": False,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "leanmill_target": {
            "label": "Save LeanMill target and notes",
            "route": "POST /api/leanmill/target",
            "mode": "asks before saving target and notes",
            "write_path_templates": [
                "ztare_proofs/leanmill-formalizations/blueprints/{slug}_blueprint.md",
                "analytics/public/leanmill/workbench/leanmill_blueprint_receipts.jsonl",
                "analytics/public/leanmill/workbench/latest_leanmill_blueprint.json",
            ],
            "writes_project_files": False,
            "writes_repo_files": True,
            "requires_confirmation": True,
            "browser_writes": False,
        },
        "leanmill_blueprint": {
            "label": "Save LeanMill target and notes",
            "route": "POST /api/leanmill/blueprint",
            "mode": "compatibility route for older clients",
            "compatibility_only": True,
            "write_path_templates": [
                "ztare_proofs/leanmill-formalizations/blueprints/{slug}_blueprint.md",
                "analytics/public/leanmill/workbench/leanmill_blueprint_receipts.jsonl",
                "analytics/public/leanmill/workbench/latest_leanmill_blueprint.json",
            ],
            "writes_project_files": False,
            "writes_repo_files": True,
            "requires_confirmation": True,
            "browser_writes": False,
        },
        "leanmill_autoformalize_notes": {
            "label": "Autoformalize from notes",
            "route": "POST /api/leanmill/autoformalize-notes",
            "mode": "asks before starting a background job",
            "write_path_templates": [
                "analytics/public/leanmill/workbench/jobs/{job_id}.json",
                "analytics/public/leanmill/workbench/jobs/{job_id}_result.json",
                "analytics/public/leanmill/workbench/jobs/{job_id}.stdout.log",
                "analytics/public/leanmill/workbench/jobs/{job_id}.stderr.log",
                "analytics/public/leanmill/workbench/leanmill_action_history.jsonl",
                "analytics/public/leanmill/workbench/latest_leanmill_action.json",
            ],
            "writes_project_files": False,
            "writes_repo_files": True,
            "requires_confirmation": True,
            "browser_writes": False,
        },
        "leanmill_solve_adhoc": {
            "label": "Solve ad hoc target",
            "route": "POST /api/leanmill/solve-adhoc",
            "mode": "asks before starting a background job",
            "write_path_templates": [
                "analytics/public/leanmill/workbench/jobs/{job_id}.json",
                "analytics/public/leanmill/workbench/jobs/{job_id}_result.json",
                "analytics/public/leanmill/workbench/jobs/{job_id}.stdout.log",
                "analytics/public/leanmill/workbench/jobs/{job_id}.stderr.log",
                "analytics/public/leanmill/workbench/leanmill_action_history.jsonl",
                "analytics/public/leanmill/workbench/latest_leanmill_action.json",
            ],
            "writes_project_files": False,
            "writes_repo_files": True,
            "requires_confirmation": True,
            "browser_writes": False,
        },
        "evidence_fetch": {
            "label": "Fetch evidence",
            "route": "POST /api/evidence-fetch",
            "command_template": evidence_fetch_command_template,
            "mode": "asks before fetching evidence",
            "write_path_templates": evidence_fetch_write_path_templates,
            "writes_project_files": True,
            "requires_confirmation": True,
            "browser_writes": False,
        },
        "evidence_gap_justify": {
            "label": "Justify evidence gap",
            "route": "POST /api/evidence-gap-justify",
            "mode": "writes evidence-gap history",
            "write_path_templates": [
                "projects/{project}/workspace/evidence_gap_resolutions.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "preflight": {
            "label": "Check readiness",
            "route": "POST /api/preflight",
            "mode": "writes saved history",
            "write_path_templates": [
                "projects/{project}/workspace/iteration_telemetry.jsonl",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "project_test": {
            "label": "Run project test",
            "route": "POST /api/project-test",
            "mode": "writes saved history",
            "write_path_templates": [
                "projects/{project}/workspace/forensic_workbench_project_tests.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_project_test.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "run_preview_and_confirm": {
            "label": "Run",
            "route": "POST /api/run",
            "mode": "asks before writing",
            "write_path_templates": [
                "projects/{project}/workspace/iteration_telemetry.jsonl",
                "projects/{project}/latest_eval_results.json",
                "projects/{project}/eval_results.jsonl",
            ],
            "writes_project_files": True,
            "requires_confirmation": True,
            "browser_writes": False,
        },
        "report_support_refresh": {
            "label": "Check report readiness",
            "route": "POST /api/report-contract",
            "command_template": "ztare forensic-workbench report-action --project {project} --action check_readiness --renderer decision_brief --confirmed --json",
            "mode": "asks before checking report readiness",
            "write_path_templates": [
                "projects/{project}/synthesis/report_support_contract.json",
                "projects/{project}/workspace/forensic_workbench_report_support_checks.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_report_support_check.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": True,
            "browser_writes": False,
        },
        "report_synthesis": {
            "label": "Refresh report inputs",
            "route": "POST /api/report-synthesis",
            "command_template": "ztare forensic-workbench report-action --project {project} --action refresh_inputs --renderer decision_brief --confirmed --json",
            "mode": "asks before full report synthesis",
            "write_path_templates": [
                "projects/{project}/synthesis/context.json",
                "projects/{project}/synthesis/context.decision_brief.json",
                "projects/{project}/synthesis/history_summary.json",
                "projects/{project}/synthesis/ledger.json",
                "projects/{project}/synthesis/brief.decision_brief.json",
                "projects/{project}/synthesis/Report.decision_brief.candidate.md",
                "projects/{project}/synthesis/qa.decision_brief.json",
                "projects/{project}/synthesis/autoresearch_review_context.json",
                "projects/{project}/synthesis/report_support_contract.json",
                "projects/{project}/workspace/forensic_workbench_report_synthesis.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_report_synthesis.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": True,
            "browser_writes": False,
        },
        "review": {
            "label": "Save review",
            "route": "POST /api/review",
            "mode": "writes saved history",
            "write_path_templates": [
                "projects/{project}/workspace/forensic_workbench_applied/<timestamp>_{project_check_slug}_review_<hash>.json",
                "projects/{project}/workspace/forensic_workbench_reviews.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_review.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "next_step": {
            "label": "Save next step",
            "route": "POST /api/next-step",
            "mode": "writes saved history",
            "write_path_templates": [
                "projects/{project}/workspace/forensic_workbench_applied/<timestamp>_{project_check_slug}_action_<hash>.json",
                "projects/{project}/workspace/forensic_workbench_row_actions.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_row_action.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "project_file": {
            "label": "Project file",
            "route": "POST /api/project-file",
            "mode": "writes project file",
            "write_path_templates": [
                "projects/{project}/workspace/forensic_workbench_project_file_{project_file_digest}.json",
                "projects/{project}/workspace/forensic_workbench_project_files.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_project_file_write.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
        "research_map": {
            "label": "Save research map",
            "route": "POST /api/research-map",
            "mode": "writes project map",
            "write_path_templates": [
                "projects/{project}/workspace/research_map.md",
                "projects/{project}/workspace/research_map.json",
                "projects/{project}/workspace/forensic_workbench_research_maps.jsonl",
                "projects/{project}/workspace/forensic_workbench_latest_research_map.json",
            ],
            "writes_project_files": True,
            "requires_confirmation": False,
            "browser_writes": False,
        },
    }
    return contracts
