#!/usr/bin/env python3
"""GP-216f scale-8 — gate-from-metric generator.

Mechanizes the procedure of converting a graph-derived metric into an advisory
gate. Input: metric definition (name, computation, threshold, rubric_field).
Output: a fully-formed advisory gate file under `src/ztare/gates/` with
self-tests, plus an entry in the gate registry.

# The discovery-procedure-as-primitive

Hand-writing 5 advisory gates from 5 graph findings showed that 80% of each
gate is structural boilerplate. The remaining 20% is the metric computation +
threshold + rubric-field-to-check. This script automates the boilerplate so
new graph metrics become gates in seconds.

Cross-scale alias: this is GP-219 proto-op A (Auxiliary Object Construction)
applied at the gate-generator scale — the generator IS the engineered
auxiliary object whose properties (advisory mode, schema validation, self-tests)
transfer to every gate it produces.

# Reliability metadata (added 2026-05-05 after Meitner correction)

Each generated gate includes a `RELIABILITY_NOTE` constant documenting the
classifier-noise dependencies of the underlying metric. If the metric depends
on `classify_status` from `ns_trackb_graph.py`, the note records that
classifier bug-history matters and the gate's findings should be audited for
status-classifier drift.

# Usage

    python scripts/public/utilities/gate_from_metric.py \\
        --metric-spec analytics/public/closure_metric_specs/leverage.json \\
        --output-gate src/ztare/gates/closure_leverage_gate.py

    # Or batch-generate all queued specs:
    python scripts/public/utilities/gate_from_metric.py --all-specs analytics/public/closure_metric_specs/

Spec format (JSON):
    {
      "metric_name": "closure_leverage",
      "gate_class_name": "ClosureLeverageGate",
      "metric_description": "Open obligations ranked by # downstream users",
      "threshold_type": "top_n",                   # top_n | min_value | exact_match | monotonic
      "threshold_value": 10,
      "rubric_field_to_check": "target_obligations",
      "rubric_field_type": "list",                  # list | bool | float
      "graph_extraction_function": "compute_leverage_ranking",  # Python callable name
      "violation_type": "low_leverage_attempt",
      "advisory_default": true,
      "reliability_note": "Depends on classify_status; subject to status-classifier drift."
    }
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from textwrap import dedent

REPO = Path(__file__).resolve().parents[3]
GATES_DIR = REPO / "src" / "ztare" / "gates"


GATE_TEMPLATE = '''"""G-{NAME_UPPER} — {METRIC_DESCRIPTION} (auto-generated advisory v0.1).

Auto-generated by scripts/public/utilities/gate_from_metric.py from graph-derived metric.

# Status: ADVISORY v0.1 (auto-generated)

Ships in advisory mode. Flip to promote-blocking with `enforce_block=True`
after 3-5 closure-attempt observations confirm the metric is meaningful for
this domain.

# Reliability note

{RELIABILITY_NOTE}

If this gate produces unexpected false-positives, audit the underlying metric
extractor (likely `ns_trackb_graph.py:classify_*` heuristics) before tuning
the gate.
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any


METRIC_NAME = "{METRIC_NAME}"
RELIABILITY_NOTE = """{RELIABILITY_NOTE}"""


def {EXTRACTOR_NAME}(graph_path: Path, receipt_node_id: str) -> list[dict]:
    """Extract metric values from artifact graph.

    Auto-generated stub — REPLACE with actual metric computation. The expected
    return shape is a list of dicts each with at minimum 'name' and a numeric
    score field. The gate compares declared rubric values against this ranking.
    """
    if not graph_path.exists():
        return []
    g = json.loads(graph_path.read_text())
    nodes = g.get("@graph", [])
    # TODO(auto-gen): implement actual metric extraction here.
    return []


def run_{METRIC_NAME}_gate(
    rubric_data: dict[str, Any] | None = None,
    artifact_graph_path: str | Path | None = None,
    receipt_node_id: str = "ns_file:ns_gp216_bridge_composition_receipt",
    *,
    threshold_value: {THRESHOLD_PY_TYPE} = {THRESHOLD_VALUE_REPR},
    enforce_block: bool = False,
) -> dict[str, Any]:
    """Verify closure attempt against the {METRIC_NAME} metric.

    Args:
        rubric_data: looks for rubric field `{RUBRIC_FIELD}`
        artifact_graph_path: path to JSON-LD artifact graph
        receipt_node_id: graph node id for the closure receipt
        threshold_value: comparison threshold ({THRESHOLD_TYPE})
        enforce_block: if True, return passed=False on violations

    Returns:
        {{"passed": bool, "blocking_active": bool, "violations": list[dict],
         "advisory_warnings": list[str], "metric_ranking": list[dict],
         "matched_targets": list, "summary": str}}
    """
    rubric_data = rubric_data or {{}}
    declared = rubric_data.get("{RUBRIC_FIELD}")

    if artifact_graph_path is None:
        artifact_graph_path = Path(__file__).resolve().parents[3] / "analytics" / "queries" / "ns_trackb_artifact_graph.json"
    artifact_graph_path = Path(artifact_graph_path)

    violations: list[dict[str, Any]] = []
    warnings: list[str] = []

    if not artifact_graph_path.exists():
        return {{
            "passed": True, "blocking_active": enforce_block,
            "violations": [{{"type": "graph_not_found", "severity": "advisory",
                            "reason": f"Artifact graph not found at {{artifact_graph_path}}; gate skipped."}}],
            "advisory_warnings": ["graph not generated"],
            "metric_ranking": [], "matched_targets": [],
            "summary": "graph not generated; gate skipped",
        }}

    ranking = {EXTRACTOR_NAME}(artifact_graph_path, receipt_node_id)
    if not ranking:
        return {{
            "passed": True, "blocking_active": enforce_block,
            "violations": [], "advisory_warnings": ["empty metric ranking"],
            "metric_ranking": [], "matched_targets": [],
            "summary": "empty ranking; nothing to gate against",
        }}

    # Threshold check based on declared THRESHOLD_TYPE: {THRESHOLD_TYPE}
    {THRESHOLD_CHECK_BODY}

    blocking = [v for v in violations if v.get("severity") == "blocking"]
    passed = (not blocking) if enforce_block else True

    summary_parts = [f"metric={{METRIC_NAME}}", f"ranking_size={{len(ranking)}}"]
    if violations:
        summary_parts.append(f"{{len(violations)}} violation(s)")
    if not enforce_block:
        summary_parts.append("ADVISORY mode")

    return {{
        "passed": passed, "blocking_active": enforce_block,
        "violations": violations, "advisory_warnings": warnings,
        "metric_ranking": ranking, "matched_targets": [],
        "reliability_note": RELIABILITY_NOTE,
        "summary": "; ".join(summary_parts),
    }}


def _self_test() -> None:
    """Auto-generated minimal self-test. Customize after generation."""
    import tempfile
    fake_graph = {{"@graph": [{{"@id": "test_node", "@type": "ns_lean_file"}}]}}
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
        json.dump(fake_graph, f)
        gp = f.name
    r = run_{METRIC_NAME}_gate(rubric_data={{}}, artifact_graph_path=gp)
    assert "passed" in r
    assert r["blocking_active"] is False
    import os; os.unlink(gp)
    print(f"AUTO-GEN GATE {METRIC_NAME}: minimal self-test passed (extend in generated file)")


if __name__ == "__main__":
    _self_test()
'''


THRESHOLD_BODIES = {
    "top_n": '''
    # threshold_type: top_n - declared field must overlap with top-N of ranking
    if not declared:
        violations.append({{"type": "{VIOLATION_TYPE}",
            "severity": "advisory" if not enforce_block else "blocking",
            "reason": f"rubric field `{RUBRIC_FIELD}` not declared; cannot check against top-{{threshold_value}} ranking"}})
    else:
        if not isinstance(declared, list):
            declared = [declared]
        top = ranking[:threshold_value]
        top_names = {{r.get("name") for r in top}}
        matched = [d for d in declared if d in top_names]
        if not matched:
            violations.append({{"type": "{VIOLATION_TYPE}",
                "severity": "advisory" if not enforce_block else "blocking",
                "declared": list(declared), "top_alternatives": [r.get("name") for r in top[:5]],
                "reason": f"declared targets do not overlap top-{{threshold_value}} of metric ranking"}})
''',
    "min_value": '''
    # threshold_type: min_value - declared field's value must be >= threshold
    if declared is None:
        violations.append({{"type": "{VIOLATION_TYPE}",
            "severity": "advisory" if not enforce_block else "blocking",
            "reason": f"rubric field `{RUBRIC_FIELD}` not declared"}})
    elif declared < threshold_value:
        violations.append({{"type": "{VIOLATION_TYPE}",
            "severity": "advisory" if not enforce_block else "blocking",
            "declared_value": declared, "minimum_required": threshold_value,
            "reason": f"declared {RUBRIC_FIELD} = {{declared}} < required {{threshold_value}}"}})
''',
    "monotonic": '''
    # threshold_type: monotonic - current value must be > prior value (increase)
    prior = rubric_data.get("prior_{METRIC_NAME}_value")
    if declared is None:
        violations.append({{"type": "{VIOLATION_TYPE}",
            "severity": "advisory" if not enforce_block else "blocking",
            "reason": f"rubric field `{RUBRIC_FIELD}` not declared"}})
    elif prior is not None and declared <= prior:
        violations.append({{"type": "{VIOLATION_TYPE}",
            "severity": "advisory" if not enforce_block else "blocking",
            "declared": declared, "prior": prior,
            "reason": f"metric did not increase: prior={{prior}}, current={{declared}}; closure attempt did not refine"}})
''',
}


def render_gate(spec: dict) -> str:
    metric_name = spec["metric_name"]
    name_upper = metric_name.upper().replace("_", "-")
    threshold_type = spec.get("threshold_type", "top_n")
    threshold_body_template = THRESHOLD_BODIES.get(threshold_type, THRESHOLD_BODIES["top_n"])
    threshold_body = threshold_body_template.format(
        VIOLATION_TYPE=spec.get("violation_type", f"{metric_name}_violation"),
        RUBRIC_FIELD=spec["rubric_field_to_check"],
        METRIC_NAME=metric_name,
    )
    py_type = {"list": "int", "bool": "bool", "float": "float"}.get(spec.get("rubric_field_type", "list"), "int")
    return GATE_TEMPLATE.format(
        NAME_UPPER=name_upper,
        METRIC_NAME=metric_name,
        METRIC_DESCRIPTION=spec.get("metric_description", "(auto-generated metric gate)"),
        EXTRACTOR_NAME=spec.get("graph_extraction_function", f"compute_{metric_name}_ranking"),
        THRESHOLD_TYPE=threshold_type,
        THRESHOLD_PY_TYPE=py_type,
        THRESHOLD_VALUE_REPR=repr(spec.get("threshold_value")),
        RUBRIC_FIELD=spec["rubric_field_to_check"],
        VIOLATION_TYPE=spec.get("violation_type", f"{metric_name}_violation"),
        RELIABILITY_NOTE=spec.get("reliability_note", "No reliability concerns recorded."),
        THRESHOLD_CHECK_BODY=threshold_body.strip(),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate advisory gates from graph-metric specs")
    parser.add_argument("--metric-spec", type=Path, help="Path to JSON metric spec")
    parser.add_argument("--all-specs", type=Path, help="Directory of metric specs (batch mode)")
    parser.add_argument("--output-gate", type=Path, help="Output gate file (single-spec mode)")
    parser.add_argument("--gates-dir", type=Path, default=GATES_DIR)
    args = parser.parse_args()

    specs = []
    if args.all_specs:
        if not args.all_specs.is_dir():
            print(f"ERROR: not a directory: {args.all_specs}", file=sys.stderr); return 2
        for path in sorted(args.all_specs.glob("*.json")):
            specs.append((path, json.loads(path.read_text())))
    elif args.metric_spec:
        specs.append((args.metric_spec, json.loads(args.metric_spec.read_text())))
    else:
        print("ERROR: provide --metric-spec or --all-specs", file=sys.stderr); return 2

    for spec_path, spec in specs:
        rendered = render_gate(spec)
        if args.output_gate:
            out = args.output_gate
        else:
            out = args.gates_dir / f"{spec['metric_name']}_gate.py"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(rendered)
        print(f"generated: {out}  (from spec {spec_path.name})")
    print(f"\n{len(specs)} gate(s) generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
