#!/usr/bin/env python3
"""Exact adapter audit for the moving Jacobian contact ideal.

The fixed ideal generated by ``C`` is not invariant under the admissible,
target-lift-compatible contact-zero Hamiltonian ``Q**2``.  The moving relation
velocity ``C_dot = -{Q**2,C}`` repairs the finite ideal slices exactly.  The
same Hamiltonian sends the positive-contact element ``Q**2*C`` to contact
depth zero, giving a sharp regression witness for the fixed-filtration route.
This script uses the substrate-neutral filtered-obstruction compiler for the
compatibility and coinvariant certificates; it does not promote any finite
slice to an all-order moving-family theorem.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

import sympy as sp


HERE = Path(__file__).resolve().parent
SRC = HERE.parents[2] / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from ztare.common.filtered_obstruction import (  # noqa: E402
    FilteredAction,
    FilteredBasisVector,
    FilteredObstructionError,
    FilteredObstructionProblem,
    FilteredRelation,
    compile_filtered_obstruction,
)


def _poisson(
    left: sp.Expr,
    right: sp.Expr,
    p: sp.Symbol,
    q: sp.Symbol,
) -> sp.Expr:
    return sp.expand(
        sp.diff(left, p) * sp.diff(right, q)
        - sp.diff(left, q) * sp.diff(right, p)
    )


def _monomials(
    p: sp.Symbol,
    q: sp.Symbol,
    maximum_degree: int,
) -> list[sp.Expr]:
    return [
        p**a * q**b
        for total in range(maximum_degree + 1)
        for a in range(total, -1, -1)
        for b in [total - a]
    ]


def _name(monomial: sp.Expr, p: sp.Symbol, q: sp.Symbol) -> str:
    powers = monomial.as_powers_dict()
    return f"P{int(powers.get(p, 0))}_Q{int(powers.get(q, 0))}"


def _coordinates(
    polynomial: sp.Expr,
    monomials: list[sp.Expr],
    p: sp.Symbol,
    q: sp.Symbol,
) -> dict[str, str]:
    expanded = sp.Poly(sp.expand(polynomial), p, q)
    coordinates: dict[str, str] = {}
    for monomial in monomials:
        powers = monomial.as_powers_dict()
        coefficient = expanded.coeff_monomial(
            p ** int(powers.get(p, 0))
            * q ** int(powers.get(q, 0))
        )
        if coefficient:
            coordinates[_name(monomial, p, q)] = str(coefficient)
    reconstructed = sum(
        sp.Rational(coordinates.get(_name(monomial, p, q), "0"))
        * monomial
        for monomial in monomials
    )
    assert sp.expand(reconstructed - polynomial) == 0
    return coordinates


def _problem(
    maximum_degree: int,
    *,
    moving: bool,
    reverse_basis: bool = False,
) -> tuple[FilteredObstructionProblem, dict[str, object]]:
    if maximum_degree < 3:
        raise ValueError("maximum_degree must be at least three")
    p, q = sp.symbols("P Q")
    contact = 4 * p**3 - p**2 - 18 * p * q + 27 * q**2 + 4 * q
    hamiltonian = q**2
    contact_bracket = _poisson(hamiltonian, contact, p, q)
    assert sp.expand(
        contact_bracket + 4 * q * (6 * p**2 - p - 9 * q)
    ) == 0
    quotient, remainder = sp.reduced(contact_bracket, [contact], p, q)
    assert quotient == [0]
    assert remainder == contact_bracket

    positive_contact = sp.expand(q**2 * contact)
    leakage = _poisson(hamiltonian, positive_contact, p, q)
    expected_leakage = -4 * q**3 * (6 * p**2 - p - 9 * q)
    assert sp.expand(leakage - expected_leakage) == 0
    leakage_quotient, leakage_remainder = sp.reduced(
        leakage,
        [contact],
        p,
        q,
    )
    assert leakage_quotient == [0]
    assert sp.expand(leakage_remainder - expected_leakage) == 0
    r = sp.symbols("r")
    p_normalized = r - sp.Rational(3, 4) * r**2
    q_normalized = sp.Rational(1, 4) * r**2 * (1 - r)
    leakage_on_cusp = sp.factor(
        leakage.subs({p: p_normalized, q: q_normalized})
    )
    expected_on_cusp = (
        r**7 * (r - 1) ** 3 * (3 * r - 2) ** 3 / 128
    )
    assert sp.expand(leakage_on_cusp - expected_on_cusp) == 0

    monomials = _monomials(p, q, maximum_degree)
    basis_monomials = list(reversed(monomials)) if reverse_basis else monomials
    basis = tuple(
        FilteredBasisVector(_name(monomial, p, q), 0)
        for monomial in basis_monomials
    )
    action_columns = {
        _name(monomial, p, q): _coordinates(
            _poisson(hamiltonian, monomial, p, q),
            monomials,
            p,
            q,
        )
        for monomial in monomials
    }

    multipliers = _monomials(p, q, maximum_degree - 3)
    relations = []
    velocities: dict[str, dict[str, str]] = {}
    transport_checks = []
    for multiplier in multipliers:
        relation_name = "C_" + _name(multiplier, p, q)
        relation_polynomial = sp.expand(contact * multiplier)
        relations.append(
            FilteredRelation(
                relation_name,
                0,
                _coordinates(
                    relation_polynomial,
                    monomials,
                    p,
                    q,
                ),
            )
        )
        velocity = sp.expand(-contact_bracket * multiplier)
        if moving:
            velocities[relation_name] = _coordinates(
                velocity,
                monomials,
                p,
                q,
            )
        transported = sp.expand(
            _poisson(hamiltonian, relation_polynomial, p, q)
            + velocity
            - contact * _poisson(hamiltonian, multiplier, p, q)
        )
        assert transported == 0
        transport_checks.append(relation_name)

    action = FilteredAction(
        "ad_Q2_with_moving_C" if moving else "ad_Q2_fixed_C",
        0,
        action_columns,
        relation_velocities=velocities,
    )
    problem = FilteredObstructionProblem(
        name=(
            f"jacobian_moving_contact_degree_{maximum_degree}"
            if moving
            else f"jacobian_fixed_contact_degree_{maximum_degree}"
        ),
        basis=basis,
        relations=tuple(relations),
        actions=(action,),
        distinguished={_name(sp.Integer(1), p, q): 1},
    )
    metadata = {
        "maximum_total_degree": maximum_degree,
        "basis_reversed": reverse_basis,
        "ambient_dimension": len(monomials),
        "relation_count": len(relations),
        "contact": str(contact),
        "ad_Q2_contact": str(contact_bracket),
        "ad_Q2_contact_remainder_mod_C": str(remainder),
        "Q2_is_contact_zero_cone_and_target_lift_compatible": True,
        "positive_contact_witness": str(positive_contact),
        "positive_contact_leakage": str(leakage),
        "positive_contact_leakage_remainder_mod_C": str(
            leakage_remainder
        ),
        "positive_contact_leakage_on_cusp_normalization": str(
            leakage_on_cusp
        ),
        "moving_relation_velocity": str(-contact_bracket),
        "transport_identity": (
            "{Q^2,C*f}+C_dot*f=C*{Q^2,f}"
        ),
        "transport_checks": transport_checks,
    }
    return problem, metadata


def run() -> dict[str, object]:
    static_failures = []
    moving_windows = []
    for maximum_degree in range(3, 7):
        static_problem, static_metadata = _problem(
            maximum_degree,
            moving=False,
        )
        try:
            compile_filtered_obstruction(static_problem)
        except FilteredObstructionError as error:
            assert error.code == "relation_not_invariant"
            static_failures.append({
                **static_metadata,
                "rejected": True,
                "error_code": error.code,
                "error": str(error),
            })
        else:
            raise AssertionError("fixed contact ideal was accepted")

        moving_problem, moving_metadata = _problem(
            maximum_degree,
            moving=True,
        )
        certificate = compile_filtered_obstruction(moving_problem)
        reversed_problem, _ = _problem(
            maximum_degree,
            moving=True,
            reverse_basis=True,
        )
        reversed_certificate = compile_filtered_obstruction(reversed_problem)
        assert certificate.relation_rank == reversed_certificate.relation_rank
        assert certificate.constraint_rank == reversed_certificate.constraint_rank
        assert (
            certificate.coinvariant_dimension
            == reversed_certificate.coinvariant_dimension
        )
        assert (
            certificate.distinguished_survives
            == reversed_certificate.distinguished_survives
        )
        moving_windows.append({
            **moving_metadata,
            "certificate": certificate.to_dict(),
            "basis_permutation_control": {
                "relation_rank_equal": True,
                "constraint_rank_equal": True,
                "coinvariant_dimension_equal": True,
                "distinguished_decision_equal": True,
            },
        })

    return {
        "schema": "axiompack.jacobian_moving_contact_compiler_adapter.v2",
        "fixed_contact_filtration_rejected": True,
        "static_failures": static_failures,
        "moving_contact_transport_verified": True,
        "moving_windows": moving_windows,
        "window_degrees": [3, 4, 5, 6],
        "claim_boundary": (
            "The admissible, target-lift-compatible contact-zero "
            "Hamiltonian Q^2 does not normalize the fixed ideal (C), and "
            "its bracket with Q^2*C reaches contact depth zero. The exact "
            "moving relation velocity C_dot=-{Q^2,C} repairs every "
            "displayed finite ideal slice. "
            "The finite coinvariant dimensions are adapter diagnostics, "
            "not an all-order obstruction and not a source-cost theorem."
        ),
        "next_residual": (
            "Compile the parameter-ordered moving contact connection and "
            "its paired source transfer; determine whether its induced "
            "first-positive-contact operator has a prefix-independent "
            "annihilator or an exact cancellation schedule."
        ),
    }


if __name__ == "__main__":
    print(json.dumps(run(), indent=2, sort_keys=True))
