#!/usr/bin/env python3
"""Algebraic normal-two connection for the pure contact-zero parity tail.

The pure contact-zero quotient has one representative in every cusp weight:
``P**c`` in even weight and ``P**a*Q`` in odd weight.  After slope-two
rescaling, radial normalization is therefore a rank-two module over
``QQ[[y]]`` with ``y=x**2*Pcrit(x, 0)``.  This replay performs that
decomposition in the exact quadratic function field generated by the local
deck involution and extracts the complete normal-two instantaneous
connection.  It deliberately stops before inferring a logarithmic tail from
an instantaneous branch point.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import sys

import sympy as sp


HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
SRC_ROOT = HERE.parents[2] / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from gauge_moving_pullback_normal_semigroup import _exact_family  # noqa: E402
from gauge_pure_contact_zero_delta_critical_recurrence import (  # noqa: E402
    _critical_polynomial,
    _critical_recurrence,
    _critical_source_from_family,
)


@dataclass(frozen=True)
class QuadraticElement:
    """An element ``rational + radical_coefficient*sqrt(discriminant)``."""

    rational: sp.Expr
    radical_coefficient: sp.Expr


def _cancel(value: sp.Expr) -> sp.Expr:
    return sp.cancel(value)


def _add(left: QuadraticElement, right: QuadraticElement) -> QuadraticElement:
    return QuadraticElement(
        _cancel(left.rational + right.rational),
        _cancel(left.radical_coefficient + right.radical_coefficient),
    )


def _scale(value: QuadraticElement, scalar: sp.Expr) -> QuadraticElement:
    return QuadraticElement(
        _cancel(scalar * value.rational),
        _cancel(scalar * value.radical_coefficient),
    )


def _multiply(
    left: QuadraticElement,
    right: QuadraticElement,
    discriminant: sp.Expr,
) -> QuadraticElement:
    return QuadraticElement(
        _cancel(
            left.rational * right.rational
            + left.radical_coefficient
            * right.radical_coefficient
            * discriminant
        ),
        _cancel(
            left.rational * right.radical_coefficient
            + left.radical_coefficient * right.rational
        ),
    )


def _inverse(
    value: QuadraticElement,
    discriminant: sp.Expr,
) -> QuadraticElement:
    norm = _cancel(
        value.rational**2
        - value.radical_coefficient**2 * discriminant
    )
    return QuadraticElement(
        _cancel(value.rational / norm),
        _cancel(-value.radical_coefficient / norm),
    )


def _divide(
    numerator: QuadraticElement,
    denominator: QuadraticElement,
    discriminant: sp.Expr,
) -> QuadraticElement:
    return _multiply(numerator, _inverse(denominator, discriminant), discriminant)


def _power(
    value: QuadraticElement,
    exponent: int,
    discriminant: sp.Expr,
) -> QuadraticElement:
    result = QuadraticElement(sp.Integer(1), sp.Integer(0))
    for _index in range(exponent):
        result = _multiply(result, value, discriminant)
    return result


def _evaluate_polynomial(
    polynomial: sp.Expr,
    argument: QuadraticElement,
    variable: sp.Symbol,
    discriminant: sp.Expr,
) -> QuadraticElement:
    result = QuadraticElement(sp.Integer(0), sp.Integer(0))
    for (exponent,), coefficient in sp.Poly(polynomial, variable).terms():
        result = _add(
            result,
            _scale(_power(argument, exponent, discriminant), coefficient),
        )
    return result


def _derivative(
    value: QuadraticElement,
    variable: sp.Symbol,
    discriminant: sp.Expr,
) -> QuadraticElement:
    # d(sqrt(D))/dx = D'/(2D) sqrt(D).
    return QuadraticElement(
        _cancel(sp.diff(value.rational, variable)),
        _cancel(
            sp.diff(value.radical_coefficient, variable)
            + value.radical_coefficient
            * sp.diff(discriminant, variable)
            / (2 * discriminant)
        ),
    )


def _critical_expression(
    coefficients: dict[tuple[int, int], object],
    x: sp.Symbol,
    eta: sp.Symbol,
) -> sp.Expr:
    return sp.expand(sum(
        sp.Rational(value.numerator, value.denominator)
        * x**x_order
        * eta**normal
        for (x_order, normal), value in coefficients.items()
    ))


def _algebraic_normal_two(
    critical_prefix: tuple[int, sp.Expr] | None = None,
) -> tuple[sp.Symbol, sp.Expr, QuadraticElement]:
    """Return the radially normalized connection, optionally after a prefix.

    ``critical_prefix=(j, K)`` inserts the target coefficient
    ``s**j*K(P,Q)`` with coefficient one before the parity tail is solved.
    The returned difference from the prefix-free connection is therefore the
    exact linear response of that finite critical prefix.
    """

    x, eta = sp.symbols("x eta")
    discriminant = sp.factor(36 + 12 * x - 3 * x**2)
    radical = QuadraticElement(sp.Integer(0), sp.Integer(1))
    involution = _add(
        QuadraticElement((6 - x) / 2, sp.Integer(0)),
        _scale(radical, -sp.Rational(1, 2)),
    )

    (parameter, u, z), family_p, family_q = _exact_family()
    p_critical_data = _critical_polynomial(
        family_p, 2, parameter=parameter, u=u, z=z
    )
    q_critical_data = _critical_polynomial(
        family_q, 3, parameter=parameter, u=u, z=z
    )
    base_data = _critical_source_from_family(
        p_critical_data, q_critical_data
    )
    p_critical = _critical_expression(p_critical_data, x, eta)
    q_critical = _critical_expression(q_critical_data, x, eta)
    base = _critical_expression(base_data, x, eta)
    if critical_prefix is not None:
        target_p, target_q = sp.symbols("P Q")
        prefix_row, prefix_polynomial = critical_prefix
        if prefix_row < 0:
            raise ValueError("critical prefix row must be nonnegative")
        prefix_critical = sp.expand(
            x**prefix_row
            * prefix_polynomial.subs(
                {target_p: p_critical, target_q: q_critical}
            )
        )
        base = sp.expand(base + 8 * prefix_critical)
    p = sp.factor(p_critical.subs(eta, 0))
    q = sp.factor(q_critical.subs(eta, 0))
    assert sp.cancel(p - (x - 6) / 8) == 0
    assert sp.cancel(q - (3 * x - 16) / 64) == 0
    y = sp.factor(x**2 * p)

    # The target demand is the negative normalized radial source row.  Its
    # unique parity decomposition is
    #   f=p^3*A(y)+x*p^2*q*B(y).
    demand = sp.factor(-base.subs(eta, 0) / 8)
    fixed = QuadraticElement(x, sp.Integer(0))
    p_fixed = QuadraticElement(p, sp.Integer(0))
    q_fixed = QuadraticElement(q, sp.Integer(0))
    demand_fixed = QuadraticElement(demand, sp.Integer(0))
    p_other = _evaluate_polynomial(p, involution, x, discriminant)
    q_other = _evaluate_polynomial(q, involution, x, discriminant)
    demand_other = _evaluate_polynomial(
        demand, involution, x, discriminant
    )
    first_value = _divide(
        demand_fixed, _power(p_fixed, 2, discriminant), discriminant
    )
    other_value = _divide(
        demand_other, _power(p_other, 2, discriminant), discriminant
    )
    parity_even = _divide(
        _add(
            _multiply(
                first_value,
                _multiply(involution, q_other, discriminant),
                discriminant,
            ),
            _scale(
                _multiply(
                    other_value,
                    _multiply(fixed, q_fixed, discriminant),
                    discriminant,
                ),
                -1,
            ),
        ),
        _add(
            _multiply(
                p_fixed,
                _multiply(involution, q_other, discriminant),
                discriminant,
            ),
            _scale(
                _multiply(
                    p_other,
                    _multiply(fixed, q_fixed, discriminant),
                    discriminant,
                ),
                -1,
            ),
        ),
        discriminant,
    )
    parity_odd = _divide(
        _add(
            _multiply(first_value, p_other, discriminant),
            _scale(_multiply(other_value, p_fixed, discriminant), -1),
        ),
        _add(
            _multiply(
                fixed,
                _multiply(q_fixed, p_other, discriminant),
                discriminant,
            ),
            _scale(
                _multiply(
                    involution,
                    _multiply(q_other, p_fixed, discriminant),
                    discriminant,
                ),
                -1,
            ),
        ),
        discriminant,
    )

    def y_derivative(value: QuadraticElement) -> QuadraticElement:
        return _scale(
            _derivative(value, x, discriminant),
            1 / sp.diff(y, x),
        )

    even_y = y_derivative(parity_even)
    even_yy = y_derivative(even_y)
    odd_y = y_derivative(parity_odd)
    odd_yy = y_derivative(odd_y)
    y_critical = sp.expand(x**2 * p_critical)
    y_one = y_critical.coeff(eta, 1)
    y_two = y_critical.coeff(eta, 2)

    p_zero = p
    p_one = p_critical.coeff(eta, 1)
    p_two = p_critical.coeff(eta, 2)
    q_zero = q
    q_one = q_critical.coeff(eta, 1)
    q_two = q_critical.coeff(eta, 2)
    p_cube = (
        p_zero**3,
        3 * p_zero**2 * p_one,
        3 * p_zero**2 * p_two + 3 * p_zero * p_one**2,
    )
    even_expansion = (
        parity_even,
        _scale(even_y, y_one),
        _add(
            _scale(even_y, y_two),
            _scale(even_yy, y_one**2 / 2),
        ),
    )
    even_normal_two = _add(
        _add(
            _scale(even_expansion[2], p_cube[0]),
            _scale(even_expansion[1], p_cube[1]),
        ),
        _scale(even_expansion[0], p_cube[2]),
    )

    odd_prefactor = (
        x * p_zero**2 * q_zero,
        x * (2 * p_zero * p_one * q_zero + p_zero**2 * q_one),
        x
        * (
            (2 * p_zero * p_two + p_one**2) * q_zero
            + 2 * p_zero * p_one * q_one
            + p_zero**2 * q_two
        ),
    )
    odd_expansion = (
        parity_odd,
        _scale(odd_y, y_one),
        _add(
            _scale(odd_y, y_two),
            _scale(odd_yy, y_one**2 / 2),
        ),
    )
    odd_normal_two = _add(
        _add(
            _scale(odd_expansion[2], odd_prefactor[0]),
            _scale(odd_expansion[1], odd_prefactor[1]),
        ),
        _scale(odd_expansion[0], odd_prefactor[2]),
    )
    normal_two = _add(
        QuadraticElement(base.coeff(eta, 2), sp.Integer(0)),
        _scale(_add(even_normal_two, odd_normal_two), 8),
    )
    return x, discriminant, normal_two


def run(verification_rows: int = 14) -> dict[str, object]:
    if verification_rows < 8:
        raise ValueError("the algebraic connection needs eight verification rows")
    x, discriminant, normal_two = _algebraic_normal_two()
    expected_rational = sp.cancel(
        (
            21 * x**6
            - 124 * x**5
            + 456 * x**4
            - 2048 * x**3
            - 6768 * x**2
            + 22464 * x
            + 44928
        )
        / (896 * x**3 * (x - 4) * (x**2 - 4 * x - 8))
    )
    expected_radical = sp.cancel(
        (x - 6)
        * (x + 2)
        * (7 * x**3 - 42 * x**2 + 624)
        / (896 * x**3 * (x - 4) * (x**2 - 4 * x - 8))
    )
    assert sp.cancel(normal_two.rational - expected_rational) == 0
    assert sp.cancel(
        normal_two.radical_coefficient - expected_radical
    ) == 0

    radical_branch = sp.sqrt(discriminant)
    algebraic_connection = sp.cancel(
        expected_rational + expected_radical * radical_branch
    )
    recurrence = _critical_recurrence(
        verification_rows,
        guess_rational_generating_function=False,
    )
    series = sp.series(
        algebraic_connection, x, 0, verification_rows + 1
    ).removeO().expand()
    assert all(
        series.coeff(x, row["target_row"])
        == sp.Rational(row["velocity_normal_two"])
        for row in recurrence["rows"]
    )

    # D=24(x+2)+O((x+2)^2), while the radical coefficient has one
    # simple zero and a nonzero quotient at x=-2.  The product therefore
    # has a nonzero (x+2)^(3/2) Puiseux term.
    branch_scale = sp.factor(
        sp.cancel(discriminant / (x + 2)).subs(x, -2)
    )
    radical_scale = sp.factor(
        sp.cancel(expected_radical / (x + 2)).subs(x, -2)
    )
    assert branch_scale == 24
    assert radical_scale == -sp.Rational(25, 1344)
    return {
        "schema": (
            "axiompack.jacobian_pure_contact_zero_"
            "parity_algebraic_connection.v1"
        ),
        "parity_section": {
            "even_weight": "P^(w/2)",
            "odd_weight": "P^((w-3)/2)*Q",
            "module_variable": "y=x^2*(x-6)/8",
            "deck_involution": (
                "(6-x-sqrt(-3*(x+2)*(x-6)))/2"
            ),
        },
        "normal_two_velocity": {
            "rational_part": str(sp.factor(expected_rational)),
            "radical_coefficient": str(sp.factor(expected_radical)),
            "radical_squared": str(discriminant),
            "series_rows_verified": verification_rows,
        },
        "nearest_branch": {
            "point": -2,
            "discriminant_linear_coefficient": str(branch_scale),
            "radical_coefficient_after_simple_zero": str(radical_scale),
            "puiseux_order": "3/2",
            "nonremovable_in_instantaneous_connection": True,
        },
        "claim_boundary": (
            "The pure-parity radial normalization has the displayed exact "
            "algebraic normal-two instantaneous connection and a nonzero "
            "Puiseux branch at x=-2. This proves its velocity series is "
            "infinite. A logarithmic lower bound additionally requires an "
            "inverse-dexp/finite-prefix theorem showing that no finite "
            "critical logarithm produces this algebraic connection."
        ),
    }


if __name__ == "__main__":
    print(json.dumps(run(), indent=2, sort_keys=True))
