#!/usr/bin/env python3
"""Finite-terminal-log candidate generated by the prefix ``Q^3*C``.

The full projected staircase agrees through cost nine with the
right-forward-``dexp`` image of a logarithm containing only its cost-two
zero-grade letter and its cost-three terminal letter.  The fast replay
computes that all-order forward response.  The optional full replay
checks the actual normalized connection through the held-out cost-nine
row.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import sympy as sp


HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from gauge_controlled_global_magnus_hamiltonian import _ops  # noqa: E402
from ztare.common.formal_lie_series import (  # noqa: E402
    VelocityPlacement,
    magnus_from_velocity,
    velocity_from_magnus,
)


LAMBDA = sp.symbols("lambda")
ZERO_GRADE_COEFFICIENT = sp.Rational(9, 256)
TERMINAL_LOGARITHM_COEFFICIENT = -sp.Rational(27, 2048)
TERMINAL_GRADE = (-8, -8)
COST_TWO_LOGARITHM = {
    (7, 9): sp.Rational(3, 32),
    (7, 10): -sp.Rational(135, 256),
    (7, 11): sp.Rational(51, 256),
    (8, 10): -sp.Rational(57, 256),
    (8, 11): sp.Rational(57, 128),
    (9, 11): sp.Rational(67, 256),
    (9, 12): -sp.Rational(35, 256),
    (10, 12): -sp.Rational(39, 256),
    (11, 13): ZERO_GRADE_COEFFICIENT,
}


def _trial_logarithm(
    maximum_cost: int,
) -> list[dict[tuple[int, int], sp.Expr]]:
    logarithm = [{} for _ in range(maximum_cost + 1)]
    logarithm[2] = {
        exponent: coefficient * LAMBDA
        for exponent, coefficient in COST_TWO_LOGARITHM.items()
    }
    logarithm[3] = {
        (12, 14): (
            TERMINAL_LOGARITHM_COEFFICIENT * LAMBDA
        ),
    }
    return logarithm


def _terminal_exponent(cost: int) -> tuple[int, int]:
    if cost < 3 or cost % 2 == 0:
        raise ValueError("terminal response costs are odd and at least three")
    depth = (cost - 3) // 2
    return (12 + 10 * depth, 14 + 10 * depth)


def _terminal_velocity_rows(
    maximum_cost: int,
) -> tuple[
    list[dict[str, object]],
    list[dict[tuple[int, int], sp.Expr]],
]:
    logarithm = _trial_logarithm(maximum_cost)
    velocity = velocity_from_magnus(
        logarithm,
        maximum_cost,
        _ops(2),
        VelocityPlacement.RIGHT_MULTIPLY,
    )
    replay = magnus_from_velocity(
        velocity,
        maximum_cost,
        _ops(2),
        VelocityPlacement.RIGHT_MULTIPLY,
    )
    assert replay == logarithm

    rows = []
    for cost in range(3, maximum_cost + 1, 2):
        depth = (cost - 3) // 2
        exponent = _terminal_exponent(cost)
        coefficient = sp.factor(
            velocity[cost - 1].get(exponent, 0)
        )
        rows.append({
            "depth": depth,
            "cost": cost,
            "exponent": list(exponent),
            "lambda_power": depth + 1,
            "coefficient": str(coefficient),
        })
    return rows, velocity


def _terminal_projection_rows(
    rows: list[list[list[object]]],
    cost: int,
) -> list[list[object]]:
    return [
        row
        for row in rows[cost - 1]
        if row[0] == list(TERMINAL_GRADE)
    ]


def _grade(
    exponent: tuple[int, int],
    cost: int,
) -> tuple[int, int]:
    return (
        2 * exponent[0] - 10 * cost - 2,
        2 * exponent[1] - 10 * cost - 6,
    )


def _projected_prefix_rows(
    value: dict[tuple[int, int], sp.Expr],
    cost: int,
) -> list[list[object]]:
    return [
        [
            list(_grade(exponent, cost)),
            list(exponent),
            str(sp.factor(coefficient)),
        ]
        for exponent, coefficient in sorted(value.items())
        if (
            coefficient.has(LAMBDA)
            and all(
                component >= terminal
                for component, terminal in zip(
                    _grade(exponent, cost),
                    TERMINAL_GRADE,
                    strict=True,
                )
            )
        )
    ]


def _full_projection_witness() -> dict[str, object]:
    from gauge_cone_radial_triangular_staircase import run as staircase

    result = staircase(
        maximum_target_order=8,
        cancel_second_normal=True,
        verify_roundtrips=False,
        compute_logarithms=True,
        normalization_objective="logarithm",
        delayed_c_prefix_terms=[(0, 3, LAMBDA)],
        project_to_prefix_ray=True,
        prefix_terminal_grade_override=TERMINAL_GRADE,
    )
    projection = result["prefix_candidate_ray_projection"]
    trial_logarithm = _trial_logarithm(9)
    trial_velocity = velocity_from_magnus(
        trial_logarithm,
        9,
        _ops(2),
        VelocityPlacement.RIGHT_MULTIPLY,
    )
    expected_velocity = {
        3: "-81*lambda/2048",
        5: "243*lambda**2/524288",
        7: "-8019*lambda**3/67108864",
        9: "1515591*lambda**4/34359738368",
    }
    velocity_rows = {}
    logarithm_rows = {}
    full_window_velocity = {}
    full_window_logarithm = {}
    for cost in range(1, 10):
        actual_velocity = sorted(
            (
                row
                for row in projection["source_velocity"][cost - 1]
                if "lambda" in row[2]
            ),
            key=str,
        )
        expected_window_velocity = sorted(
            _projected_prefix_rows(
                trial_velocity[cost - 1],
                cost,
            ),
            key=str,
        )
        actual_logarithm = sorted(
            (
                row
                for row in projection["source_logarithm"][cost - 1]
                if "lambda" in row[2]
            ),
            key=str,
        )
        expected_window_logarithm = sorted(
            _projected_prefix_rows(
                trial_logarithm[cost],
                cost,
            ),
            key=str,
        )
        assert actual_velocity == expected_window_velocity
        assert actual_logarithm == expected_window_logarithm
        if actual_velocity:
            full_window_velocity[str(cost)] = actual_velocity
        if actual_logarithm:
            full_window_logarithm[str(cost)] = actual_logarithm
    for cost, coefficient in expected_velocity.items():
        exponent = list(_terminal_exponent(cost))
        velocity_row = _terminal_projection_rows(
            projection["source_velocity"], cost
        )
        logarithm_row = _terminal_projection_rows(
            projection["source_logarithm"], cost
        )
        assert velocity_row == [[
            list(TERMINAL_GRADE),
            exponent,
            coefficient,
        ]]
        if cost == 3:
            assert logarithm_row == [[
                list(TERMINAL_GRADE),
                exponent,
                "-27*lambda/2048",
            ]]
        else:
            assert logarithm_row == []
        velocity_rows[str(cost)] = velocity_row
        logarithm_rows[str(cost)] = logarithm_row
    return {
        "verified": True,
        "source_velocity_terminal_rows": velocity_rows,
        "source_logarithm_terminal_rows": logarithm_rows,
        "full_window_source_velocity": full_window_velocity,
        "full_window_source_logarithm": full_window_logarithm,
    }


def run(
    maximum_cost: int = 15,
    verify_full_projection: bool = False,
) -> dict[str, object]:
    if maximum_cost < 9:
        raise ValueError("the replay requires costs through nine")
    rows, velocity = _terminal_velocity_rows(maximum_cost)
    expected = {
        3: -sp.Rational(81, 2048) * LAMBDA,
        5: sp.Rational(243, 524288) * LAMBDA**2,
        7: -sp.Rational(8019, 67108864) * LAMBDA**3,
        9: sp.Rational(1515591, 34359738368) * LAMBDA**4,
        11: -sp.Rational(
            422849889,
            21990232555520,
        ) * LAMBDA**5,
    }
    for cost, coefficient in expected.items():
        assert (
            velocity[cost - 1][_terminal_exponent(cost)]
            == coefficient
        )

    full_projection = (
        _full_projection_witness()
        if verify_full_projection
        else {
            "verified": False,
            "replay_flag": "--verify-full-projection",
            "maximum_held_out_cost": 9,
        }
    )
    return {
        "schema": (
            "axiompack.jacobian_cone_q3c_"
            "finite_terminal_log.v1"
        ),
        "prefix": "Q^3*C",
        "grading": "(2*a-10*cost-2,2*b-10*cost-6)",
        "terminal_grade": list(TERMINAL_GRADE),
        "finite_terminal_logarithm": {
            "cost_two_zero_grade": "9*lambda*u^11*z^13/256",
            "cost_three": "-27*lambda*u^12*z^14/2048",
            "higher_terminal_rows": "0",
        },
        "finite_leading_window_logarithm": {
            "grade_window": "both components >= (-8,-8)",
            "cost_two_terms": {
                f"{exponent[0]},{exponent[1]}": str(coefficient)
                for exponent, coefficient
                in sorted(COST_TWO_LOGARITHM.items())
            },
            "cost_three_terms": {
                "12,14": str(TERMINAL_LOGARITHM_COEFFICIENT),
            },
            "higher_rows": "0",
        },
        "adjoint_multiplier": "9*(1+10*k)/128",
        "right_forward_dexp_response": {
            "function": "2 + (1-exp(-x))/x",
            "constant_coefficient": "3",
            "positive_depth_coefficient": "(-1)^k/(k+1)!",
        },
        "maximum_computed_forward_cost": maximum_cost,
        "terminal_velocity_rows": rows,
        "full_projected_replay": full_projection,
        "claim_boundary": (
            "The all-order rows are the exact forward-dexp image of "
            "the displayed finite terminal logarithm. The actual "
            "logarithm-first staircase is matched throughout the "
            "leading grade window through cost nine, not proved equal "
            "at every order. Lower source grades, "
            "mixed prefixes, and higher powers of C are excluded."
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--maximum-cost",
        type=int,
        default=15,
    )
    parser.add_argument(
        "--verify-full-projection",
        action="store_true",
    )
    arguments = parser.parse_args()
    print(json.dumps(
        run(
            maximum_cost=arguments.maximum_cost,
            verify_full_projection=arguments.verify_full_projection,
        ),
        indent=2,
        sort_keys=True,
    ))


if __name__ == "__main__":
    main()
