#!/usr/bin/env python3
"""Oriented BCH tail ideals for two polynomial autonomous flows.

For endpoint maps ``F = Q o P``, substitution pullbacks compose as
``T_F = T_P * T_Q``.  If ``h = log(T_F)`` and ``p`` is the inner vector
field, the forced outer generator in the derivation convention is therefore

    q = BCH(-p, h).

An outer degree cap ``e`` is equivalent to vanishing of the coefficients of
``q`` above degree ``e``.  For an inner cap ``d``, the first overdetermined
tail ideal is generated by degrees ``e+1`` through ``e+d``.  This replay
constructs those ideals with the shared typed BCH kernel, checks their
orientation against direct time-one-map composition, and searches the fixed
inner-cubic lane for a resultant recurrence.

Finite resultant rows do not prove the all-degree cubic or two-flow claims.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
import hashlib
import json
from pathlib import Path
import sys

import sympy as sp


HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]
SRC_ROOT = REPO_ROOT / "src"
for path in (HERE, SRC_ROOT):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from gauge_critical_holonomy_rank_two_differential import (  # noqa: E402
    _polynomial_ode,
    _recurrence_coefficients,
)
from gauge_two_polynomial_flow_direct_factorization import (  # noqa: E402
    _audit_cap,
    _time_one_flow,
    _zero,
)
from ztare.common.formal_lie_series import (  # noqa: E402
    FormalLieOps,
    bch_series,
)


@dataclass(frozen=True)
class TailIdealRow:
    inner_degree: int
    outer_degree: int
    variable_count: int
    constraint_degrees: tuple[int, ...]
    prefix_ideal_is_proper: bool
    complete_ideal_is_unit: bool
    direct_prefix_ideal_is_proper: bool
    direct_complete_ideal_is_unit: bool
    constraints_sha256: str

    def to_dict(self) -> dict[str, object]:
        return {
            "inner_degree": self.inner_degree,
            "outer_degree": self.outer_degree,
            "variable_count": self.variable_count,
            "constraint_degrees": list(self.constraint_degrees),
            "prefix_ideal_is_proper": self.prefix_ideal_is_proper,
            "complete_ideal_is_unit": self.complete_ideal_is_unit,
            "direct_prefix_ideal_is_proper": (
                self.direct_prefix_ideal_is_proper
            ),
            "direct_complete_ideal_is_unit": (
                self.direct_complete_ideal_is_unit
            ),
            "constraints_sha256": self.constraints_sha256,
        }


def _sha256(value: object) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def _iterative_logarithm(endpoint: list[sp.Expr]) -> list[sp.Expr]:
    """Triangularly recover the vector field whose time-one map is endpoint."""

    maximum_order = len(endpoint) - 1
    logarithm = _zero(maximum_order)
    for degree in range(2, maximum_order + 1):
        probe = sp.Symbol(f"iterative_log_probe_{degree}")
        logarithm[degree] = probe
        flow = _time_one_flow(logarithm)
        coefficient = sp.expand(flow[degree]).coeff(probe)
        assert coefficient == 1
        logarithm[degree] = sp.factor(
            endpoint[degree] - flow[degree].subs(probe, 0)
        )
    replay = _time_one_flow(logarithm)
    assert replay == endpoint
    return logarithm


def _witt_ops(x: sp.Symbol) -> FormalLieOps[sp.Expr]:
    return FormalLieOps(
        zero=lambda: sp.S.Zero,
        add=lambda left, right: sp.expand(left + right),
        scale=lambda value, scalar: sp.expand(
            sp.Rational(scalar.numerator, scalar.denominator) * value
        ),
        bracket=lambda left, right: sp.expand(
            left * sp.diff(right, x) - right * sp.diff(left, x)
        ),
    )


def _forced_outer_coefficients(
    inner_degree: int,
    maximum_spatial_degree: int,
    iterative_logarithm: list[sp.Expr],
    x: sp.Symbol,
) -> tuple[tuple[sp.Symbol, ...], list[sp.Expr]]:
    maximum_weight = maximum_spatial_degree - 1
    symbols = sp.symbols(f"a2:{inner_degree + 1}")
    negative_inner = [sp.S.Zero for _ in range(maximum_weight + 1)]
    target_logarithm = [sp.S.Zero for _ in range(maximum_weight + 1)]
    for degree, symbol in enumerate(symbols, 2):
        negative_inner[degree - 1] = -symbol * x**degree
    for degree in range(2, maximum_spatial_degree + 1):
        target_logarithm[degree - 1] = (
            iterative_logarithm[degree] * x**degree
        )
    forced = bch_series(
        negative_inner,
        target_logarithm,
        maximum_weight,
        _witt_ops(x),
    )
    coefficients = [sp.S.Zero for _ in range(maximum_spatial_degree + 1)]
    for weight in range(1, maximum_weight + 1):
        degree = weight + 1
        coefficient = sp.expand(forced[weight]).coeff(x, degree)
        assert sp.expand(forced[weight] - coefficient * x**degree) == 0
        coefficients[degree] = sp.factor(coefficient)
    return tuple(symbols), coefficients


def _primitive_polynomial(
    expression: sp.Expr,
    variables: tuple[sp.Symbol, ...],
) -> sp.Expr:
    numerator = sp.cancel(expression).as_numer_denom()[0]
    polynomial = sp.Poly(numerator, *variables, domain=sp.QQ)
    _content, primitive = polynomial.primitive()
    result = primitive.as_expr()
    if primitive.LC() < 0:
        result = -result
    return sp.expand(result)


def _tail_constraints(
    inner_degree: int,
    outer_degree: int,
    symbols: tuple[sp.Symbol, ...],
    forced_outer: list[sp.Expr],
) -> list[sp.Expr]:
    return [
        _primitive_polynomial(forced_outer[degree], symbols)
        for degree in range(
            outer_degree + 1,
            outer_degree + inner_degree + 1,
        )
    ]


def _groebner_is_unit(
    constraints: list[sp.Expr],
    variables: tuple[sp.Symbol, ...],
) -> bool:
    basis = sp.groebner(
        constraints,
        *variables,
        order="grevlex",
        method="f5b",
    )
    return bool(basis.contains(sp.S.One))


def _audit_tail_ideal(
    inner_degree: int,
    outer_degree: int,
    symbols: tuple[sp.Symbol, ...],
    forced_outer: list[sp.Expr],
    target: list[sp.Expr],
) -> TailIdealRow:
    constraints = _tail_constraints(
        inner_degree, outer_degree, symbols, forced_outer
    )
    prefix_is_unit = _groebner_is_unit(constraints[:-1], symbols)
    complete_is_unit = _groebner_is_unit(constraints, symbols)
    direct = _audit_cap(inner_degree, outer_degree, target)
    assert complete_is_unit == direct.first_excess_ideal_is_unit
    assert (not prefix_is_unit) == direct.pre_excess_ideal_is_proper
    return TailIdealRow(
        inner_degree=inner_degree,
        outer_degree=outer_degree,
        variable_count=len(symbols),
        constraint_degrees=tuple(
            range(outer_degree + 1, outer_degree + inner_degree + 1)
        ),
        prefix_ideal_is_proper=not prefix_is_unit,
        complete_ideal_is_unit=complete_is_unit,
        direct_prefix_ideal_is_proper=direct.pre_excess_ideal_is_proper,
        direct_complete_ideal_is_unit=direct.first_excess_ideal_is_unit,
        constraints_sha256=_sha256(
            [str(sp.factor(constraint)) for constraint in constraints]
        ),
    )


def _cubic_resultant_row(
    outer_degree: int,
    symbols: tuple[sp.Symbol, ...],
    forced_outer: list[sp.Expr],
) -> dict[str, object]:
    if len(symbols) != 2:
        raise ValueError("the cubic lane needs exactly two variables")
    a2, a3 = symbols
    constraints = _tail_constraints(3, outer_degree, symbols, forced_outer)
    first, second, excess = constraints
    resultant_first_second = sp.Poly(
        sp.resultant(first, second, a3), a2, domain=sp.QQ
    ).primitive()[1]
    resultant_first_excess = sp.Poly(
        sp.resultant(first, excess, a3), a2, domain=sp.QQ
    ).primitive()[1]
    resultant_second_excess = sp.Poly(
        sp.resultant(second, excess, a3), a2, domain=sp.QQ
    ).primitive()[1]
    common_pair_projection = sp.gcd(
        resultant_first_second,
        resultant_first_excess,
    ).monic()
    final = sp.factor(
        sp.resultant(
            common_pair_projection.as_expr(),
            resultant_second_excess.as_expr(),
            a2,
        )
    )
    final_numerator = sp.cancel(final).as_numer_denom()[0]
    assert final_numerator != 0
    final_integer = int(final_numerator)
    return {
        "outer_degree": outer_degree,
        "constraint_degrees": list(
            range(outer_degree + 1, outer_degree + 4)
        ),
        "first_pair_resultant_degree": resultant_first_second.degree(),
        "first_excess_resultant_degree": resultant_first_excess.degree(),
        "second_excess_resultant_degree": resultant_second_excess.degree(),
        "common_pair_projection_degree": common_pair_projection.degree(),
        "projection_artifacts_removed_by_gcd": True,
        "final_resultant_nonzero": True,
        "final_resultant_sign": 1 if final_integer > 0 else -1,
        "final_resultant_decimal_digits": len(str(abs(final_integer))),
        "final_resultant_sha256": _sha256(str(final_integer)),
        "final_resultant": str(final_integer),
    }


def build_certificate(
    maximum_degree: int = 5,
    cubic_outer_maximum: int = 8,
) -> dict[str, object]:
    if maximum_degree < 3:
        raise ValueError("maximum_degree must be at least three")
    if cubic_outer_maximum < maximum_degree:
        raise ValueError("cubic_outer_maximum must cover the cap grid")
    maximum_spatial_degree = max(
        2 * maximum_degree,
        cubic_outer_maximum + 3,
    )
    x, p2, p1, p0, _audit = _polynomial_ode()
    target = _recurrence_coefficients(
        maximum_spatial_degree, x, p2, p1, p0
    )
    iterative_logarithm = _iterative_logarithm(target)

    forced_by_inner_degree = {
        inner_degree: _forced_outer_coefficients(
            inner_degree,
            maximum_spatial_degree,
            iterative_logarithm,
            x,
        )
        for inner_degree in range(2, maximum_degree + 1)
    }

    a2 = forced_by_inner_degree[2][0][0]
    quadratic_forced = forced_by_inner_degree[2][1]
    assert sp.factor(
        quadratic_forced[4]
        + (18 * a2 - 5) / sp.Integer(4032)
    ) == 0
    assert sp.factor(
        quadratic_forced[5]
        - (144 * a2**2 - 120 * a2 + 23) / sp.Integer(96768)
    ) == 0

    cap_rows = []
    for inner_degree in range(2, maximum_degree + 1):
        symbols, forced = forced_by_inner_degree[inner_degree]
        for outer_degree in range(2, maximum_degree + 1):
            cap_rows.append(
                _audit_tail_ideal(
                    inner_degree,
                    outer_degree,
                    symbols,
                    forced,
                    target,
                )
            )

    cubic_symbols, cubic_forced = forced_by_inner_degree[3]
    cubic_rows = [
        _cubic_resultant_row(
            outer_degree, cubic_symbols, cubic_forced
        )
        for outer_degree in range(4, cubic_outer_maximum + 1)
    ]

    core: dict[str, object] = {
        "schema": "axiompack.two_polynomial_flow_bch_tail_ideal.v1",
        "map_factorization": "F = outer o inner",
        "pullback_product": "T_F = T_inner * T_outer",
        "derivation_bch_formula": "outer = BCH(-inner, target_log)",
        "opposite_bch_order_rejected": True,
        "orientation_fixture": {
            "cap": [2, 3],
            "degree_4_constraint": "18*a2 - 5",
            "degree_5_constraint": "144*a2^2 - 120*a2 + 23",
        },
        "universal_tail_ideal": (
            "I_(d,e)=<q_(e+1),...,q_(e+d)> in "
            "QQ[a2,...,a_d], q=BCH(-p,h)"
        ),
        "maximum_degree_cross_checked": maximum_degree,
        "cap_rows": [row.to_dict() for row in cap_rows],
        "all_cap_ideals_match_direct_composition": True,
        "all_complete_cap_ideals_unit": all(
            row.complete_ideal_is_unit for row in cap_rows
        ),
        "cubic_resultant_rows": cubic_rows,
        "all_declared_cubic_resultants_nonzero": all(
            row["final_resultant_nonzero"] for row in cubic_rows
        ),
        "target_coefficient_recurrence_sha256": _sha256(
            [str(value) for value in target]
        ),
        "iterative_logarithm_sha256": _sha256(
            [str(value) for value in iterative_logarithm]
        ),
        "claim_boundary": (
            "The oriented tail-ideal compiler is equivalent to direct "
            "composition on the declared finite grid. The listed cubic "
            "resultants exclude only the declared outer caps. No recurrence "
            "or all-degree nonvanishing theorem is inferred."
        ),
    }
    return {**core, "certificate_sha256": _sha256(core)}


if __name__ == "__main__":
    print(json.dumps(build_certificate(), indent=2, sort_keys=True))
