"""G-CHOKEPOINT-DECLARATION — Closure attempt must declare which betweenness-centrality chokepoint(s) it targets (auto-generated advisory v0.1).

Auto-generated by scripts/public/utilities/gate_from_metric.py from graph-derived metric.

# Status: ADVISORY v0.1 (auto-generated)

Ships in advisory mode. Flip to promote-blocking with `enforce_block=True`
after 3-5 closure-attempt observations confirm the metric is meaningful for
this domain.

# Reliability note

Betweenness centrality is computed on the import-edge graph; reliable. Chokepoint identification does not depend on classify_status, only on graph topology.

If this gate produces unexpected false-positives, audit the underlying metric
extractor (likely `ns_trackb_graph.py:classify_*` heuristics) before tuning
the gate.
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any


METRIC_NAME = "chokepoint_declaration"
RELIABILITY_NOTE = """Betweenness centrality is computed on the import-edge graph; reliable. Chokepoint identification does not depend on classify_status, only on graph topology."""


def compute_chokepoint_ranking(graph_path: Path, receipt_node_id: str) -> list[dict]:
    """Extract metric values from artifact graph.

    Auto-generated stub — REPLACE with actual metric computation. The expected
    return shape is a list of dicts each with at minimum 'name' and a numeric
    score field. The gate compares declared rubric values against this ranking.
    """
    if not graph_path.exists():
        return []
    g = json.loads(graph_path.read_text())
    nodes = g.get("@graph", [])
    # TODO(auto-gen): implement actual metric extraction here.
    return []


def run_chokepoint_declaration_gate(
    rubric_data: dict[str, Any] | None = None,
    artifact_graph_path: str | Path | None = None,
    receipt_node_id: str = "ns_file:ns_gp216_bridge_composition_receipt",
    *,
    threshold_value: int = 5,
    enforce_block: bool = False,
) -> dict[str, Any]:
    """Verify closure attempt against the chokepoint_declaration metric.

    Args:
        rubric_data: looks for rubric field `target_chokepoints`
        artifact_graph_path: path to JSON-LD artifact graph
        receipt_node_id: graph node id for the closure receipt
        threshold_value: comparison threshold (top_n)
        enforce_block: if True, return passed=False on violations

    Returns:
        {"passed": bool, "blocking_active": bool, "violations": list[dict],
         "advisory_warnings": list[str], "metric_ranking": list[dict],
         "matched_targets": list, "summary": str}
    """
    rubric_data = rubric_data or {}
    declared = rubric_data.get("target_chokepoints")

    if artifact_graph_path is None:
        artifact_graph_path = Path(__file__).resolve().parents[3] / "analytics" / "queries" / "ns_trackb_artifact_graph.json"
    artifact_graph_path = Path(artifact_graph_path)

    violations: list[dict[str, Any]] = []
    warnings: list[str] = []

    if not artifact_graph_path.exists():
        return {
            "passed": True, "blocking_active": enforce_block,
            "violations": [{"type": "graph_not_found", "severity": "advisory",
                            "reason": f"Artifact graph not found at {artifact_graph_path}; gate skipped."}],
            "advisory_warnings": ["graph not generated"],
            "metric_ranking": [], "matched_targets": [],
            "summary": "graph not generated; gate skipped",
        }

    ranking = compute_chokepoint_ranking(artifact_graph_path, receipt_node_id)
    if not ranking:
        return {
            "passed": True, "blocking_active": enforce_block,
            "violations": [], "advisory_warnings": ["empty metric ranking"],
            "metric_ranking": [], "matched_targets": [],
            "summary": "empty ranking; nothing to gate against",
        }

    # Threshold check based on declared THRESHOLD_TYPE: top_n
    # threshold_type: top_n - declared field must overlap with top-N of ranking
    if not declared:
        violations.append({"type": "chokepoint_not_declared",
            "severity": "advisory" if not enforce_block else "blocking",
            "reason": f"rubric field `target_chokepoints` not declared; cannot check against top-{threshold_value} ranking"})
    else:
        if not isinstance(declared, list):
            declared = [declared]
        top = ranking[:threshold_value]
        top_names = {r.get("name") for r in top}
        matched = [d for d in declared if d in top_names]
        if not matched:
            violations.append({"type": "chokepoint_not_declared",
                "severity": "advisory" if not enforce_block else "blocking",
                "declared": list(declared), "top_alternatives": [r.get("name") for r in top[:5]],
                "reason": f"declared targets do not overlap top-{threshold_value} of metric ranking"})

    blocking = [v for v in violations if v.get("severity") == "blocking"]
    passed = (not blocking) if enforce_block else True

    summary_parts = [f"metric={METRIC_NAME}", f"ranking_size={len(ranking)}"]
    if violations:
        summary_parts.append(f"{len(violations)} violation(s)")
    if not enforce_block:
        summary_parts.append("ADVISORY mode")

    return {
        "passed": passed, "blocking_active": enforce_block,
        "violations": violations, "advisory_warnings": warnings,
        "metric_ranking": ranking, "matched_targets": [],
        "reliability_note": RELIABILITY_NOTE,
        "summary": "; ".join(summary_parts),
    }


def _self_test() -> None:
    """Auto-generated minimal self-test. Customize after generation."""
    import tempfile
    fake_graph = {"@graph": [{"@id": "test_node", "@type": "ns_lean_file"}]}
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
        json.dump(fake_graph, f)
        gp = f.name
    r = run_chokepoint_declaration_gate(rubric_data={}, artifact_graph_path=gp)
    assert "passed" in r
    assert r["blocking_active"] is False
    import os; os.unlink(gp)
    print(f"AUTO-GEN GATE chokepoint_declaration: minimal self-test passed (extend in generated file)")


if __name__ == "__main__":
    _self_test()
