"""Proof-carrying world models: Lean equivalence certificates (GP-250).

For a sealed environment whose law is itself a seed-grammar program, both the
recovered champion and the sealed law are *independently* translated from
their ASTs into dependency-free Lean 4, and a theorem asserts they agree on an
explicitly enumerated probe set (bounded-BFS reachable states × all actions,
plus step contexts). The proof is `rfl` — pure kernel reduction, no tactics,
no `native_decide`.

Ratification goes through leanmill's external-artifact organ
(`ztare.leanmill.audit_external`): warm-REPL compile with cold lake fallback,
per-declaration axiom audit against the allowlist {propext, Classical.choice,
Quot.sound} (catches `Lean.ofReduceBool` laundering), sorry/admit lexical ban,
and the `claim_audit` certificate. This module only *generates* the artifact;
it holds no soundness surface of its own.

Honest boundary (recorded on the seam): certificates exist only where both
sides are seed-grammar ASTs. A python-level earned extension has no mechanical
Lean translation, so extension champions carry gate-level evidence, not
certificates. The probe set is enumerated in Python; the certificate's claim
is exactly "these two independently-translated programs agree on this explicit
finite set", with reachable-set coverage a Python-side statement.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path

from ztare.gates.lean_compile_primitives import ensure_elan_on_path
from ztare.leanmill.audit_external import audit_external
from ztare.worldmodel.grid_dsl import Grid, Program, evaluate

_PRELUDE = """-- generated by ztare.worldmodel.lean_equivalence (GP-250); dependency-free
set_option linter.unusedVariables false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

abbrev Grid := List (List Nat)

def getCell (g : Grid) (y x : Int) : Nat :=
  if 0 ≤ y ∧ y.toNat < g.length then
    let row := g[y.toNat]!
    if 0 ≤ x ∧ x.toNat < row.length then row[x.toNat]! else 0
  else 0

def gshift (g : Grid) (dy dx : Int) : Grid :=
  (List.range g.length).map fun (y : Nat) =>
    (List.range (g[y]!.length)).map fun (x : Nat) =>
      getCell g ((y : Int) - dy) ((x : Int) - dx)

def grecolor (g : Grid) (a b : Nat) : Grid :=
  g.map fun row => row.map fun c => if c = a then b else c

def gcount (g : Grid) (color : Nat) : Nat :=
  (g.map fun row => (row.filter (fun c => c = color)).length).foldl (· + ·) 0
"""


def _int_expr(node) -> str:
    op = node[0]
    if op == "lit":
        return str(node[1])
    if op == "action":
        return "a"
    if op == "step":
        return "t"
    if op == "add":
        return f"({_int_expr(node[1])} + {_int_expr(node[2])})"
    if op == "mod":
        return f"({_int_expr(node[1])} % {_int_expr(node[2])})"
    if op == "count":
        return f"(gcount s {node[1]})"
    raise ValueError(f"untranslatable int expr: {node!r}")


def _bool_expr(node) -> str:
    if node[0] == "eq":
        return f"({_int_expr(node[1])} = {_int_expr(node[2])})"
    raise ValueError(f"untranslatable bool expr: {node!r}")


def to_lean(program: Program) -> str:
    """Mechanical seed-grammar AST -> Lean expression over (s a t)."""
    op = program[0]
    if op == "s":
        return "s"
    if op == "shift":
        def _delta(node):
            # raw int in the seed grammar; ("lit", k) accepted as the evaluator's
            # benign superset — both are compile-time constants here
            if isinstance(node, tuple) and node[0] == "lit":
                return node[1]
            if isinstance(node, int):
                return node
            raise ValueError(f"non-constant shift delta has no certificate: {node!r}")
        return (f"(gshift {to_lean(program[1])} ({_delta(program[2])} : Int) "
                f"({_delta(program[3])} : Int))")
    if op == "recolor":
        return f"(grecolor {to_lean(program[1])} {_int_expr(program[2])} {_int_expr(program[3])})"
    if op == "if":
        return (f"(if {_bool_expr(program[1])} then {to_lean(program[2])} "
                f"else {to_lean(program[3])})")
    raise ValueError(f"untranslatable grid expr (extensions have no certificate): {program!r}")


def _lean_grid(g: Grid) -> str:
    return "[" + ", ".join("[" + ", ".join(str(c) for c in row) + "]" for row in g) + "]"


def reachable_probes(sealed_fn, initial: Grid, action_arity: int,
                     depth: int = 6, max_pairs: int = 120) -> list:
    """Bounded-BFS over JOINTLY reachable (state, step) pairs under the sealed
    law, crossed with every action. Pairing states with unreachable step
    contexts would demand agreement on physics the environment never presents.
    Step is tracked mod 6 (sound because seed-grammar programs read the step
    only through %2 / %3 guards), with the residue as representative step."""
    seen = {(initial, 0)}
    frontier = [(initial, 0)]
    for _ in range(depth):
        nxt = []
        for s, r in frontier:
            for a in range(action_arity):
                pair = (sealed_fn(s, a, r), (r + 1) % 6)
                if pair not in seen and len(seen) < max_pairs:
                    seen.add(pair)
                    nxt.append(pair)
        frontier = nxt
    return [(s, a, r) for (s, r) in sorted(seen, key=lambda p: (p[1], str(p[0])))
            for a in range(action_arity)]


@dataclass
class LeanCertificate:
    env_id: str
    champion: str
    probes: int
    certified: bool
    lean_file: str
    audit_file: str = ""
    detail: str = ""


def emit_certificate(env_id: str, champion: Program, sealed: Program, probes: list,
                     out_dir: "Path | str", project: "str | None" = None) -> LeanCertificate:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    lean_path = out_dir / f"{env_id}_equivalence.lean"

    probe_rows = ",\n  ".join(
        f"({_lean_grid(s)}, {a}, {t})" for (s, a, t) in probes)
    # No #print axioms here — audit_external appends its own per-decl probes.
    src = f"""{_PRELUDE}
def candidate (s : Grid) (a t : Nat) : Grid := {to_lean(champion)}

def sealedLaw (s : Grid) (a t : Nat) : Grid := {to_lean(sealed)}

def probes : List (Grid × Nat × Nat) := [
  {probe_rows}
]

theorem equivalence_on_probes :
    probes.all (fun p => candidate p.1 p.2.1 p.2.2 == sealedLaw p.1 p.2.1 p.2.2) = true := rfl
"""
    lean_path.write_text(src)

    ensure_elan_on_path()  # cold-lake fallback inside the audit needs lake on PATH
    if project is None:
        project = str(Path(__file__).resolve().parents[3] / "ztare_proofs")
    claim = (f"[GP-250 {env_id}] recovered champion and sealed law agree on all "
             f"{len(probes)} enumerated reachable probes")
    trustworthy, audit_md = audit_external(lean_path, claim_nl=claim, project=project)
    audit_path = out_dir / f"{env_id}_audit.md"
    audit_path.write_text(audit_md)
    cert = LeanCertificate(env_id=env_id, champion=str(champion), probes=len(probes),
                           certified=trustworthy, lean_file=str(lean_path),
                           audit_file=str(audit_path))
    (out_dir / f"{env_id}_certificate.json").write_text(json.dumps(asdict(cert), indent=2))
    return cert


def certify_environment(env, out_dir: "Path | str") -> "LeanCertificate | None":
    """Recover the champion from a reset-witnessing log, then certify against
    the stored sealed AST. Returns None when no certificate is possible
    (inexpressible env, or a champion using a python-level extension)."""
    from ztare.substrates.arc_synthetic import scripted_random_actions
    from ztare.worldmodel.episode_log import EpisodeLog
    from ztare.worldmodel.synthesis import synthesize

    sealed_ast = getattr(env, "sealed_program", None) or getattr(env.transition, "sealed_ast", None)
    if sealed_ast is None:
        return None

    log = EpisodeLog()
    for opening in range(env.action_arity):
        actions = [opening] + scripted_random_actions(env, 19, 11 + opening)
        for t, (s, a, s_next) in enumerate(env.rollout(actions)):
            log.append(s, a, s_next, t=t)
    result = synthesize(log, env.action_arity)
    if result.status != "committee":
        return None
    champion = result.champion
    try:
        to_lean(champion)
    except ValueError:
        return None
    probes = reachable_probes(env.transition, env.initial, env.action_arity)
    # sanity: python-side agreement before spending a kernel reduction
    for (s, a, t) in probes:
        if evaluate(champion, s, a, t) != env.transition(s, a, t):
            return LeanCertificate(env.env_id, str(champion), len(probes), False, "",
                                   detail="python-side probe disagreement; not emitted")
    return emit_certificate(env.env_id, champion, sealed_ast, probes, out_dir)
