"""Finite world-model specification to Lean lowering (GP-250).

``lean_bridge`` consumes the prelude and ``spec_to_lean_step`` through the
governed blueprint path.  This module translates catalog semantics; it does
not emit or ratify a separate certificate artifact.

Semantics notes:
  - connected components (translate_block scoping) are computed by a bounded
    union-growth fixpoint over the MATCH-CELL LIST only (small: the moving
    palette's cells), never the full grid — this keeps kernel reduction
    tractable on 64x64 frames
  - unsupported catalog operations fail during lowering rather than silently
    acquiring semantics
"""

from __future__ import annotations

_PRELUDE = r"""-- generated by ztare.worldmodel.spec_lean (GP-250); dependency-free
set_option linter.unusedVariables false
set_option maxRecDepth 1000000
set_option maxHeartbeats 40000000

abbrev Grid := List (List Nat)
abbrev Cell := Nat × Nat   -- (row, col)

def cellAt (g : Grid) (y x : Nat) : Nat := (g.getD y []).getD x 0

def gridMap (g : Grid) (f : Nat → Nat → Nat → Nat) : Grid :=
  (List.range g.length).map fun y =>
    (List.range ((g.getD y []).length)).map fun x => f y x (cellAt g y x)

def recolorMap (g : Grid) (m : List (Nat × Nat)) : Grid :=
  gridMap g fun _ _ c => ((m.find? (fun p => p.1 = c)).map Prod.snd).getD c

-- consume_extremal over rows: recolor the min/max-index cell of `color`
def consumeRowExtremal (g : Grid) (color repl : Nat) (useMin : Bool) : Grid :=
  g.map fun row =>
    let idxs := (List.range row.length).filter (fun x => row.getD x 0 = color)
    match (if useMin then idxs.head? else idxs.getLast?) with
    | none => row
    | some k => (List.range row.length).map fun x => if x = k then repl else row.getD x 0

def countColor (g : Grid) (c : Nat) : Nat :=
  (g.map (fun row => (row.filter (fun v => v = c)).length)).foldl (· + ·) 0

-- when_overlap predicate: does any cell of `colors` fall in the inclusive rect?
def overlapAny (g : Grid) (colors : List Nat) (y0 x0 y1 x1 : Nat) : Bool :=
  (List.range g.length).any fun y =>
    (List.range ((g.getD y []).length)).any fun x =>
      y0 ≤ y && y ≤ y1 && x0 ≤ x && x ≤ x1 && colors.contains (cellAt g y x)

def consumeRowExtremalK (g : Grid) (color repl : Nat) (useMin : Bool) : Nat → Grid
  | 0 => g
  | Nat.succ k => consumeRowExtremalK (consumeRowExtremal g color repl useMin) color repl useMin k

def rateCount (t p q : Nat) : Nat :=
  (((t + 1) * p) / q) - ((t * p) / q)

-- bounded connected-components over the MATCH-CELL LIST (4-connectivity):
-- grow the component containing `seed` by fixpoint, at most cells.length steps
def adj (a b : Cell) : Bool :=
  (a.1 = b.1 && (a.2 + 1 = b.2 || b.2 + 1 = a.2)) ||
  (a.2 = b.2 && (a.1 + 1 = b.1 || b.1 + 1 = a.1))

def growOnce (comp rest : List Cell) : List Cell × List Cell :=
  let added := rest.filter (fun c => comp.any (fun k => adj k c))
  (comp ++ added, rest.filter (fun c => ¬ comp.any (fun k => adj k c)))

def component (seed : Cell) (cells : List Cell) (fuel : Nat) : List Cell :=
  match fuel with
  | 0 => [seed]
  | Nat.succ f =>
    let rec go (n : Nat) (comp rest : List Cell) : List Cell :=
      match n with
      | 0 => comp
      | Nat.succ m =>
        let (c2, r2) := growOnce comp rest
        if c2.length = comp.length then comp else go m c2 r2
    go (Nat.succ f) [seed] (cells.filter (fun c => c ≠ seed))

def matchCells (g : Grid) (colors : List Nat) : List Cell :=
  ((List.range g.length).map fun y =>
    ((List.range ((g.getD y []).length)).filter
      (fun x => colors.contains (cellAt g y x))).map (fun x => (y, x))).flatten

def componentsOf (g : Grid) (colors : List Nat) : List (List Cell) :=
  let cells := matchCells g colors
  let rec go (n : Nat) (remaining : List Cell) (acc : List (List Cell)) : List (List Cell) :=
    match n, remaining with
    | 0, _ => acc
    | _, [] => acc
    | Nat.succ m, seed :: _ =>
      let comp := component seed remaining remaining.length
      go m (remaining.filter (fun c => ¬ comp.contains c)) (acc ++ [comp])
  go cells.length cells []

def distinctColors (g : Grid) (comp : List Cell) : Nat :=
  (comp.map (fun c => cellAt g c.1 c.2)).eraseDups.length

def compOk (g : Grid) (comp : List Cell) (dy dx : Int) (destOk : List Nat)
    (minColors : Nat) : Bool :=
  (minColors ≤ distinctColors g comp) &&
  comp.all (fun c =>
    let ny := (c.1 : Int) + dy
    let nx := (c.2 : Int) + dx
    0 ≤ ny && ny < (g.length : Int) && 0 ≤ nx && nx < ((g.getD 0 []).length : Int) &&
    (comp.contains (ny.toNat, nx.toNat) || destOk.contains (cellAt g ny.toNat nx.toNat)))

def translateBlock (g : Grid) (colors : List Nat) (dy dx : Int) (destOk : List Nat)
    (fill : Nat) (minColors : Nat) : Grid :=
  let comps := (componentsOf g colors).filter
    (fun comp => compOk g comp dy dx destOk minColors)
  let movedSrc := comps.flatten
  gridMap g fun y x c =>
    let src := ((y : Int) - dy, (x : Int) - dx)
    if 0 ≤ src.1 && 0 ≤ src.2 &&
       movedSrc.contains (src.1.toNat, src.2.toNat) then
      cellAt g src.1.toNat src.2.toNat
    else if movedSrc.contains (y, x) then fill
    else c

-- region_event: iff the mover CROSSED the rect between the step-start grid `s`
-- and the current grid `g` in the named direction, write learned (y,x,color)
-- triples. isExit = mover in the rect on `s` but gone on `g`; else the reverse.
def writeTriples (g : Grid) (ts : List (Nat × Nat × Nat)) : Grid :=
  gridMap g fun y x c =>
    ((ts.find? (fun t => t.1 == y && t.2.1 == x)).map (fun t => t.2.2)).getD c

def regionEvent (g s : Grid) (colors : List Nat) (y0 x0 y1 x1 : Nat)
    (isExit : Bool) (ts : List (Nat × Nat × Nat)) : Grid :=
  let o0 := overlapAny s colors y0 x0 y1 x1
  let o1 := overlapAny g colors y0 x0 y1 x1
  let fired := if isExit then (o0 && ! o1) else ((! o0) && o1)
  if fired then writeTriples g ts else g

-- region_event TOGGLE/CYCLE: on fire, permute paired colours over the cell-set.
-- `perm` is the flattened (from, to) map; a colour absent from it is unchanged.
def permAt (perm : List (Nat × Nat)) (c : Nat) : Nat :=
  ((perm.find? (fun p => p.1 = c)).map Prod.snd).getD c

def permCells (g : Grid) (cells : List Cell) (perm : List (Nat × Nat)) : Grid :=
  gridMap g fun y x c => if cells.contains (y, x) then permAt perm c else c

def regionEventPerm (g s : Grid) (colors : List Nat) (y0 x0 y1 x1 : Nat)
    (isExit : Bool) (cells : List Cell) (perm : List (Nat × Nat)) : Grid :=
  let o0 := overlapAny s colors y0 x0 y1 x1
  let o1 := overlapAny g colors y0 x0 y1 x1
  let fired := if isExit then (o0 && ! o1) else ((! o0) && o1)
  if fired then permCells g cells perm else g

-- when_region guard: does the rect's row-major contents equal the pattern?
def regionEquals (g : Grid) (y0 x0 y1 x1 : Nat) (pat : List Nat) : Bool :=
  (((List.range (y1 + 1 - y0)).map fun dy =>
    (List.range (x1 + 1 - x0)).map fun dx => cellAt g (y0 + dy) (x0 + dx)).flatten) == pat

-- region-STATE machine: the region's row-major content (read on the STEP-START
-- grid `s`) is matched to one of `states` and rewritten to its successor under
-- `trans` (an explicit (from,to) index map; a ring cycle is just its k pairs).
-- Unknown content or no outgoing edge => fail-closed (region untouched). This is
-- the ONLY region write that fits a glyph whose lit block SHIFTS on each crossing
-- — cell-wise content equality per state, not a per-cell colour map.
def regionContent (g : Grid) (y0 x0 y1 x1 : Nat) : List Nat :=
  ((List.range (y1 + 1 - y0)).map fun dy =>
    (List.range (x1 + 1 - x0)).map fun dx => cellAt g (y0 + dy) (x0 + dx)).flatten

def stateIndex (states : List (List Nat)) (c : List Nat) : Option Nat :=
  (List.range states.length).find? (fun k => states.getD k [] == c)

def regionEventStates (g s : Grid) (colors : List Nat) (y0 x0 y1 x1 : Nat)
    (isExit : Bool) (ry0 rx0 ry1 rx1 : Nat)
    (states : List (List Nat)) (trans : List (Nat × Nat)) : Grid :=
  let o0 := overlapAny s colors y0 x0 y1 x1
  let o1 := overlapAny g colors y0 x0 y1 x1
  let fired := if isExit then (o0 && ! o1) else ((! o0) && o1)
  if ! fired then g else
  match stateIndex states (regionContent s ry0 rx0 ry1 rx1) with
  | none => g
  | some i =>
    match (trans.find? (fun p => p.1 = i)).map Prod.snd with
    | none => g
    | some j =>
      let st := states.getD j []
      let wcols := rx1 + 1 - rx0
      gridMap g fun y x c =>
        if ry0 ≤ y && y ≤ ry1 && rx0 ≤ x && x ≤ rx1 then
          st.getD ((y - ry0) * wcols + (x - rx0)) c
        else c

-- when_dest guard (relational): does any destination cell of a qualifying
-- component (each cell displaced by the referenced rule's own dy/dx, outside
-- the component) hold one of `cs`? Object-anchored, no absolute coordinates.
def destHolds (g : Grid) (colors : List Nat) (dy dx : Int) (minColors : Nat)
    (cs : List Nat) : Bool :=
  ((componentsOf g colors).filter
    (fun comp => minColors ≤ distinctColors g comp)).any fun comp =>
      comp.any fun c =>
        let ny := (c.1 : Int) + dy
        let nx := (c.2 : Int) + dx
        0 ≤ ny && ny < (g.length : Int) && 0 ≤ nx && nx < ((g.getD 0 []).length : Int) &&
        ¬ comp.contains (ny.toNat, nx.toNat) && cs.contains (cellAt g ny.toNat nx.toNat)
"""


def _lean_int_list(xs) -> str:
    return "[" + ", ".join(str(int(x)) for x in xs) + "]"


def _count_to_lean(rule: dict) -> str:
    if "rate" in rule:
        p, q = int(rule["rate"][0]), int(rule["rate"][1])
        return f"(rateCount t {p} {q})"
    return str(int(rule.get("count", 1)))


def _rule_to_lean(rule: dict, g_expr: str) -> str:
    op = rule["op"]
    if op == "identity":
        return g_expr
    if op == "recolor_map":
        pairs = ", ".join(f"({int(k)}, {int(v)})" for k, v in rule["mapping"].items())
        return f"(recolorMap {g_expr} [{pairs}])"
    if op == "consume_extremal":
        if rule.get("axis", "row") != "row":
            raise ValueError("consume_extremal axis=col has no Lean translation yet")
        use_min = "true" if rule.get("extreme", "min") == "min" else "false"
        k = _count_to_lean(rule)
        if k == "1":
            return (f"(consumeRowExtremal {g_expr} {int(rule['color'])} "
                    f"{int(rule['replacement'])} {use_min})")
        return (f"(consumeRowExtremalK {g_expr} {int(rule['color'])} "
                f"{int(rule['replacement'])} {use_min} {k})")
    if op == "accumulate_extremal":
        # transpose of consume_extremal: fill the extremal-index EMPTY (`from`)
        # cell with `color` == set the extremal cell of value `from` to `color`.
        # Reuse consumeRowExtremal with (match, write) swapped — one def carries
        # both, which is the alias made proof-level explicit.
        if rule.get("axis", "row") != "row":
            raise ValueError("accumulate_extremal axis=col has no Lean translation yet")
        use_min = "true" if rule.get("extreme", "min") == "min" else "false"
        empty, color = int(rule.get("from", 0)), int(rule["color"])
        k = _count_to_lean(rule)
        if k == "1":
            return f"(consumeRowExtremal {g_expr} {empty} {color} {use_min})"
        return f"(consumeRowExtremalK {g_expr} {empty} {color} {use_min} {k})"
    if op == "translate_block":
        return (f"(translateBlock {g_expr} {_lean_int_list(rule['match_colors'])} "
                f"({int(rule['dy'])} : Int) ({int(rule['dx'])} : Int) "
                f"{_lean_int_list(rule['require_dest_colors'])} {int(rule['fill_color'])} "
                f"{int(rule.get('component_min_colors', 1))})")
    if op == "region_event":
        from ztare.worldmodel.spec_catalog import _perm_from_rule
        y0, x0, y1, x1 = (int(v) for v in rule["rect"])
        is_exit = "true" if rule.get("edge", "exit") == "exit" else "false"
        states = rule.get("content_states")
        if states is not None:
            ry0, rx0, ry1, rx1 = (int(v) for v in rule["region"])
            k = len(states)
            tr = rule.get("state_transition", "cycle")
            pairs = ([(i, (i + 1) % k) for i in range(k)] if tr == "cycle"
                     else [(int(f), int(t)) for f, t in tr])
            st_lit = "[" + ", ".join(_lean_int_list(s) for s in states) + "]"
            tr_lit = "[" + ", ".join(f"({f}, {t})" for f, t in pairs) + "]"
            return (f"(regionEventStates {g_expr} s {_lean_int_list(rule['mover_colors'])} "
                    f"{y0} {x0} {y1} {x1} {is_exit} {ry0} {rx0} {ry1} {rx1} "
                    f"{st_lit} {tr_lit})")
        perm = _perm_from_rule(rule)
        if perm:
            cells = ", ".join(f"({int(y)}, {int(x)})"
                              for _c, cs in rule["writes"] for (y, x) in cs)
            pm = ", ".join(f"({int(a)}, {int(b)})" for a, b in perm.items())
            return (f"(regionEventPerm {g_expr} s {_lean_int_list(rule['mover_colors'])} "
                    f"{y0} {x0} {y1} {x1} {is_exit} [{cells}] [{pm}])")
        triples = ", ".join(f"({int(y)}, {int(x)}, {int(color)})"
                            for color, cells in rule["writes"] for (y, x) in cells)
        return (f"(regionEvent {g_expr} s {_lean_int_list(rule['mover_colors'])} "
                f"{y0} {x0} {y1} {x1} {is_exit} [{triples}])")
    raise ValueError(f"no Lean translation for op {op!r}")


def spec_to_lean_step(spec: dict) -> str:
    """The spec's step as a Lean definition over (s a t). when_t_mod guards
    translate to if-conditions on t.

    when_effect (rule-coupling) parity: the Python kernel threads a real
    fired-flag through _run (a rule "fired" iff it changed the grid). In Lean we
    express "the referenced rule fired" for the case the refine actually
    produces — the referenced id is the LEADING rule of an action list, so its
    input is the step-start grid `s` — by recomputing that rule on `s` and
    testing inequality. A when_effect whose referent is not a step-start rule
    raises (no wrong certificate is emitted).
    # ponytail: step-start recomputation covers every spec the abduction emits;
    # full let-threaded flags across the action/always boundary only if a future
    # coupling references a mid-chain rule.
    """
    _fresh = [0]
    leading_by_id = {str(rules[0]["id"]): rules[0]
                     for rules in spec.get("actions", {}).values()
                     if rules and rules[0].get("id") is not None}

    def guard_expr(r, g_expr, body, act_rules=()):
        conds = []
        tm = r.get("when_t_mod")
        if tm is not None:
            conds.append(f"t % {int(tm[0])} = {int(tm[1])}")
        wp = r.get("when_phase")
        if wp is not None:
            conds.append(f"t % {int(wp[0])} = {int(wp[1])}")
        wr = r.get("when_region")
        if wr is not None:
            y0, x0, y1, x1, pat = wr
            conds.append(f"regionEquals s {int(y0)} {int(x0)} {int(y1)} {int(x1)} "
                         f"{_lean_int_list(pat)} = true")
        wc = r.get("when_count")
        if wc is not None:
            color, lo, hi = wc
            # step-start semantics: guards read the ORIGINAL input `s`
            if lo is not None:
                conds.append(f"{int(lo)} ≤ countColor s {int(color)}")
            if hi is not None:
                conds.append(f"countColor s {int(color)} ≤ {int(hi)}")
        wo = r.get("when_overlap")
        if wo is not None:
            colors, y0, x0, y1, x1 = wo
            # positional pause: the rule fires only while NO cell of `colors`
            # sits in the rect (overlap suppresses it) — step-start grid `s`
            conds.append(f"overlapAny s {_lean_int_list(colors)} "
                         f"{int(y0)} {int(x0)} {int(y1)} {int(x1)} = false")
        we = r.get("when_effect")
        if we is not None:
            ref, want = str(we[0]), bool(we[1])
            ref_rule = leading_by_id.get(ref)
            if ref_rule is None:
                raise ValueError(f"when_effect ref {ref!r} is not a step-start "
                                 "(leading) rule; Lean lowering unsupported")
            applied = _rule_to_lean(ref_rule, "s")
            # fired iff applying the referenced leading rule to `s` changes it
            conds.append(f"({applied} == s) = {'false' if want else 'true'}")
        wd = r.get("when_dest")
        if wd is not None:
            # relational destination gate: resolved against the CURRENT action's
            # id'd translate (each Lean branch is one action, so it is static
            # here); no referent under this action -> the predicate is False
            ref_rule = next((ar for ar in act_rules
                             if ar.get("op") == "translate_block"
                             and str(ar.get("id")) == str(wd[0])), None)
            want = bool(wd[2])
            if ref_rule is None:
                if want:            # False != True -> the rule never fires here
                    return g_expr
            else:
                conds.append(
                    f"destHolds s {_lean_int_list(ref_rule['match_colors'])} "
                    f"({int(ref_rule['dy'])} : Int) ({int(ref_rule['dx'])} : Int) "
                    f"{int(ref_rule.get('component_min_colors', 1))} "
                    f"{_lean_int_list(wd[1])} = {'true' if want else 'false'}")
        if not conds:
            return body
        cond = " ∧ ".join(conds)
        return f"(if {cond} then {body} else {g_expr})"

    def chain(rules, g_expr, act_rules=()):
        rules = list(rules)
        if not rules:
            return g_expr
        r, rest = rules[0], rules[1:]
        body = guard_expr(r, g_expr, _rule_to_lean(r, g_expr), act_rules)
        if r.get("stop_if_applied") and rest:
            # faithful control flow: if the guarded rule CHANGED the grid it
            # shadows the remaining rules of this list, else the chain continues
            _fresh[0] += 1
            v = f"g{_fresh[0]}"
            rest_expr = chain(rest, g_expr, act_rules)
            return (f"(let {v} := {body}; if {v} == {g_expr} then {rest_expr} else {v})")
        return chain(rest, body, act_rules)

    branches = []
    for a_str in sorted(spec["actions"], key=int):
        act_rules = spec["actions"][a_str]
        expr = chain(act_rules, "s", act_rules)
        expr = chain(spec.get("always", []), expr, act_rules)
        branches.append((int(a_str), expr))
    body = branches[-1][1]
    for a, expr in reversed(branches[:-1]):
        body = f"(if a = {a} then {expr} else {body})"
    return f"def specStep (s : Grid) (a t : Nat) : Grid := {body}"
