#!/usr/bin/env python3
"""GP-XXX index builder — Linus MAINTAINERS-style auto-generated index.

GP-157 v5.0 Phase 5 Fix 1 (panel-approved 2026-04-25 night).

Walks the repo for GP-NNN references and writes
`docs/internal/gp_index.md` (markdown, human-readable) and
`docs/internal/gp_index.tsv` (tab-separated, grep/awk-friendly per
Kernighan).

Usage:
    python3 scripts/build_gp_index.py
    make gp-index    # alias

Per panel cross-cutting concern: walks BOTH `research_areas/` AND
`docs/internal/` (single-tree walker would miss half the artifacts).

Per Karpathy: <100 lines, regenerates in <5s, or it'll bit-rot. This
script is 130 lines (slightly over) but no faster compression sacrifices
the data clarity.

Status enum (panel collapse — 3 states): `active | shipped | archived`.
Read from YAML frontmatter `status:` if present; fall back to dirpath
heuristics (`archived/` → archived; `specs/active/` → active; etc.).
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from datetime import datetime, timezone

REPO = Path(__file__).resolve().parent.parent
SCAN_ROOTS = [
    REPO / "research_areas",
    REPO / "docs" / "internal",
    REPO / "projects",
    REPO / "rubrics",
]

GP_PATTERN = re.compile(r"(?:^|[^A-Za-z])GP[-_]?(\d{3})(?:[^0-9]|$)", re.IGNORECASE)
FRONTMATTER_PATTERN = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


@dataclass
class GPArtifact:
    gp_id: str                       # canonical "GP-NNN"
    kind: str                        # seam / spec / project / rubric / postmortem / philosophy / other
    path: Path                       # primary file (or dir)
    status: str                      # active / shipped / archived (panel-collapsed enum)
    last_modified: str               # ISO date


def _kind_from_path(p: Path) -> str:
    s = str(p.relative_to(REPO))
    if "/postmortems/" in s: return "postmortem"
    if "/philosophy/" in s: return "philosophy"
    if "/seams/" in s: return "seam"
    if "/specs/" in s: return "spec"
    if s.startswith("projects/"): return "project"
    if s.startswith("rubrics/"): return "rubric"
    if "/internal/" in s: return "doc"
    return "other"


def _status_from_path_or_frontmatter(p: Path) -> str:
    s = str(p.relative_to(REPO))
    if "/archived/" in s or "/_archive/" in s: return "archived"
    # Try frontmatter
    try:
        text = p.read_text() if p.is_file() else ""
        m = FRONTMATTER_PATTERN.match(text)
        if m:
            for line in m.group(1).splitlines():
                if line.startswith("status:"):
                    val = line.split(":", 1)[1].strip().strip('"').strip("'")
                    if val in {"active", "shipped", "archived"}:
                        return val
                    # Map legacy verbose enum to collapsed 3-state
                    if val in {"proposed", "debating", "spec", "implementing"}:
                        return "active"
                    if val in {"retired"}:
                        return "archived"
    except Exception:
        pass
    # Path-based fallback
    if "/specs/active/" in s: return "active"
    if "/seams/" in s and "/_archive/" not in s: return "active"
    if s.startswith("projects/"): return "active"
    return "active"


def scan() -> dict[str, list[GPArtifact]]:
    """Walk SCAN_ROOTS, find GP-NNN artifacts, group by canonical id."""
    artifacts: dict[str, list[GPArtifact]] = defaultdict(list)
    for root in SCAN_ROOTS:
        if not root.exists():
            continue
        for p in root.rglob("*"):
            if not p.is_file() and not p.is_dir():
                continue
            # Match name; for dirs match the basename
            name = p.name
            m = GP_PATTERN.search(name)
            if not m:
                continue
            num = m.group(1)
            gp_id = f"GP-{num}"
            kind = _kind_from_path(p)
            status = _status_from_path_or_frontmatter(p) if p.is_file() else "active"
            try:
                mtime = datetime.fromtimestamp(p.stat().st_mtime, tz=timezone.utc).strftime("%Y-%m-%d")
            except Exception:
                mtime = "?"
            artifacts[gp_id].append(GPArtifact(gp_id, kind, p, status, mtime))
    return artifacts


def write_outputs(artifacts: dict[str, list[GPArtifact]]) -> None:
    md_path = REPO / "docs" / "internal" / "gp_index.md"
    tsv_path = REPO / "docs" / "internal" / "gp_index.tsv"

    md_lines: list[str] = []
    tsv_lines: list[str] = ["gp_id\tkind\tstatus\tpath\tlast_modified"]

    md_lines.append("# GP-XXX Index — auto-generated\n")
    md_lines.append(
        f"_Generated by `scripts/build_gp_index.py` at "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. "
        f"Do NOT hand-edit; re-run the script (`make gp-index`)._\n"
    )
    md_lines.append("\n## Summary\n")
    by_kind: dict[str, int] = defaultdict(int)
    by_status: dict[str, int] = defaultdict(int)
    total = 0
    for gp_id, items in artifacts.items():
        for a in items:
            by_kind[a.kind] += 1
            by_status[a.status] += 1
            total += 1
    md_lines.append(f"- **Total artifacts**: {total}")
    md_lines.append(f"- **Unique GP-NNNs**: {len(artifacts)}")
    md_lines.append(f"- **By kind**: " + ", ".join(f"{k}={v}" for k, v in sorted(by_kind.items())))
    md_lines.append(f"- **By status**: " + ", ".join(f"{k}={v}" for k, v in sorted(by_status.items())))
    md_lines.append("")

    md_lines.append("\n## Artifacts (sorted by GP-NNN)\n")
    md_lines.append("| GP-id | Kind | Status | Path | Last modified |")
    md_lines.append("|---|---|---|---|---|")

    for gp_id in sorted(artifacts.keys(), key=lambda s: int(s.split("-")[1])):
        for a in sorted(artifacts[gp_id], key=lambda a: (a.kind, str(a.path))):
            rel = a.path.relative_to(REPO)
            md_lines.append(f"| {a.gp_id} | {a.kind} | {a.status} | `{rel}` | {a.last_modified} |")
            tsv_lines.append(f"{a.gp_id}\t{a.kind}\t{a.status}\t{rel}\t{a.last_modified}")

    md_path.write_text("\n".join(md_lines) + "\n")
    tsv_path.write_text("\n".join(tsv_lines) + "\n")
    print(f"✅ wrote {md_path.relative_to(REPO)} ({total} artifacts, {len(artifacts)} GP-NNNs)")
    print(f"✅ wrote {tsv_path.relative_to(REPO)}")


def main(argv: list[str]) -> int:
    artifacts = scan()
    if not artifacts:
        print("⚠️  no GP-NNN artifacts found", file=sys.stderr)
        return 1
    write_outputs(artifacts)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
