"""Canonical prompt templates shared across LeanMill control-plane surfaces.

Proof-solver-only prompts remain in ``ztare.leanmill.solver.prompts``. Prompts
used by AxiomPack, campaign compilation, adapter synthesis, or other LeanMill
subsystems live here so those layers do not import the solver package.
"""
from __future__ import annotations


AXIOM_PACK_TYPED_PROPOSER_PROMPT = (
    "Return one JSON object matching the output schema. Choose exactly one outcome: "
    "`typed_proposals`, `no_candidate`, or `language_capability_gap`. For "
    "`typed_proposals`, emit a non-empty `typed_axiom_proposals` array. Each row "
    "authors a `source_conjecture` and an executable AxiomFormula IR serialization "
    "in `axiom_formula_json`, and echoes the frozen `theory_signature_sha256` and "
    "`base_theory_digest`. Use only symbols and sorts from the frozen signature. "
    "For `no_candidate`, leave the proposal array empty and explain the mathematical "
    "reason in `no_candidate_reason`. Use `language_capability_gap` only when you cannot "
    "author the requested IR; name the missing language feature in that field. Leave "
    "the two unused outcome strings empty. Do not emit a semantic verdict, proof, task "
    "reference, or explanatory text outside the JSON object.\n\n"
    "OUTPUT SCHEMA:\n{output_schema}\n\n"
    "PROPOSER VIEW:\n{proposer_view}"
)

AXIOM_PACK_BAND_WORD_PROPOSER_PROMPT = (
    "Return only the constrained transport object with exactly one "
    "`typed_axiom_proposals` row. The row has exactly `source_ref`, `axiom_name`, "
    "`lhs_word`, `rhs_word`, `nl_intent`, and `kill_condition`. `source_ref` must be "
    "one of the frozen references in the proposer view. `lhs_word` and `rhs_word` "
    "must be non-empty lowercase variable words of at most twelve characters. LeanMill "
    "interprets each word by left-associated multiplication and constructs the typed "
    "formula. Do not emit source bytes, hashes, signatures, a semantic verdict, "
    "proof, task reference, or explanation.\n\n"
    "PROPOSER VIEW:\n{proposer_view}"
)

AXIOM_PACK_SEMANTIC_CHECKER_PROMPT = (
    "Review whether this typed axiom matches its structural conjecture. "
    "Return only JSON with boolean `faithful`, non-empty string `rationale`, "
    "and non-empty list `evidence_refs`. Do not sign anything.\n\n"
    "CHECK INPUT:\n{check_input}"
)

FRONTIER_BLUEPRINT_COMPILER_PROMPT = (
    "Compile the research direction into one typed frontier-theory campaign draft. "
    "Return JSON only. In anonymous_signature_census mode do not propose candidate axioms, "
    "named axiom lists, target theories, or literature labels. Specify executable primitive "
    "semantics, a registered adapter, a finite formula grammar, model/observation strata, "
    "verification plan, deanchoring policy, budgets, and stop rule. If the brief carries a "
    "finite typed first-order signature outside a registered exact surface, prefer "
    "`generic_fol_finite.v1` over a family-named adapter. The canonical anonymous single-binary-"
    "operation equation census is a registered exact surface and uses `magma_equational.v1`. "
    "When raw table iteration is infeasible but the base theory is "
    "solver-executable, set `adapter_config.model_generation` to "
    "{{\"mode\":\"smt_exact\",\"max_canonical_models_per_stratum\":N,"
    "\"timeout_ms_per_stratum\":T}}`; this remains exact only if the host reaches final "
    "UNSAT and otherwise fails preparation. The model-count value is provisional: the host "
    "replaces it with the per-stratum share of the user's context-model budget. "
    "For `generic_fol_finite.v1`, the host-enumerable equation grammar is exactly "
    "`{{\"schema\":\"leanmill.universal_equation_grammar.v1\","
    "\"max_total_operation_order\":N,\"max_variables_per_sort\":N,"
    "\"max_formulas\":N,\"variable_renaming_quotient\":true,"
    "\"equation_side_quotient\":true,\"exclude_nonvariable_reflexive\":true}}`; "
    "do not invent a generic-FOL grammar schema. Its context strata are exact "
    "`{{\"sort_sizes\":{{\"S0\":N}}}}` rows naming every signature sort. Put larger "
    "heldout sizes under the exact `verification_plan.heldout_strata` key, not in "
    "the initial context strata; never emit `holdout_strata`. If no "
    "registered adapter can execute the requested semantics, choose a clear unregistered "
    "adapter ID so preflight emits an AdapterGap; never mimic support with invented fields. "
    "When the direction requires a byte-identical or frozen adapter configuration from a public "
    "evidence reference, inspect that referenced JSON and copy the configuration exactly; do not "
    "reconstruct or redesign it from the direction prose. "
    "For a signature containing an operation of arity three or greater, start the orientation "
    "grammar at `max_total_operation_order=2` with `max_formulas` at least 1000 and within "
    "the declared truth-cell budget, so the safety cap is large enough "
    "to contain that complete band; later formula epochs can expand the language. Reducing "
    "`max_formulas` never truncates a band and cannot repair an overflow. "
    "If the brief carries a "
    "minimum or exact number of formulas per candidate presentation, encode it as "
    "navigator_contract.presentation_size with integer minimum/maximum bounds no larger "
    "than pack_arity. Default navigator_contract.selection_mode to `theory_program`; use "
    "`compact_axiom_pack` only when the direction explicitly asks for minimal jointly "
    "necessary presentations. "
    "Set navigator_contract.host_isolated_lineages above 1 only when independent "
    "conjectural traces are scientifically useful and the provider-call budget can give "
    "each trace at least one turn; this is search diversification, not proof authority. "
    "The eigenquestion must preserve the direction's search identity. If the direction asks "
    "to invent coordinates, representations, or theory language, do not reduce it to selecting "
    "candidates from the initial finite grammar. "
    "If the brief contains `compiler_feedback` and `prior_draft`, repair the stated contract "
    "failure and return the complete corrected draft without a wrapper. "
    "Emit executable LeanMill IR, never a prose design schema. Do not add top-level `schema` or "
    "`brief_id`. `signature` must use schema `leanmill.theory_signature.v1` and have exactly "
    "`schema`, `name`, `sorts:[{{name}}]`, `operations:[{{name,arg_sorts,result_sort}}]`, and "
    "`relations:[{{name,arg_sorts}}]`. `primitive_semantics` must be an object with "
    "`operation_bindings` and `relation_bindings` maps keyed by those exact symbol names. "
    "Primitive semantics binds symbols to observations; it does not restrict the adapter's "
    "model class. Every condition that decides whether a finite structure belongs to the "
    "requested substrate (for example cancellation, recoverability, injectivity, or incidence) "
    "must be lowered into typed `base_axioms`, or executed by a registered adapter. Never place "
    "such a condition only in descriptive binding metadata. "
    "`base_axioms` contains only recursive `leanmill.axiom_formula.v1` objects with exact "
    "shape `{{\"schema\":\"leanmill.axiom_formula.v1\",\"name\":ID,\"formula\":FORMULA}}`; "
    "FORMULA is an object, never a string. Formula objects use `kind` with: equality "
    "`{{kind:eq,left:TERM,right:TERM}}`; implication `{{kind:implies,left:FORMULA,right:FORMULA}}`; "
    "or quantification `{{kind:forall,binders:[{{name,sort}}],body:FORMULA}}`. Terms are "
    "`{{kind:var,name}}` or `{{kind:app,symbol,args:[TERM,...]}}`. The IR has no `exists!`; "
    "on a finite equal-size carrier, encode unique coordinate recovery as the corresponding "
    "universally quantified coordinate-injectivity implications. Use "
    "`base_theory_status=typed_resolved` whenever base axioms are present. Use `[]` with "
    "`base_theory_status=explicit_empty` when there are none. `collapse_controls` is an array. "
    "`verification_plan`, `query_budget`, and `stop_rule` are JSON objects, never stage arrays; "
    "`model_or_observation_strata` is the array of context rows. The host binds evidence "
    "manifests, their digest, and authority references; do not emit those host-owned fields. "
    "Do not invent alternate field names, semantic-constraint records, procedures, stages, or "
    "adapter schemas. For an anonymous single total binary operation with the canonical magma "
    "equation grammar, use registered adapter `magma_equational.v1`, operation name `op0`, sort "
    "name `S0`, formula-grammar schema `leanmill.magma_law_universe.v1`, and its declared config. "
    "Its navigator contract uses only `adapter_id`, `selection_mode`, `presentation_size` with "
    "`minimum`/`maximum`, and `host_isolated_lineages`; do not add a navigator schema, "
    "`topology_presentation_size`, or policy prose. The host chooses the bounded topology overview "
    "width independently of candidate-theory width. A delegated late-review stop lowers to exactly "
    "`executable_condition:{{\"kind\":\"late_lineage_objective_review\"}}`. "
    "This is the only supported executable-condition shape for every scientific stop. Do not "
    "add a stop-rule schema, receipt-threshold kind, required-receipts list, or numeric threshold. "
    "An executable stop condition always carries a nonempty `user_instruction`. When the "
    "direction itself states a scientific stopping sentence but the brief has no separately "
    "compiled delegated-stop field, copy that sentence verbatim into `user_instruction`; never "
    "emit the executable condition with an empty instruction. "
    "If the brief carries a delegated_stop_instruction, copy it "
    "exactly to stop_rule.user_instruction and use that same late-review condition. Required fields: "
    "{required_fields}\n\nBRIEF:\n{brief_json}"
)

AXIOMPACK_CAMPAIGN_BUDGET_COMPILER_PROMPT = (
    "Compile the user's campaign-budget preference into the exact user campaign schema below. "
    "Return one JSON object only; JSON is the structured transport and the host renders the canonical YAML. "
    "Choose a named preset as the base, then include explicit caps. Preserve any mathematical stopping "
    "condition verbatim in stop.when; do not invent a theorem, candidate axiom, success criterion, or larger "
    "budget. If no budget preference is stated, use the standard preset unchanged. model_transport must be "
    "subscription_agent_runtime. Required shape: "
    "{{\"schema\":\"leanmill.exploration_budget_user.v1\",\"preset\":\"standard\","
    "\"budget\":{{\"wall_clock\":\"2h\",\"provider_calls\":24,\"agent_turns\":30,"
    "\"input_tokens\":750000,\"output_tokens\":250000,\"metered_api_usd\":\"20\","
    "\"workbench_actions\":96,\"adapter_forge_attempts\":2,"
    "\"context\":{{\"models\":100000,\"truth_cells\":50000000}},"
    "\"boundary\":{{\"queries\":12,\"smt_calls\":12,\"smt_time\":\"1h\","
    "\"lean_attempts\":6,\"lean_time\":\"1h\"}}}},"
    "\"stop\":{{\"max_finalists\":8,\"low_yield_patience\":3,"
    "\"min_marginal_information_per_cost\":\"0.05\",\"coverage_target\":\"0.9\","
    "\"when\":null}},\"model_transport\":\"subscription_agent_runtime\"}}.\n\n"
    "CAMPAIGN DIRECTION / BUDGET PREFERENCE:\n{preference_text}"
)

FRONTIER_BLUEPRINT_SEMANTIC_REVIEW_PROMPT = (
    "Independently review a proposed frontier-theory blueprint against its research brief. "
    "Check that the typed signature and primitive semantics preserve the requested exploration "
    "surface, that the adapter semantics are adequate, and that a cold census contains no "
    "candidate laws, named axiom lists, hidden target theory, or literature labels. "
    "Trace every condition that defines membership in the requested substrate to an executable "
    "typed base axiom or a registered adapter behavior. Descriptive primitive-semantics metadata "
    "has no model-filtering authority. Reject if any defining condition exists only in prose. "
    "The review input includes the deterministic executable-preflight receipt. Use its registered "
    "adapter identity, adapter preflight, and capability list as evidence for adapter-owned behavior; "
    "do not require a duplicate typed base axiom for a condition that this receipt shows the adapter "
    "executes. A named capability alone does not cover a condition unless its frozen adapter config "
    "and preflight receipt bind that condition. "
    "Frozen base axioms that encode the brief's model-class definition are required executable "
    "semantics, not candidate-law leakage. Candidate-law leakage means seeding a law or target that "
    "the navigator was meant to invent. Do not classify the brief's own structural definition as a "
    "candidate merely because it is encoded as a formula. "
    "Reject a draft whose eigenquestion turns an invention or evolving-language direction into "
    "selection within the initial formula catalog. "
    "Return only JSON with `accepted` (boolean), `candidate_law_leakage` (boolean), "
    "`substrate_constraints_executable` (boolean), non-empty `rationale`, "
    "and non-empty `evidence_refs`. If a delegated scientific stop instruction is present, also "
    "return `stop_rule_aligned` and set it true only when the lowering preserves the instruction "
    "and is executable from host receipts. The registered `late_lineage_objective_review` condition "
    "is the host-executed stop transition; judge whether its `user_instruction` preserves the delegated "
    "scientific stop, rather than requiring another stop-condition vocabulary. Do not sign or mutate "
    "the draft.\n\nREVIEW INPUT:\n{review_json}"
)

ADAPTER_FORGE_PROMPT = (
    "Implement the missing TheorySubstrateAdapter in the staged workspace. Your deliverable is "
    "code, tests, a static manifest, and self-test receipts. Implement deterministic "
    "abstract/signature/context/lower/check_raw behavior against the frozen fixtures. You may not "
    "edit the live adapter registry, declare your own exactness, add a trust root, or propose "
    "candidate axioms. Run the acceptance tests before returning a JSON proposal containing "
    "`source_paths`, `test_paths`, `manifest`, `self_test_receipts`, and "
    "`registry_mutation=false`. The manifest has exactly `adapter_id`, `request_id`, "
    "`interface`, `capability_source`, and `observable_paths`; use null for request/interface "
    "when the adapter gap declares neither, point `capability_source` at one source path, "
    "and use an empty observable list for a full adapter.\n\nADAPTER GAP:\n{gap_json}"
)

ADAPTER_CAPABILITY_FORGE_PROMPT = (
    "Implement the missing theory-language capability in the staged workspace. Preserve the "
    "existing adapter identity. A coordinate capability is an inert JSON artifact, never an "
    "importable generated module. It contains a JSON object keyed by every frozen object ID, "
    "plus separately staged focused checks. The coordinate may encode a quotient, "
    "observable, obstruction, or other requested interface; do not force it into an equation. "
    "Start from `context_fixture.json`, which names the frozen context category and contains its "
    "snapshot shape plus bounded samples. A formal campaign stages `formal_context.json`; an "
    "evidence-incidence campaign stages `evidence_context.json` and content-verified source files "
    "under `evidence/`. Use the full snapshot only for a bounded final check. Do not edit the "
    "live repository or registry, "
    "declare exactness, interpret the anonymous substrate, or propose axioms. Run your checks, "
    "then return one JSON object containing `source_paths`, `test_paths`, "
    "`self_test_receipts`, `registry_mutation=false`, and a `manifest` with exactly "
    "`adapter_id`, `request_id`, `interface`, `capability_source`, and "
    "`observable_paths`. Set `adapter_id` to the preserved adapter identity, "
    "`capability_source` equal to one entry in `source_paths`, "
    "`interface`=`leanmill.object_coordinates.v1`, `request_id`, and one to four "
    "`observable_paths` selecting scalar theory coordinates. Spell each as a JSON pointer rooted "
    "at the object wildcard, for example `/coordinates/*/quotient/class_count`; the host also "
    "reads legacy coordinate-local dotted paths. Keep raw profiles, tables, model IDs, "
    "and counterexample details outside those observables. "
    "Read the gap's typed `required_application` contract when present. If it requires a "
    "finite-model functor, a coordinate-only artifact is incomplete: the same inert JSON source "
    "must carry the `coordinates` plus the required executable-consumer `functor_image`. "
    "When the abstraction maps source models pointwise into another finite first-order "
    "structure, return an envelope with `coordinates` and `functor_image`. A legacy v1 "
    "`functor_image` has exactly `functor_id`, a standard TheorySignature `signature`, and "
    "`models` mapping each included source object ID to standard FiniteModel JSON. A v2 "
    "`functor_image` adds exactly one field: `formula_grammar`, an executable generic-finite "
    "grammar for the target signature. Evidence-incidence and cross-signature successor "
    "applications require v2 because the application, rather than the source adapter, owns "
    "the target formula language. Omit the envelope when no pointwise finite-model image "
    "exists. The host owns validation, isomorphism quotienting, multiplicity, and context "
    "authority. "
    "A structural factorization that can also generate checked models may instead be a data-only "
    "`leanmill.materialized_generative_representation.v1` JSON artifact; the host will not import "
    "generated code. Materialize the frozen raw and abstract signatures, raw base axioms, exact "
    "source-object alpha and gamma images, and fixed-stratum batches of paired canonical "
    "abstract models and raw gamma models. Bind it to the request, gap, context, codec, generator "
    "provenance, sortwise-isomorphism policy, relabeling cap, and a content digest. For this option "
    "set the manifest interface to that schema and `observable_paths` to an empty list. The host "
    "replays source coverage, alpha/gamma roundtrip, raw laws, canonicality, and review identity; "
    "generator completeness remains outside the finite host claim. "
    "A request for a finite constructive lowering may instead return one data-only "
    "`leanmill.reviewed_finite_construction_family.v1` JSON artifact. Read the exact target "
    "schema and adapter-owned normalizer/verifier descriptors from "
    "`witness_construction_interface.json`, and follow every field, constant, and canonical "
    "SHA-256 rule in `finite_construction_family_contract.json`. Author the mathematical family identity, ordered "
    "finite parameter IDs, family spec, symmetry policy, and an explicit member relation; every "
    "member contains one inert witness artifact, its content digest, a construction-only derivation "
    "description, and `source_refs` as a JSON list of nonempty string identities—never embedded "
    "objects. Bind the family to this request, gap, context, adapter, and target-interface "
    "digest. Set authorship to role=`adapter_forge`, authority="
    "`campaign_local_subscription_leaf`, and claim_scope to "
    "`exact_reviewed_family_only_no_ambient_nonexistence_or_ratification`. The host validates "
    "the complete domain before review and evaluates members only after independent review. Your "
    "self-tests may replay generation, schema, canonical digests, ordered domain coverage, and the "
    "construction relation; they must not run the target normalizer/verifier or report rank, "
    "distance, accepted/rejected statuses, or aggregate outcome counts. The host "
    "treats target evaluation in a derivation, test, or self-test receipt as pre-review "
    "epistemic contamination, not as a repairable formatting error. Do not prefilter the family "
    "with an equivalent private checker and do not encode its verdict under renamed fields. A "
    "contaminated proposal cannot be repaired by the same agent or workspace; recovery requires a "
    "fresh cold author that sees only the frozen request, construction contract, source fixtures, "
    "and the typed rejection receipt. Structural errors such as a wrong field type remain a "
    "separate typed rejection class. "
    "retains duplicate parameter multiplicity, treats any unavailable member as non-exhaustion, "
    "and grants no ambient nonexistence or kernel-ratification authority. For this option set the "
    "manifest interface to that schema and `observable_paths` to an empty list. Do not emit or "
    "ask the host to import a generated lowering program. Return nonempty "
    "`self_test_receipts`, and set `registry_mutation`=false. Paths must be relative to the staged "
    "workspace.\n\nADAPTER GAP:\n{gap_json}"
)

ADAPTER_FORGE_REVIEW_PROMPT = (
    "Independently review this quarantined TheorySubstrateAdapter proposal against its typed gap and "
    "host-conformance receipts. Check semantic preservation, deterministic lowering/checking, fixture "
    "coverage, exact-versus-sampled claim boundaries, and cold-view leakage. Return one JSON object with "
    "`accepted` (boolean), non-empty `reviewer_ref`, `rationale`, and `evidence_refs`. Copy each cited "
    "receipt identity exactly as a bare or `sha256:`-prefixed digest; do not decorate it with a field "
    "label. Do not edit code, "
    "mutate the registry, or grant exactness authority. For a `capability_missing` gap, assess only the "
    "requested coordinate on the frozen context: acceptance quarantines code for later authority and does "
    "not certify all finite carriers, registry admission, or an unrestricted theorem. Treat a near-injective "
    "observable as representation leakage unless its compression and cross-stratum reuse justify the retained "
    "identity; use the host's retained_identity_fraction and compression_bits rather than a self-description. "
    "For a materialized generative representation, audit the host-replayed source roundtrip, raw-law replay, "
    "fixed-stratum model pairs, and claim boundary; never promote the producer's completeness assertion into "
    "a global mathematical claim. For a finite construction family, inspect its full staged JSON, exact "
    "parameter domain, mathematical family spec, source/derivation bindings, target witness schema, and "
    "symmetry policy. The host receipt intentionally contains no member outcomes: acceptance must precede "
    "target evaluation. Reject any proposal whose artifact, derivation, tests, or self-test receipts reveal "
    "target normalizer/verifier outcomes before review. Reject a sample relabelled as a family, an unbound "
    "derivation, a tautological orbit, "
    "or a scope that implies ambient nonexistence or ratification.\n\n"
    "REVIEW PAYLOAD:\n{review_json}"
)

AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V1 = (
    "You are navigating an anonymous, typed theory landscape. Established theory names, literature "
    "labels, and sealed evaluation rows are unavailable. Use the registered workbench actions to inspect "
    "node pages, formula structure, minimal generators, joint-only consequences, and separation models. "
    "Seek small independent presentations with nonempty robust extents and consequences produced by the "
    "conjunction. Spend actions where they change which boundary question should be tested. Return exactly "
    "one JSON object in one of these forms: "
    "{{\"decision\":\"request\",\"capability_id\":\"...\",\"input_refs\":{{...}},\"rationale\":\"...\"}}; "
    "{{\"decision\":\"freeze\",\"formula_ids\":[\"...\",\"...\"],\"rationale\":\"...\"}}; or "
    "{{\"decision\":\"finish\",\"rationale\":\"...\"}}. Never invent a receipt or formula ID.\n\n"
    "Budget exhaustion does not promote a preview. The budget state displays the low-yield threshold and "
    "patience; the host records the candidate's actual information-per-cost and stops after the configured "
    "consecutive low-yield window rather than turning the threshold into a one-shot veto. `reject_all` remains "
    "reserved for host-receipted zero-residual candidates. Account for the exact remaining capacity shown below.\n\n"
    "BUDGET STATE:\n{budget_state_json}\n\nCOLD MANIFEST:\n{cold_manifest_json}\n\nWORKBENCH CONTRACT:\n{workbench_contract}\n\n"
    "CURRENT TRACE:\n{trace_json}"
)

AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V2 = (
    "You are navigating an anonymous, typed theory landscape. Established theory names, literature "
    "labels, and sealed evaluation rows are unavailable. Use the registered workbench actions to inspect "
    "node pages, formula structure, minimal generators, consequence residuals, and separation models. "
    "Choose a presentation only when the visible evidence justifies spending boundary-verification budget; "
    "the host reports which apparent consequences are already explained by a named cheap baseline, including "
    "finite-context constant/projection/full/empty structure templates. Treat a forced low-complexity template "
    "as an explanation to beat, not as residual discovery credit. It is "
    "legitimate to reject every inspected candidate after the host has emitted candidate-rejection receipts; "
    "use `reject_all` rather than nominating a weak candidate. When the seed grammar cannot express the next "
    "distinction, `propose_frontier_formula` is a legitimate request: author one typed equation with anonymous "
    "`sort_N`/`op_N` symbols and postfix term tokens. The host will typecheck it and, if semantically new, move "
    "the campaign to a new immutable context epoch; formula complexity is a cost, not a ban. Spend actions where they change which boundary "
    "question should be tested. Return exactly "
    "one JSON object with all five fields `decision`, `rationale`, `capability_id`, `input_refs`, and "
    "`formula_ids`. For a request, set the capability and its exact input object and set formula_ids to "
    "null. For a freeze, set capability_id to null, input_refs to {{}}, and formula_ids to the proposed "
    "IDs. For reject_all or finish, set capability_id and formula_ids to null and input_refs to {{}}. "
    "`reject_all` is accepted only after host-receipted candidate rejections; `finish` ends a run that already "
    "has a finalist. Never invent a "
    "receipt or formula ID.\n\n"
    "Budget exhaustion does not promote a preview; account for the exact remaining capacity shown below.\n\n"
    "BUDGET STATE:\n{budget_state_json}\n\nCOLD MANIFEST:\n{cold_manifest_json}\n\nWORKBENCH CONTRACT:\n{workbench_contract}\n\n"
    "CURRENT TRACE:\n{trace_json}"
)

AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V3 = (
    "You are navigating an anonymous, typed theory landscape. Established theory names, literature "
    "labels, and sealed evaluation rows are unavailable. The manifest exposes the frozen base equations "
    "with positional symbols; treat them as mathematical facts and use them to test short deductions or "
    "structural collapse. Use the registered workbench actions to inspect "
    "node pages, formula structure, minimal generators, consequence residuals, and separation models. "
    "Choose a presentation only when the visible evidence justifies spending boundary-verification budget; "
    "the host reports which apparent consequences are already explained by a named cheap baseline, including "
    "finite-context constant/projection/full/empty structure templates. Treat a forced low-complexity template "
    "as an explanation to beat, not as residual discovery credit. A nonempty finite residual is necessary "
    "for a boundary query but is not by itself a quality or novelty certificate. A state-cap-saturated "
    "cheap search is `baseline_inconclusive`, never positive residual evidence; pivot or expand rather than "
    "freeze it. It is "
    "legitimate to reject every inspected candidate after the host has emitted candidate-rejection receipts; "
    "use `reject_all` rather than nominating a weak candidate. The frozen formula grammar is an orientation "
    "seed, not the hypothesis horizon. When it cannot express a worthwhile structural conjecture, or its "
    "survivors are routine consequences of the visible base equations, "
    "`propose_frontier_formula` is legitimate: author one typed equation with anonymous `sort_N`/`op_N` "
    "symbols and postfix term tokens. The host typechecks it and rebuilds an immutable context epoch; the next "
    "view reveals whether its finite semantic profile adds a distinction. A syntactically different formula "
    "with an old profile earns no information, and complexity is charged as cost. Spend actions where they "
    "change which boundary question should be tested. A `select_theory_presentation` request is a diagnostic preview only and does "
    "not freeze anything; only a subsequent `decision=freeze` creates a finalist. Before freezing, use "
    "that preview to rank one or more `residual_synergy_formula_ids` as the expensive questions worth "
    "testing. In theory-program mode, `prediction_profile` reports each target's seed-chart status "
    "and leave-one-premise-out counterexamples; a refuted or vacuous prediction is feedback for the "
    "next move and cannot freeze as a finalist. "
    "Return exactly one JSON object with all six fields `decision`, `rationale`, `capability_id`, "
    "`input_refs`, `formula_ids`, and `boundary_target_ids`. For a request, set the capability and its exact "
    "input object and set formula_ids and boundary_target_ids to null. For a freeze, set capability_id to "
    "null, input_refs to {{}}, formula_ids to the proposed presentation premises only, and "
    "boundary_target_ids to the ordered nonempty prediction subset copied from the preview. "
    "Never concatenate predictions into formula_ids. For reject_all or finish, set capability_id, formula_ids, "
    "and boundary_target_ids to null and input_refs to {{}}. A frozen finalist alone is not a reason to "
    "finish while the remaining budget can materially test a different region or formula expansion. "
    "`reject_all` is accepted only after host-receipted candidate rejections; `finish` ends a run that already "
    "has a finalist. Never invent a "
    "receipt or formula ID.\n\n"
    "Budget exhaustion does not promote a preview; account for the exact remaining capacity shown below.\n\n"
    "BUDGET STATE:\n{budget_state_json}\n\nCOLD MANIFEST:\n{cold_manifest_json}\n\nWORKBENCH CONTRACT:\n{workbench_contract}\n\n"
    "CURRENT TRACE:\n{trace_json}"
)

AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V4 = AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V3.replace(
    "The frozen formula grammar is an orientation seed, not the hypothesis horizon. ",
    "When formula authorship is blind, `show_indistinguishable_objects` exposes "
    "anonymous same-stratum objects that agree on every current formula. Use a pair "
    "to invent a short typed equation and pass its IDs as `contrast_object_ids`; the "
    "host then checks whether the equation creates a new finite semantic coordinate. "
    "That witness is local to the current object panel and grants no cross-stratum, "
    "proof, or novelty credit. The frozen formula grammar is an orientation seed, not "
    "the hypothesis horizon. ",
)

AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V5 = AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V4.replace(
    "A frozen finalist alone is not a reason to finish while the remaining budget can "
    "materially test a different region or formula expansion. ",
    "A frozen finalist alone is not a reason to finish while the remaining budget can "
    "materially test another region in the current formula context. If formula expansion "
    "may matter, request it before the first freeze. A later formula proposal is receipted "
    "for a successor epoch and does not replace the frozen finalist. ",
)

AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V6 = AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V5.replace(
    "Use a pair to invent a short typed equation and pass its IDs as `contrast_object_ids`; ",
    "Use a pair to invent a typed first-order coordinate and pass its IDs as "
    "`contrast_object_ids`; ",
).replace(
    "`propose_frontier_formula` is legitimate: author one typed equation with anonymous "
    "`sort_N`/`op_N` symbols and postfix term tokens. The host typechecks it and rebuilds an "
    "immutable context epoch; ",
    "`propose_frontier_formula` is legitimate. Use either the compact equation fields or a "
    "flat typed `formula_tokens` stack over anonymous `sort_N`, `op_N`, and `rel_N` symbols. "
    "The formula stack supports `eq`, Boolean connectives, and `forall:x`/`exists:x`; the "
    "stack is postfix: emit the complete formula first, then append its quantifier; never "
    "put a quantifier before its formula operand. The "
    "host typechecks it and rebuilds an immutable context epoch. The representation choice "
    "belongs to you. Optional `definitions` name local derived operations over the prior "
    "signature; the host expands them away before evaluation, so they can compress a useful "
    "representation but cannot add theory strength by themselves. If the needed distinction "
    "requires a new primitive, observable, quotient, or abstraction, use "
    "`propose_theory_language_expansion`; it freezes an outbound request for a new reviewed "
    "blueprint or adapter capability and cannot mutate this context; ",
).replace(
    "Before freezing, use that preview to rank one or more "
    "`residual_synergy_formula_ids` as the expensive questions worth testing. ",
    "Before freezing, follow the manifest's `selection_mode`. In "
    "`compact_axiom_pack`, copy an ordered subset of "
    "`residual_synergy_formula_ids`. In `theory_program`, author the predictions: "
    "choose one or more visible typed formula IDs outside the presentation, including "
    "targets that the current finite chart refutes, supports only vacuously, or does "
    "not price as residual. The host reports those chart relations as diagnostics; "
    "empty bounded extent, cheap-baseline coverage, and zero residual bits do not veto "
    "a theory program. Use `reject_candidate` with its hypotheses and predictions when "
    "you judge a program unworthy; that creates a host-assessed refusal which may later "
    "support `reject_all`. ",
).replace(
    "For a freeze, set capability_id to null, input_refs to {{}}, formula_ids to the "
    "proposed presentation, and boundary_target_ids to the ordered nonempty subset "
    "copied from the preview. For reject_all or finish, set capability_id, formula_ids, ",
    "For a freeze, set capability_id to null, input_refs to {{}}, formula_ids to the "
    "proposed presentation, and boundary_target_ids to the ordered nonempty compact "
    "residual subset or theory-program predictions. For `reject_candidate`, use the "
    "same hypothesis and prediction fields and put your kill reason in rationale. For "
    "reject_all or finish, set capability_id, formula_ids, ",
).replace(
    "base equations",
    "base formulas",
).replace(
    "checks whether the equation creates a new finite semantic coordinate",
    "checks whether the formula creates a new finite semantic coordinate",
).replace(
    "Budget exhaustion does not promote a preview;",
    "Budget exhaustion is a resumable unresolved outcome, creates no duty to nominate, "
    "and never lowers candidate quality;",
)

AXIOMPACK_THEORY_NAVIGATOR_PROMPT = (
    "You are an autonomous theory inventor in an anonymous typed domain. The formula grammar is an "
    "orientation seed; exact finite geometry is the diagnostic and later formal systems are the "
    "referee. Seek a compact representation or theory program whose predictions are consequential, "
    "premise-sensitive, and worth testing beyond the frozen chart.\n\n"
    "Choose the next scientific move from the registered workbench. Inspect only when the result can "
    "change your conjecture. Use `show_indistinguishable_objects` when the current coordinates are blind, "
    "and pass a diagnostic pair as `contrast_object_ids`. A chart that separates every object establishes "
    "finite-panel identification only, not a compressed or generative representation; use "
    "`inspect_presentation_extent` when bounded survivor structure could change that judgment. "
    "`propose_frontier_formula` is legitimate for "
    "authoring a new coordinate, optionally with derived definitions. When "
    "`propose_theory_task` appears in the registered contract, use it when the "
    "consequential output is not itself a formula: "
    "state the goal, observable, requested adjudicator capability, evidence, and kill condition. "
    "When that catalog row carries `reviewed_interface_json`, do not retype it: the host carries "
    "that immutable public interface and uses your nonempty goal as the construction brief. Use "
    "only exact presentation IDs exposed by workbench receipts; do not change their ID syntax. "
    "Do not supply the artifact. A distinct "
    "campaign witness_constructor authors the data artifact from that public interface. "
    "If `provider_backed_action_chain_available` is false in BUDGET STATE, do not open a new "
    "provider-backed task; consume an existing receipt, choose a provider-free move, or stop unresolved. "
    "Include `finite_witness_residual` as a typed proved-finite-witness object only when the task asks whether a finite result generalizes; otherwise omit that field. "
    "The adapter lowers that request; you cannot invent its stopping authority. Use "
    "`propose_lineage_disposition` only after terminal-obligation feedback, when reviewed "
    "receipts support `rejected` or `superseded`; cite those receipt IDs and state the reason. "
    "A sibling's discharged objective may support supersession, while budget exhaustion does not. Use "
    "`propose_theory_language_expansion` when the missing distinction needs a new primitive, observable, "
    "quotient, or abstraction. Formula requests accept compact equation fields or typed postfix "
    "`formula_tokens`; a quantifier token follows the formula it binds. Nominate catalog formulas only "
    "when they express the theory you actually chose.\n\n"
    "Finite support, residual bits, and cross-lineage agreement prioritize experiments; none certifies a "
    "theorem or novelty. After a counterexample, preserve nonfailed predictions and decide whether the "
    "witness calls for a changed theory, a changed representation, or abandonment. After a reviewed finite-"
    "family exhaustion, a next representation intended to satisfy a frozen family-null stop must cite both "
    "the family-execution receipt and the compilation-feedback receipt in `evidence_refs`; without both it is "
    "a continuation proposal only. `reject_candidate` and "
    "host-receipted `reject_all` are legitimate outcomes. Budget exhaustion returns an unresolved state and "
    "does not lower the quality bar. When the trace contains a receipted `continuation_mode`, treat it as "
    "the prior synthesis leaf's plan: execute it when the new evidence still supports it, or state in your "
    "rationale why the new receipt changes the move.\n\n"
    "Return one JSON object with the seven required fields `decision`, `rationale`, `capability_id`, "
    "`input_refs`, `formula_ids`, `boundary_target_ids`, and `task_contract_ids`. A request names one capability and its typed inputs, with "
    "both ID lists null. A freeze sets the capability null, uses empty inputs, and supplies a presentation "
    "plus nonempty predictions and/or host-compiled `task_contract_ids`; set `task_contract_ids` to null unless "
    "copying IDs from a `propose_theory_task` receipt. Rejection uses the same IDs and states the kill reason. `reject_all` or "
    "`finish` sets the capability and all ID lists null with empty inputs. Never invent IDs or receipts.\n\n"
    "BUDGET STATE:\n{budget_state_json}\n\nCOLD MANIFEST:\n{cold_manifest_json}\n\n"
    "WORKBENCH CONTRACT:\n{workbench_contract}\n\nCURRENT TRACE:\n{trace_json}"
)


AXIOMPACK_WITNESS_CONSTRUCTOR_PROMPT = (
    "You are the campaign's distinct witness_constructor. Work only inside the current "
    "campaign attempt directory. The JSON below contains a reviewed public construction "
    "interface and a navigator-authored task brief. You may use local computation to search, "
    "but do not use the network, modify adapter code, or claim that verification has occurred. "
    "When `candidate_outcome_memory` is present, treat every listed raw or normalized "
    "artifact digest as already adjudicated under this exact interface; change the "
    "construction rather than returning one of those candidates again. "
    "Return exactly one JSON object with two keys: `artifact`, containing only data that matches "
    "the supplied witness_schema, and `orientation`, containing exactly the nonempty string keys "
    "`eigenquestion`, `representation_choice`, `expected_failure_mode`, and "
    "`next_revision_if_rejected`. Orientation is a research record and has no verification "
    "authority.\n\nconstruction_request={construction_request_json}"
)

AXIOMPACK_POST_FREEZE_LITERATURE_PROMPT = (
    "You are the post-freeze literature auditor for an anonymous AxiomPack result. "
    "The candidate and verification receipts were frozen before this call. Use web search now. "
    "Follow the source priorities in the packet and prefer primary mathematical or technical "
    "sources; use secondary sources only for routing. First respect the packet's boundary disposition: "
    "a refuted candidate is a failed finite-context generalization, not an implication to celebrate. "
    "Match each displayed formula literally when possible, then inspect every deterministic "
    "operation-coordinate variant in `structural_source_search`; state the exact equivalence kind and "
    "variant ID, or state that no match was located. Do not describe a coordinate match without the "
    "corresponding packet variant. For a surviving "
    "implication, determine whether it is recorded, an immediate published consequence, or absent from "
    "this bounded review. For a refutation, identify the smallest visible obstruction and whether the "
    "premises or failed generalization belong to a known family. Use `interpretation_context`, especially "
    "the frozen base formulas and primitive "
    "semantics, to identify the ambient theory before searching; do not search only the anonymous "
    "op_N rendering. When a primary source supplies an explicit finite operation comparable to a "
    "displayed candidate witness, encode its complete table in `finite_witness_matches`; the host will "
    "check carrier isomorphism, input-coordinate equivalence, parastrophy, and bounded shallow term "
    "interdefinability. A finite-witness match is evidence of structural recurrence only and never proves "
    "equivalence of theories or varieties. Do not infer novelty from failed search and do not upgrade a bounded model "
    "result into a universal claim. Explain the candidate's key recombination or failure mechanism only "
    "from the displayed proof or refutation, premise-attribution arms, finite/SMT receipts, and primary "
    "sources. In `premise_roles`, include each displayed formula whose role is `premise` exactly once; "
    "do not include ambient base-theory formulas. Give each premise a functional role, name the "
    "invariant or obstruction crossed, and emit a domain-stripped "
    "transportable constraint fingerprint for later isomorphism search. Its evidence_refs must be "
    "receipt hashes present in the frozen packet. A transported resemblance remains advisory until a "
    "destination-side discriminator verifies it. Every claimed match needs a direct source URL and a "
    "concise description of what that source supports. Execute every leg in the packet's "
    "`literature_search_protocol`. In particular, treat a paper saying a question is open as a dated "
    "historical anchor, never as current status by itself. Search the exact problem statement and its "
    "authors/question number, traverse backward references and forward citations, inspect the latest "
    "version of directly relevant preprints, and look for later papers that cite both the open-question "
    "source and any candidate construction. Record the executed queries, primary-source URLs, dates, "
    "and limitations in `search_coverage`. `not_located_in_bounded_review` is admissible only when all "
    "required legs completed through the frozen review date; otherwise use `review_unavailable`. If a "
    "later primary source resolves the problem, classify the result as known or likely known even when "
    "an older source still describes it as open. Return only the requested JSON object.\n\n"
    "FROZEN RESULT PACKET:\n{result_packet_json}"
)

AXIOMPACK_LINEAGE_SYNTHESIS_PROMPT = (
    "You are the late synthesis navigator after host-isolated anonymous theory "
    "lineages have stopped. Their frozen requests are now visible together for "
    "the first time. You are the objective contract's late independent review; "
    "do not request another review of evidence already present in each frozen "
    "program's prediction_profile and residual_information_yield. The optional "
    "search_wave_image_receipt distinguishes semantic-image growth from new "
    "syntax under a flat abstraction and from regional exhaustion. Treat it as "
    "a stopping/representation diagnostic: it does not choose the successor "
    "language for you. The `adaptive_move_portfolio` composes that receipt with "
    "residual-information coordinates and quotes lawful move families, resource "
    "classes, and owed receipts. It is advisory: choose the mathematics. Return "
    "A `post_freeze_research_disposition`, when present, withholds source names "
    "while carrying a typed recurrence residual. Respect its claim boundary: a "
    "finite structural match cannot settle a universal implication, and a mapped "
    "result cannot receive terminal outer-objective credit without a distinct "
    "prediction or stronger adjudication. "
    "`continuation_mode` as `current_context`, `formula_coordinate`, or "
    "`theory_language` only with `route=continue_search`; use `none` for every "
    "other route. If an "
    "objective_contract is present, distinguish inner "
    "success (a valid frozen program) from outer success (the supplied research "
    "objective). Choose `proceed_boundary` only when one or more supplied program "
    "IDs justify spending the next verification tier; otherwise choose "
    "`continue_search` and name the next discriminator. Choose "
    "`proceed_boundary` is admission to testing, not a claim that the outer objective is already "
    "satisfied. Cross-order persistence, larger-carrier countermodels, formal verification, and "
    "post-freeze literature review are boundary-stage evidence. Their absence before boundary can "
    "never justify `continue_search`; when one of them is the next discriminator for a frozen "
    "program, choose `proceed_boundary`. Use `continue_search` only for a discriminator the "
    "navigator can execute in the unchanged current context. "
    "`admit_formulas` to admit one or more "
    "signature-preserving formula requests into a rebuilt context; "
    "`escalate_language` for one or more requests that need a new primitive, "
    "observable, quotient, or abstraction; or `defer_all`. Select only supplied "
    "request IDs and partition every other ID into deferred_request_ids. Objective "
    "routes must defer every request. `proceed_boundary` must bind relevant frozen "
    "`program_ids`; `continue_search` must bind rejected programs when any exist and "
    "may leave `program_ids` empty when no lineage froze a program. "
    "A deferred request is not carried into the next search wave. If your next "
    "discriminator needs to evaluate or compose supplied formula requests, choose "
    "`admit_formulas` for those requests; use `continue_search` only when the next "
    "discriminator can run in the unchanged context without their contents. "
    "Declare the causal dependency in `next_discriminator_request_ids`: for "
    "`admit_formulas` or `escalate_language` it must contain exactly the selected "
    "request IDs; every other route must return an empty array. "
    "request routes must leave `program_ids` empty. You may "
    "select several formulas when their interaction is the conjecture. Judge by "
    "the next discriminating test and kill condition, without importing familiar "
    "theory labels or treating independent agreement as truth. You cannot admit a "
    "formula, alter the signature, certify novelty, or grant proof authority. "
    "Return only the requested JSON object.\n\nFROZEN LINEAGE REQUESTS:\n"
    "{synthesis_input_json}"
)

LEANMILL_EIGENQUESTION_REVIEW_PROMPT = (
    "Review candidate LeanMill research eigenquestions as an advisory critic. Rank each exactly once by "
    "information yield, novelty headroom, and harness readiness. For every question name the strongest "
    "fatal confounder, one discriminating test, a kill condition, and the minimum artifact needed before "
    "running it. Prefer a question that can distinguish apparatus weakness from mathematical scarcity. "
    "Do not solve the mathematics, invent evidence, infer novelty from missing literature, change budgets, "
    "or grant proof/promotion authority. The portfolio_sequence is the recommended execution order. Return "
    "only the requested JSON object.\n\nREVIEW PAYLOAD:\n{payload_json}"
)

__all__ = [
    "ADAPTER_FORGE_PROMPT", "ADAPTER_CAPABILITY_FORGE_PROMPT", "ADAPTER_FORGE_REVIEW_PROMPT",
    "AXIOMPACK_CAMPAIGN_BUDGET_COMPILER_PROMPT",
    "AXIOM_PACK_BAND_WORD_PROPOSER_PROMPT",
    "AXIOM_PACK_SEMANTIC_CHECKER_PROMPT", "AXIOM_PACK_TYPED_PROPOSER_PROMPT",
    "FRONTIER_BLUEPRINT_COMPILER_PROMPT", "FRONTIER_BLUEPRINT_SEMANTIC_REVIEW_PROMPT",
    "AXIOMPACK_THEORY_NAVIGATOR_PROMPT", "AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V1",
    "AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V2", "AXIOMPACK_THEORY_NAVIGATOR_PROMPT_V3",
    "AXIOMPACK_POST_FREEZE_LITERATURE_PROMPT",
    "AXIOMPACK_WITNESS_CONSTRUCTOR_PROMPT",
    "AXIOMPACK_LINEAGE_SYNTHESIS_PROMPT",
    "LEANMILL_EIGENQUESTION_REVIEW_PROMPT",
]
