import Mathlib.Tactic

/-!
# Infinite target-critical support below ordinary rate two

The July minimax charges ordinary target derivation excess, while its Rees
boundary uses target weights `(4,6)`.  These filtrations are not comparable
at rate two in the direction needed by the finite-critical schedule adapter.

For every `b ≥ 2`, put `Q^b` in parameter row `3b-5`.  It lies in the
contact-zero ideal `(Q^2)`, has exact critical Rees weight, and has ordinary
derivation-excess ratio at most one.  Thus an ordinary target tail bound
strictly below two cannot, by itself, make the target critical face finite.
-/

namespace AxiomPackJacobianTargetCriticalRateGap

/-- Parameter row occupied by the critical monomial `Q^b`. -/
def targetRow (b : ℕ) : ℕ := 3 * b - 5

/-- `(4,6)` Rees weight of `Q^b`. -/
def targetReesWeight (b : ℕ) : ℕ := 6 * b

/-- Ordinary derivation excess of the Hamiltonian `Q^b`. -/
def targetDerivationExcess (b : ℕ) : ℕ := b - 1

/-- The proposed monomial occurs on a valid positive parameter row. -/
theorem targetRow_positive (b : ℕ) (hb : 2 ≤ b) :
    0 < targetRow b := by
  simp only [targetRow]
  omega

/-- The row is exactly on the July target-critical Rees face. -/
theorem targetReesWeight_critical (b : ℕ) (hb : 2 ≤ b) :
    targetReesWeight b = 2 * (targetRow b + 5) := by
  simp only [targetReesWeight, targetRow]
  omega

/-- `Q^b` belongs to the contact-zero ideal generated by `Q^2`. -/
theorem qPow_contactZero {M : Type*} [CommMonoid M]
    (q : M) (b : ℕ) (hb : 2 ≤ b) :
    q ^ 2 ∣ q ^ b := by
  exact pow_dvd_pow q hb

/-- The ordinary target derivation cost is bounded by the parameter row.
The resulting rate is at most one, hence strictly below two. -/
theorem targetDerivationExcess_le_row (b : ℕ) (hb : 2 ≤ b) :
    targetDerivationExcess b ≤ targetRow b := by
  simp only [targetDerivationExcess, targetRow]
  omega

/-- Rational form of the strict-below-two rate bound. -/
theorem target_rate_lt_two (b : ℕ) (hb : 2 ≤ b) :
    (targetDerivationExcess b : ℚ) / targetRow b < 2 := by
  have hrow : 0 < (targetRow b : ℚ) := by
    exact_mod_cast targetRow_positive b hb
  rw [div_lt_iff₀ hrow]
  have hcost : targetDerivationExcess b ≤ targetRow b :=
    targetDerivationExcess_le_row b hb
  have hcostQ :
      (targetDerivationExcess b : ℚ) ≤ targetRow b := by
    exact_mod_cast hcost
  linarith

/-- The critical rows are unbounded, so the construction supplies infinitely
many distinct target-critical occurrences. -/
theorem targetRow_strictMono_after_two
    (a b : ℕ) (ha : 2 ≤ a) (hab : a < b) :
    targetRow a < targetRow b := by
  simp only [targetRow]
  omega

/-- Aggregated arithmetic certificate for the filtration mismatch. -/
theorem target_critical_rate_gap_terminal_certificate :
    (∀ b : ℕ, 2 ≤ b →
      targetReesWeight b = 2 * (targetRow b + 5)) ∧
    (∀ {M : Type*} [CommMonoid M] (q : M) (b : ℕ), 2 ≤ b →
      q ^ 2 ∣ q ^ b) ∧
    (∀ b : ℕ, 2 ≤ b →
      (targetDerivationExcess b : ℚ) / targetRow b < 2) ∧
    (∀ a b : ℕ, 2 ≤ a → a < b → targetRow a < targetRow b) := by
  exact ⟨targetReesWeight_critical, qPow_contactZero,
    target_rate_lt_two, targetRow_strictMono_after_two⟩

end AxiomPackJacobianTargetCriticalRateGap
