import ZtareProofs.AxiomPackJacobianMovingPoissonSectionArithmetic

/-!
Combinatorial carrier for the sharp `3/7` Lie cone generated by the minimum
cusp section.

This module reuses the exponent-pair and monomial-bracket model from
`AxiomPackJacobianMovingPoissonSectionArithmetic`.  It proves supportwise
closure of

`q ≥ 1 ∧ p ≤ 2*q`,

the cross-multiplied degree bound `7*degree ≤ 3*weight`, and an explicit
two-bracket recurrence reaching the sharp ray `(2*b, b)` for every
`b ≥ 1`.

The identification of these exponent pairs with the minimum polynomial
section is a pencil argument.  Moving-family integration, coefficientwise
polynomiality, the paired source logarithm, and translation from cusp weight
to parameter/BCH order also remain pencil questions.
-/

namespace AxiomPackJacobianMinimumSectionLieConeArithmetic

open AxiomPackJacobianMovingPoissonSectionArithmetic

/-- The support cone `q ≥ 1`, `p ≤ 2*q`. -/
def InMinimumLieCone (e : ExponentPair) : Prop :=
  1 ≤ e.q ∧ e.p ≤ 2 * e.q

theorem minimum_generator_in_cone
    (p q : ℕ) (hp : p ≤ 2) (hq : 1 ≤ q) :
    InMinimumLieCone ⟨p, q⟩ := by
  constructor
  · exact hq
  · simp only
    omega

theorem nonzero_bracket_preserves_cone
    (e f : ExponentPair)
    (he : InMinimumLieCone e)
    (hf : InMinimumLieCone f)
    (hn : BracketNonzero e f) :
    InMinimumLieCone (bracketExponent e f) := by
  rcases he with ⟨heq, hep⟩
  rcases hf with ⟨hfq, hfp⟩
  have hstrict : e.p < 2 * e.q ∨ f.p < 2 * f.q := by
    by_cases hse : e.p < 2 * e.q
    · exact Or.inl hse
    · by_cases hsf : f.p < 2 * f.q
      · exact Or.inr hsf
      · have heq' : e.p = 2 * e.q :=
          Nat.le_antisymm hep (Nat.le_of_not_gt hse)
        have hfeq' : f.p = 2 * f.q :=
          Nat.le_antisymm hfp (Nat.le_of_not_gt hsf)
        exfalso
        apply hn
        rw [heq', hfeq']
        ac_rfl
  constructor
  · change 1 ≤ e.q + f.q - 1
    omega
  · change e.p + f.p - 1 ≤ 2 * (e.q + f.q - 1)
    rcases hstrict with hstrict | hstrict <;> omega

theorem cone_degree_weight_bound
    (e : ExponentPair) (he : InMinimumLieCone e) :
    7 * ordinaryDegree e ≤ 3 * weight e := by
  rcases he with ⟨heq, hep⟩
  change 7 * (e.p + e.q) ≤ 3 * (2 * e.p + 3 * e.q)
  omega

/-- Sharp-ray monomial `S_b = (2*b, b)`. -/
def S (b : ℕ) : ExponentPair :=
  ⟨2 * b, b⟩

/-- Fixed minimum-section generator `G = (2, 2)`. -/
def G : ExponentPair :=
  ⟨2, 2⟩

/-- Intermediate `T_{b+1} = (2*b+1, b+1)`. -/
def Tnext (b : ℕ) : ExponentPair :=
  ⟨2 * b + 1, b + 1⟩

theorem S_in_cone (b : ℕ) (hb : 1 ≤ b) :
    InMinimumLieCone (S b) := by
  simp [InMinimumLieCone, S, hb]

theorem G_in_cone :
    InMinimumLieCone G := by
  norm_num [InMinimumLieCone, G]

theorem Tnext_in_cone (b : ℕ) :
    InMinimumLieCone (Tnext b) := by
  simp [InMinimumLieCone, Tnext]

theorem S_weight (b : ℕ) :
    weight (S b) = 7 * b := by
  simp [weight, S]
  omega

theorem S_degree (b : ℕ) :
    ordinaryDegree (S b) = 3 * b := by
  simp [ordinaryDegree, S]
  omega

theorem S_sharp (b : ℕ) :
    7 * ordinaryDegree (S b) = 3 * weight (S b) := by
  rw [S_degree, S_weight]
  omega

theorem S_G_bracket_numerator (b : ℕ) :
    bracketNumerator (S b) G = (2 * b : ℕ) := by
  simp [bracketNumerator, S, G]
  ring

theorem S_G_bracket_scalar (b : ℕ) :
    bracketScalar (S b) G = (b : ℚ) / 3 := by
  simp [bracketScalar, S_G_bracket_numerator]
  ring

theorem S_G_bracket_nonzero (b : ℕ) (hb : 1 ≤ b) :
    BracketNonzero (S b) G := by
  rw [bracketNonzero_iff_numerator_ne_zero,
    S_G_bracket_numerator]
  exact_mod_cast (by omega : (2 * b : ℕ) ≠ 0)

theorem S_G_bracket_exponent (b : ℕ) :
    bracketExponent (S b) G = Tnext b := by
  ext <;> simp [bracketExponent, S, G, Tnext]

theorem S_one_Tnext_bracket_numerator (b : ℕ) :
    bracketNumerator (S 1) (Tnext b) = 1 := by
  simp [bracketNumerator, S, Tnext]
  ring

theorem S_one_Tnext_bracket_scalar (b : ℕ) :
    bracketScalar (S 1) (Tnext b) = (1 : ℚ) / 6 := by
  simp [bracketScalar, S_one_Tnext_bracket_numerator]

theorem S_one_Tnext_bracket_nonzero (b : ℕ) :
    BracketNonzero (S 1) (Tnext b) := by
  rw [bracketNonzero_iff_numerator_ne_zero,
    S_one_Tnext_bracket_numerator]
  norm_num

theorem S_one_Tnext_bracket_exponent (b : ℕ) :
    bracketExponent (S 1) (Tnext b) = S (b + 1) := by
  apply ExponentPair.ext
  · simp [bracketExponent, S, Tnext]
    omega
  · simp [bracketExponent, S, Tnext]

/-- Bracket words generated from the two minimum-section seeds `S 1` and
`G`. -/
inductive Reachable : ExponentPair → Prop
  | seedS : Reachable (S 1)
  | seedG : Reachable G
  | bracket {e f : ExponentPair} :
      Reachable e →
      Reachable f →
      BracketNonzero e f →
      Reachable (bracketExponent e f)

theorem reachable_in_cone
    {e : ExponentPair} (h : Reachable e) :
    InMinimumLieCone e := by
  induction h with
  | seedS =>
      exact S_in_cone 1 (by norm_num)
  | seedG =>
      exact G_in_cone
  | bracket he hf hn ihe ihf =>
      exact nonzero_bracket_preserves_cone _ _ ihe ihf hn

theorem Tnext_reachable
    (b : ℕ) (hb : 1 ≤ b)
    (hS : Reachable (S b)) :
    Reachable (Tnext b) := by
  rw [← S_G_bracket_exponent b]
  exact Reachable.bracket hS Reachable.seedG
    (S_G_bracket_nonzero b hb)

theorem S_succ_reachable
    (b : ℕ) (hb : 1 ≤ b)
    (hS : Reachable (S b)) :
    Reachable (S (b + 1)) := by
  rw [← S_one_Tnext_bracket_exponent b]
  exact Reachable.bracket Reachable.seedS
    (Tnext_reachable b hb hS)
    (S_one_Tnext_bracket_nonzero b)

theorem S_reachable (b : ℕ) (hb : 1 ≤ b) :
    Reachable (S b) := by
  induction b, hb using Nat.le_induction with
  | base =>
      exact Reachable.seedS
  | succ b hb ih =>
      exact S_succ_reachable b hb ih

theorem reachable_degree_weight_bound
    {e : ExponentPair} (h : Reachable e) :
    7 * ordinaryDegree e ≤ 3 * weight e :=
  cone_degree_weight_bound e (reachable_in_cone h)

/-- Terminal arithmetic certificate for the sharp `3/7` minimum-section
Lie cone. -/
theorem minimum_section_lie_cone_arithmetic_terminal_certificate :
    (∀ (e f : ExponentPair),
      InMinimumLieCone e →
      InMinimumLieCone f →
      BracketNonzero e f →
        InMinimumLieCone (bracketExponent e f)) ∧
    (∀ e : ExponentPair,
      InMinimumLieCone e →
        7 * ordinaryDegree e ≤ 3 * weight e) ∧
    (∀ b : ℕ, 1 ≤ b →
      bracketNumerator (S b) G = (2 * b : ℕ) ∧
      bracketExponent (S b) G = Tnext b ∧
      bracketNumerator (S 1) (Tnext b) = 1 ∧
      bracketExponent (S 1) (Tnext b) = S (b + 1)) ∧
    (∀ b : ℕ, 1 ≤ b →
      Reachable (S b) ∧
      weight (S b) = 7 * b ∧
      ordinaryDegree (S b) = 3 * b) := by
  refine ⟨nonzero_bracket_preserves_cone,
    cone_degree_weight_bound, ?_, ?_⟩
  · intro b hb
    exact ⟨S_G_bracket_numerator b, S_G_bracket_exponent b,
      S_one_Tnext_bracket_numerator b,
      S_one_Tnext_bracket_exponent b⟩
  · intro b hb
    exact ⟨S_reachable b hb, S_weight b, S_degree b⟩

end AxiomPackJacobianMinimumSectionLieConeArithmetic
