import Mathlib.Tactic

/-!
Arithmetic carrier for the corrected seed-cusp prefix quotient.

The source pencil proves the polynomial statements:

* the liftable Hamiltonians restrict to `ℚ ⊕ r^5 ℚ[r]`;
* their normal image is `r^3 ℚ[r]`;
* the kernel is `ℚ + C · ℚ[P,Q]`.

Those claims require polynomial rings, restriction maps, ideals, and the
paired source/target action.  They are deliberately not reconstructed here.
This file carries only the finite arithmetic endpoints used by that proof:
the strict low-jet obstruction, its controls, the stabilizer semigroup gap,
and the optimal `2/3` exponent decomposition.
-/

namespace AxiomPackJacobianSeedPrefixQuotientArithmetic

def strictOmega (a₂ b₃ : ℚ) : ℚ := 2 * a₂ + 3 * b₃

def normalFormOmega (a₂ n₃ : ℚ) : ℚ := 5 * a₂ + 3 * n₃

/-- With `n₃ = b₃ - a₂`, the normal-coordinate obstruction is the direct
coefficient obstruction `2 a₂ + 3 b₃`. -/
theorem omega_coordinate_identity (a₂ b₃ : ℚ) :
    normalFormOmega a₂ (b₃ - a₂) = strictOmega a₂ b₃ := by
  simp [normalFormOmega, strictOmega]
  ring

/-- The lowest liftable target generator `P Q` contributes the paired
coefficient vector `(-3,5)`, which lies in the strict kernel. -/
theorem pq_pair_omega_zero :
    normalFormOmega (-3) 5 = 0 := by
  norm_num [normalFormOmega]

/-- The deliberate motion `(r²,0)` has nonzero strict obstruction. -/
theorem low_tangent_negative_control :
    strictOmega 1 0 = 2 ∧ strictOmega 1 0 ≠ 0 := by
  norm_num [strictOmega]

/-- The polar motion starts in orders `r³,r⁴`, so both low coefficients
entering the strict obstruction vanish. -/
theorem polar_prefix_omega_zero :
    strictOmega 0 0 = 0 := by
  norm_num [strictOmega]

theorem strict_compatible_iff (a₂ b₃ : ℚ) :
    strictOmega a₂ b₃ = 0 ↔ b₃ = -(2 * a₂) / 3 := by
  unfold strictOmega
  constructor <;> intro h <;> linarith

def InTwoThreeSemigroup (n : ℕ) : Prop :=
  ∃ i j : ℕ, n = 2 * i + 3 * j

/-- Every natural number except one belongs to the numerical semigroup
generated by two and three. -/
theorem in_two_three_of_ne_one (n : ℕ) (hne : n ≠ 1) :
    InTwoThreeSemigroup n := by
  rcases Nat.even_or_odd n with ⟨k, hk⟩ | ⟨k, hk⟩
  · exact ⟨k, 0, by omega⟩
  · have hkpos : 0 < k := by
      omega
    exact ⟨k - 1, 1, by omega⟩

/-- The two exponents left by the cusp stabilizer are exactly `2` and `4`;
every other exponent at least two lies in `3 + ⟨2,3⟩`. -/
theorem stabilizer_semigroup_gap (n : ℕ) (hn : 2 ≤ n) :
    n = 2 ∨ n = 4 ∨
      ∃ i j : ℕ, n = 3 + 2 * i + 3 * j := by
  by_cases htwo : n = 2
  · exact Or.inl htwo
  by_cases hfour : n = 4
  · exact Or.inr (Or.inl hfour)
  · right
    right
    have hne : n - 3 ≠ 1 := by
      omega
    obtain ⟨i, j, hij⟩ := in_two_three_of_ne_one (n - 3) hne
    exact ⟨i, j, by omega⟩

theorem two_not_in_shifted_semigroup :
    ¬ ∃ i j : ℕ, 2 = 3 + 2 * i + 3 * j := by
  omega

theorem four_not_in_shifted_semigroup :
    ¬ ∃ i j : ℕ, 4 = 3 + 2 * i + 3 * j := by
  omega

/-- A cusp exponent `m ≥ 5` has a `2a+3b` representative whose ordinary
monomial degree is exactly `ceil(m/3) = (m+2)/3`. -/
theorem optimal_two_three_section (m : ℕ) (hm : 5 ≤ m) :
    ∃ a b : ℕ,
      m = 2 * a + 3 * b ∧
      a + b = (m + 2) / 3 := by
  have hmod : m % 3 < 3 := Nat.mod_lt m (by omega)
  have hdiv : m % 3 + 3 * (m / 3) = m := Nat.mod_add_div m 3
  interval_cases hrem : m % 3
  · exact ⟨0, m / 3, by omega, by omega⟩
  · exact ⟨2, m / 3 - 1, by omega, by omega⟩
  · exact ⟨1, m / 3, by omega, by omega⟩

/-- No `P^a Q^b` representative of cusp exponent `m` has ordinary degree
below `ceil(m/3)`. -/
theorem two_three_section_degree_lower
    (m a b : ℕ) (hrep : m = 2 * a + 3 * b) :
    (m + 2) / 3 ≤ a + b := by
  omega

theorem optimal_two_three_section_minimal (m : ℕ) (hm : 5 ≤ m) :
    ∃ a b : ℕ,
      m = 2 * a + 3 * b ∧
      ∀ a' b' : ℕ,
        m = 2 * a' + 3 * b' →
        a + b ≤ a' + b' := by
  obtain ⟨a, b, hrep, hdegree⟩ := optimal_two_three_section m hm
  refine ⟨a, b, hrep, ?_⟩
  intro a' b' hrep'
  rw [hdegree]
  exact two_three_section_degree_lower m a' b' hrep'

/-- Terminal arithmetic carrier.  It does not assert the polynomial
restriction-map exact sequence described in the module documentation. -/
theorem seed_prefix_quotient_arithmetic_terminal_certificate :
    (∀ a₂ b₃ : ℚ,
      normalFormOmega a₂ (b₃ - a₂) = strictOmega a₂ b₃) ∧
    normalFormOmega (-3) 5 = 0 ∧
    strictOmega 1 0 ≠ 0 ∧
    strictOmega 0 0 = 0 ∧
    (∀ n : ℕ, 2 ≤ n →
      n = 2 ∨ n = 4 ∨
        ∃ i j : ℕ, n = 3 + 2 * i + 3 * j) ∧
    (∀ m : ℕ, 5 ≤ m →
      ∃ a b : ℕ,
        m = 2 * a + 3 * b ∧
        ∀ a' b' : ℕ,
          m = 2 * a' + 3 * b' →
          a + b ≤ a' + b') := by
  refine ⟨omega_coordinate_identity, pq_pair_omega_zero,
    low_tangent_negative_control.2, polar_prefix_omega_zero,
    stabilizer_semigroup_gap, ?_⟩
  exact optimal_two_three_section_minimal

end AxiomPackJacobianSeedPrefixQuotientArithmetic
