import Mathlib

/-!
Finite kernel certificate for the filtered Hamiltonian-jet calculation around
the public dimension-three Keller map.

The first part checks the independently extracted first derivative of the
normalized cubic weighted-lift family.  The second part checks polynomial
division certificates modulo its cubic inverse relation.  The final arithmetic
lemma is the associated-graded obstruction used to eliminate every
positive-degree fixed-gamma source shear.

The interpretation is deliberately scoped to polynomial target Hamiltonians
and polynomial source shears that fix `gamma`; broader equivariant coordinate
groups are not classified here.
-/

namespace AxiomPackJacobianHamiltonianJet

def gamma (v t : ℚ) : ℚ := 1 - (3 / 2) * v + t

def beta0 (v t : ℚ) : ℚ :=
  -3 * t * v^2 - 6 * t * v - 3 * t + (9 / 2) * v^3 + 6 * v^2 + v / 2

def alpha0 (v t : ℚ) : ℚ :=
  -2 * t * v^3 - 6 * t * v^2 - 6 * t * v - 2 * t +
    3 * v^4 + 7 * v^3 + 4 * v^2

/-- First derivative extracted from the normalized rational family, before
identifying its Hamiltonian form. -/
def betaTangent (v t : ℚ) : ℚ :=
  t^2 * v^3 + 3 * t^2 * v^2 + 3 * t^2 * v + t^2 -
    3 * t * v^4 - 7 * t * v^3 - (7 / 2) * t * v^2 +
    (3 / 2) * t * v + t + (9 / 4) * v^5 + (15 / 4) * v^4 -
    v^3 / 2 - 2 * v^2

/-- First derivative extracted from the normalized rational family, before
identifying its Hamiltonian form. -/
def alphaTangent (v t : ℚ) : ℚ :=
  (3 / 4) * t^2 * v^4 + 3 * t^2 * v^3 + (9 / 2) * t^2 * v^2 +
    3 * t^2 * v + (3 / 4) * t^2 - (9 / 4) * t * v^5 -
    (15 / 2) * t * v^4 - (17 / 2) * t * v^3 -
    (7 / 2) * t * v^2 - t * v / 4 + (27 / 16) * v^6 +
    (9 / 2) * v^5 + (27 / 8) * v^4 + v^3 / 2 + v^2 / 48

/-- The family tangent is exactly the target Hamiltonian vector field
generated by `H(P,Q) = -Q^2/4 - P^3/36`. -/
theorem first_derivative_is_hamiltonian (v t : ℚ) :
    betaTangent v t = -(gamma v t * alpha0 v t) / 2 ∧
    alphaTangent v t = (beta0 v t)^2 / 12 := by
  constructor <;>
    simp only [betaTangent, alphaTangent, beta0, alpha0, gamma] <;>
    ring

def inverseRelation (P Q w : ℚ) : ℚ := w^3 - w^2 + P * w - Q

def weightedGamma (P w : ℚ) : ℚ := P - 2 * w + 3 * w^2

def residualPNumerator (P w : ℚ) : ℚ :=
  let g := weightedGamma P w
  6 * g * w^2 - 6 * g * w + 2 * g + 9 * w^4 - 32 * w^3 +
    27 * w^2 - 6 * w

def residualPQuotient (w : ℚ) : ℚ := 27 * w - 35

def residualPRemainder (P Q w : ℚ) : ℚ :=
  -21 * P * w^2 + 29 * P * w + 2 * P + 27 * Q * w - 35 * Q +
    10 * w^2 - 10 * w

def residualQNumerator (P w : ℚ) : ℚ :=
  let g := weightedGamma P w
  2 * g^2 + 2 * g * w^3 - 12 * g * w^2 + 6 * g * w +
    12 * w^5 - 17 * w^4 + 6 * w^3 + w^2

def residualQQuotient (P w : ℚ) : ℚ := -16 * P + 18 * w^2 - 21 * w + 3

def residualQRemainder (P Q w : ℚ) : ℚ :=
  16 * P^2 * w + 2 * P^2 - 16 * P * Q + 5 * P * w^2 -
    5 * P * w + 18 * Q * w^2 - 21 * Q * w + 3 * Q

def sourceP (P w : ℚ) : ℚ :=
  weightedGamma P w * (2 - 6 * w)

def sourcePRemainder (P Q w : ℚ) : ℚ :=
  2 * (6 * P * w + P - 9 * Q - 2 * w)

def sourceQ (P w : ℚ) : ℚ :=
  let g := weightedGamma P w
  g * (g + 2 * w - 6 * w^2)

def sourceQRemainder (P Q w : ℚ) : ℚ :=
  P^2 + 9 * P * w^2 + P * w - 9 * Q * w - 3 * Q - 3 * w^2

/-- Exact quotient/remainder certificates for the second-jet residual and the
constant fixed-gamma source shear. -/
theorem inverse_relation_remainder_certificate (P Q w : ℚ) :
    residualPNumerator P w =
      residualPQuotient w * inverseRelation P Q w +
        residualPRemainder P Q w ∧
    residualQNumerator P w =
      residualQQuotient P w * inverseRelation P Q w +
        residualQRemainder P Q w ∧
    sourceP P w = -18 * inverseRelation P Q w + sourcePRemainder P Q w ∧
    sourceQ P w =
      (-3 * (3 * w + 1)) * inverseRelation P Q w +
        sourceQRemainder P Q w := by
  simp only [residualPNumerator, residualPQuotient, residualPRemainder,
    residualQNumerator, residualQQuotient, residualQRemainder, sourceP,
    sourcePRemainder, sourceQ, sourceQRemainder, weightedGamma,
    inverseRelation]
  constructor
  · ring
  constructor
  · ring
  constructor <;> ring

/-- In the associated grading `wt(w,P,Q)=(1,2,3)`, after specializing
`P=0`, the two top source components have exponents `2n+3` and `2n+4`.
They cannot both reduce to the base subring modulo `w^3-Q`. -/
theorem positive_degree_source_has_nonbase_top_component (n : ℕ) :
    ¬ (3 ∣ 2 * n + 3 ∧ 3 ∣ 2 * n + 4) := by
  omega

/-- Once positive source degree is excluded, a constant source shear has no
`w^2` term in its first remainder.  The residual coefficient is the nonzero
polynomial `(10-21P)/24`, witnessed already at `P=0`. -/
theorem constant_source_cannot_cancel_w2 :
    ∃ P : ℚ, (10 - 21 * P) / 24 ≠ 0 := by
  refine ⟨0, ?_⟩
  norm_num

/-- Terminal finite certificate for the second-order departure from the
declared polynomial coordinate subgroup. -/
theorem second_jet_escape_certificate :
    (∀ v t : ℚ,
      betaTangent v t = -(gamma v t * alpha0 v t) / 2 ∧
      alphaTangent v t = (beta0 v t)^2 / 12) ∧
    (∀ n : ℕ, ¬ (3 ∣ 2 * n + 3 ∧ 3 ∣ 2 * n + 4)) ∧
    (∃ P : ℚ, (10 - 21 * P) / 24 ≠ 0) := by
  exact ⟨first_derivative_is_hamiltonian,
    positive_degree_source_has_nonbase_top_component,
    constant_source_cannot_cancel_w2⟩

end AxiomPackJacobianHamiltonianJet
