import ZtareProofs.AxiomPackJacobianConeTransverseTowerArithmetic

/-!
Arithmetic carrier for the first surviving opposite-parity class in the
exceptional-divisor normal form of the normalized Jacobian family.

After the divisor and layer-one target normalizations, the complete
weight-five target image in layer two is the odd span generated by
`A`, `A^3`, and `A^5`.  The exact seed-linearized augmented coefficient
system has the displayed nonzero four-by-four minor, and the canonical even
residue begins with `(31 - 45*A^2)/96`.

The scalar pullback identity, completeness of the target image, and
identification of these entries with the moving family remain in the
deterministic replay and pencil proof.  This file checks the exact minor,
nonvanishing residue, and parity-routing arithmetic used by the successor
Magnus analysis.
-/

namespace AxiomPackJacobianSecondTransverseQuotientArithmetic

/-- Four-row seed-linearized witness for the augmented rank jump. -/
def linearizedRankWitness : Matrix (Fin 4) (Fin 4) ℚ :=
  Matrix.of ![
    ![0, 0, 0, 31 / 96],
    ![0, 0, -5 / 8, -25 / 128],
    ![0, 5 / 2, 5 / 4, 55 / 192],
    ![-10, -5 / 2, -5 / 8, 7 / 128]
  ]

theorem linearized_rank_witness_determinant :
    linearizedRankWitness.det = 3875 / 768 := by
  have h :
      (3 : Fin 4).succAbove (2 : Fin 3) = (2 : Fin 4) := by
    decide
  simp [linearizedRankWitness, Matrix.det_succ_row_zero,
    Fin.sum_univ_succ, h]
  norm_num

theorem linearized_rank_witness_nonsingular :
    linearizedRankWitness.det ≠ 0 := by
  rw [linearized_rank_witness_determinant]
  norm_num

/-- Seed-linearized canonical representative of the layer-two quotient. -/
def linearizedEvenResidue (A : ℚ) : ℚ :=
  (31 - 45 * A ^ 2) / 96

theorem linearized_even_residue_at_zero :
    linearizedEvenResidue 0 = 31 / 96 := by
  norm_num [linearizedEvenResidue]

theorem linearized_even_residue_nonzero :
    ∃ A : ℚ, linearizedEvenResidue A ≠ 0 := by
  refine ⟨0, ?_⟩
  rw [linearized_even_residue_at_zero]
  norm_num

/-- Parity of a bracket reverses the sum of the input parities.  Target
parity in layer `m` is `m+1`, while residue parity is `m`. -/
theorem target_target_parity (m n : ℕ) :
    ((m + 1) + (n + 1) + 1) % 2 =
      (m + n + 1) % 2 := by
  omega

theorem target_residue_parity (m n : ℕ) :
    ((m + 1) + n + 1) % 2 =
      (m + n) % 2 := by
  omega

theorem residue_residue_parity (m n : ℕ) :
    (m + n + 1) % 2 =
      (m + n + 1) % 2 := by
  rfl

/-- Terminal arithmetic carrier for the rank jump, nonzero canonical class,
and the three parity-routing endpoints. -/
theorem second_transverse_quotient_arithmetic_terminal_certificate :
    linearizedRankWitness.det = 3875 / 768 ∧
    linearizedRankWitness.det ≠ 0 ∧
    (∃ A : ℚ, linearizedEvenResidue A ≠ 0) ∧
    (∀ m n : ℕ,
      ((m + 1) + (n + 1) + 1) % 2 =
        (m + n + 1) % 2) ∧
    (∀ m n : ℕ,
      ((m + 1) + n + 1) % 2 =
        (m + n) % 2) := by
  exact ⟨linearized_rank_witness_determinant,
    linearized_rank_witness_nonsingular,
    linearized_even_residue_nonzero,
    target_target_parity,
    target_residue_parity⟩

end AxiomPackJacobianSecondTransverseQuotientArithmetic
