import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.RingTheory.UniqueFactorizationDomain.Multiplicity
import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.Tactic
import ZtareProofs.FormalDerivationFactorMultiplicityDescent

/-!
# A proper finite derivative ideal produces a Darboux prime

In a principal unique-factorization domain, the ideal generated by a finite
derivative prefix has one generator.  If the ideal is proper and contains a
nonzero initial element, that generator has an irreducible factor.  The
factor divides every prefix row.  Once the prefix reaches the factor's exact
multiplicity in the initial element, finite multiplicity descent forces the
factor to divide its own derivative.

The caller supplies a uniform bound on factor multiplicities and the fact
that positive natural scalars through that bound are units.  Polynomial
rings over characteristic-zero fields satisfy both with the polynomial
degree as a bound.
-/

namespace FormalFiniteDerivativeDarbouxAlternative

open Ideal
open Polynomial
open Submodule.IsPrincipal
open FormalDerivationFactorMultiplicityDescent

variable {R : Type*}
  [CommRing R] [IsDomain R]
  [IsPrincipalIdealRing R] [UniqueFactorizationMonoid R]

noncomputable section

/-- The derivative prefix through `bound` as a finitely generated ideal. -/
def derivativePrefixIdeal
    (D : Derivation ℤ R R) (initial : R) (bound : ℕ) : Ideal R :=
  Ideal.span (Set.range fun index : Fin (bound + 1) ↦
    (D : R → R)^[index.1] initial)

/-- A proper derivative-prefix ideal contains a prime factor that is Darboux
for the derivation. -/
theorem exists_darboux_prime_of_derivativePrefixIdeal_ne_top
    (D : Derivation ℤ R R) (initial : R) (bound : ℕ)
    (hinitial : initial ≠ 0)
    (hscalarUnits : ∀ scalar : ℕ, 0 < scalar → IsUnit (scalar : R))
    (hmultiplicityBound : ∀ h : R, Prime h → h ∣ initial →
      multiplicity h initial ≤ bound)
    (hproper : derivativePrefixIdeal D initial bound ≠ ⊤) :
    ∃ h : R, Prime h ∧ h ∣ initial ∧ h ∣ D h := by
  let prefixIdeal := derivativePrefixIdeal D initial bound
  let prefixGenerator := Submodule.IsPrincipal.generator prefixIdeal
  have hinitialMem : initial ∈ prefixIdeal := by
    apply Ideal.subset_span
    refine ⟨⟨0, Nat.zero_lt_succ bound⟩, ?_⟩
    simp
  have hgeneratorNonzero : prefixGenerator ≠ 0 := by
    intro hzero
    have hbot : prefixIdeal = ⊥ :=
      (Submodule.IsPrincipal.eq_bot_iff_generator_eq_zero prefixIdeal).2 hzero
    rw [hbot] at hinitialMem
    exact hinitial (by simpa using hinitialMem)
  have hgeneratorNonunit : ¬IsUnit prefixGenerator := by
    intro hunit
    apply hproper
    change prefixIdeal = ⊤
    rw [← Ideal.span_singleton_generator prefixIdeal,
      Ideal.span_singleton_eq_top]
    exact hunit
  obtain ⟨h, hirreducible, hdivGenerator⟩ :=
    WfDvdMonoid.exists_irreducible_factor
      hgeneratorNonunit hgeneratorNonzero
  have hprime : Prime h := irreducible_iff_prime.mp hirreducible
  have hgeneratorDvdInitial : prefixGenerator ∣ initial :=
    (Submodule.IsPrincipal.mem_iff_generator_dvd prefixIdeal).mp hinitialMem
  have hdivInitial : h ∣ initial :=
    hdivGenerator.trans hgeneratorDvdInitial
  let factorMultiplicity := multiplicity h initial
  have hmultiplicityLe : factorMultiplicity ≤ bound :=
    hmultiplicityBound h hprime hdivInitial
  have hfinite : FiniteMultiplicity h initial :=
    FiniteMultiplicity.of_prime_left hprime hinitial
  obtain ⟨cofactor, hfactorization, hcofactor⟩ :=
    hfinite.exists_eq_pow_mul_and_not_dvd
  have hpersistent :
      h ∣ (D : R → R)^[factorMultiplicity]
        (h ^ factorMultiplicity * cofactor) := by
    rw [← hfactorization]
    apply hdivGenerator.trans
    apply (Submodule.IsPrincipal.mem_iff_generator_dvd prefixIdeal).mp
    apply Ideal.subset_span
    refine ⟨⟨factorMultiplicity, Nat.lt_succ_iff.mpr hmultiplicityLe⟩, rfl⟩
  have hscalars : ∀ scalar : ℕ,
      0 < scalar → scalar ≤ factorMultiplicity →
        ¬h ∣ (scalar : R) := by
    intro scalar hpositive _hbounded hdvd
    exact hprime.not_unit
      (isUnit_of_dvd_unit hdvd (hscalarUnits scalar hpositive))
  have hdarboux : h ∣ D h :=
    prime_dvd_derivative_of_persists_to_multiplicity
      D h cofactor factorMultiplicity hprime hscalars hcofactor hpersistent
  exact ⟨h, hprime, hdivInitial, hdarboux⟩

/-- The exact finite alternative: either the prefix ideal is top, or it
contains a Darboux prime factor of the initial element. -/
theorem derivativePrefixIdeal_top_or_exists_darboux_prime
    (D : Derivation ℤ R R) (initial : R) (bound : ℕ)
    (hinitial : initial ≠ 0)
    (hscalarUnits : ∀ scalar : ℕ, 0 < scalar → IsUnit (scalar : R))
    (hmultiplicityBound : ∀ h : R, Prime h → h ∣ initial →
      multiplicity h initial ≤ bound) :
    derivativePrefixIdeal D initial bound = ⊤ ∨
      ∃ h : R, Prime h ∧ h ∣ initial ∧ h ∣ D h := by
  by_cases htop : derivativePrefixIdeal D initial bound = ⊤
  · exact Or.inl htop
  · exact Or.inr
      (exists_darboux_prime_of_derivativePrefixIdeal_ne_top
        D initial bound hinitial hscalarUnits hmultiplicityBound htop)

/-- For a univariate polynomial over a characteristic-zero field, the
polynomial degree supplies both missing adapter obligations automatically.
-/
theorem polynomial_derivativePrefixIdeal_top_or_exists_darboux_prime
    {K : Type*} [Field K] [CharZero K]
    (D : Derivation ℤ K[X] K[X]) (initial : K[X])
    (hinitial : initial ≠ 0) :
    derivativePrefixIdeal D initial initial.natDegree = ⊤ ∨
      ∃ h : K[X], Prime h ∧ h ∣ initial ∧ h ∣ D h := by
  apply derivativePrefixIdeal_top_or_exists_darboux_prime
    D initial initial.natDegree hinitial
  · intro scalar hpositive
    change IsUnit (Polynomial.C (scalar : K))
    apply Polynomial.isUnit_C.mpr
    apply isUnit_iff_ne_zero.mpr
    exact_mod_cast (Nat.ne_of_gt hpositive)
  · intro h hprime _hdivides
    have hpower :
        h ^ multiplicity h initial ∣ initial :=
      pow_multiplicity_dvd h initial
    have hdegree :
        (h ^ multiplicity h initial).natDegree ≤ initial.natDegree :=
      Polynomial.natDegree_le_of_dvd hpower hinitial
    rw [Polynomial.natDegree_pow] at hdegree
    have hdegreePositive : 0 < h.natDegree := by
      apply Nat.pos_of_ne_zero
      intro hdegreeZero
      have hdegreeZero' : h.degree = 0 := by
        rw [Polynomial.degree_eq_natDegree hprime.ne_zero, hdegreeZero]
        rfl
      exact hprime.not_unit
        (Polynomial.isUnit_iff_degree_eq_zero.mpr hdegreeZero')
    nlinarith

/-- Aggregated finite Darboux-or-unit-ideal certificate. -/
theorem finite_derivative_darboux_alternative_terminal_certificate :
    ∀ (D : Derivation ℤ R R) (initial : R) (bound : ℕ),
      initial ≠ 0 →
      (∀ scalar : ℕ, 0 < scalar → IsUnit (scalar : R)) →
      (∀ h : R, Prime h → h ∣ initial →
        multiplicity h initial ≤ bound) →
      derivativePrefixIdeal D initial bound = ⊤ ∨
        ∃ h : R, Prime h ∧ h ∣ initial ∧ h ∣ D h := by
  intro D initial bound hinitial hscalarUnits hmultiplicityBound
  exact derivativePrefixIdeal_top_or_exists_darboux_prime
    D initial bound hinitial hscalarUnits hmultiplicityBound

/-- Aggregated polynomial specialization with the intrinsic degree bound. -/
theorem polynomial_finite_derivative_darboux_alternative_terminal_certificate :
    ∀ {K : Type*} [Field K] [CharZero K]
      (D : Derivation ℤ K[X] K[X]) (initial : K[X]),
      initial ≠ 0 →
      derivativePrefixIdeal D initial initial.natDegree = ⊤ ∨
        ∃ h : K[X], Prime h ∧ h ∣ initial ∧ h ∣ D h := by
  intro K _ _ D initial hinitial
  exact polynomial_derivativePrefixIdeal_top_or_exists_darboux_prime
    D initial hinitial

end

end FormalFiniteDerivativeDarbouxAlternative
