import Mathlib.Algebra.Polynomial.Eval.Defs
import Mathlib.Tactic
import ZtareProofs.FormalFiniteDerivativeDarbouxAlternative

/-!
# Evaluation of finite derivative-prefix ideals

If a ring homomorphism kills every iterate in a finite derivative prefix,
then its kernel contains the ideal generated by that prefix.  Consequently it
kills every ideal member.  This is the algebraic evaluation step only: no
final scalar relation, common zero, or analytic realization is assumed.
-/

namespace FormalDerivativePrefixEvaluation

open Ideal
open Polynomial

open FormalFiniteDerivativeDarbouxAlternative

variable {R S : Type*} [CommRing R] [CommRing S]

/-- Generator-wise annihilation puts the complete derivative-prefix ideal in
the kernel of the evaluating ring homomorphism. -/
theorem derivativePrefixIdeal_le_ker
    (D : Derivation ℤ R R) (initial : R) (bound : ℕ)
    (evaluation : R →+* S)
    (generators_vanish : ∀ index : Fin (bound + 1),
      evaluation (((D : R → R)^[index.1]) initial) = 0) :
    derivativePrefixIdeal D initial bound ≤ RingHom.ker evaluation := by
  rw [derivativePrefixIdeal, Ideal.span_le]
  rintro value ⟨index, rfl⟩
  exact (RingHom.mem_ker).2 (generators_vanish index)

/-- Every member of the derivative-prefix ideal vanishes under an evaluation
that kills the generating iterates. -/
theorem map_eq_zero_of_mem_derivativePrefixIdeal
    (D : Derivation ℤ R R) (initial : R) (bound : ℕ)
    (evaluation : R →+* S)
    (generators_vanish : ∀ index : Fin (bound + 1),
      evaluation (((D : R → R)^[index.1]) initial) = 0)
    (member : R)
    (member_mem : member ∈ derivativePrefixIdeal D initial bound) :
    evaluation member = 0 := by
  exact (RingHom.mem_ker).1
    (derivativePrefixIdeal_le_ker D initial bound evaluation
      generators_vanish member_mem)

/-- A common zero in a nontrivial target forces the derivative-prefix ideal
to be proper. -/
theorem derivativePrefixIdeal_ne_top_of_generators_vanish
    [Nontrivial S]
    (D : Derivation ℤ R R) (initial : R) (bound : ℕ)
    (evaluation : R →+* S)
    (generators_vanish : ∀ index : Fin (bound + 1),
      evaluation (((D : R → R)^[index.1]) initial) = 0) :
    derivativePrefixIdeal D initial bound ≠ ⊤ := by
  intro htop
  have honeMem : (1 : R) ∈ derivativePrefixIdeal D initial bound := by
    rw [htop]
    exact Set.mem_univ 1
  have honeZero := map_eq_zero_of_mem_derivativePrefixIdeal
    D initial bound evaluation generators_vanish 1 honeMem
  exact one_ne_zero (by simpa only [map_one] using honeZero)

/-- Polynomial `eval₂` is a ring homomorphism, so generator-wise vanishing at
one algebraic point propagates to every polynomial in the derivative-prefix
ideal. -/
theorem eval₂_eq_zero_of_mem_derivativePrefixIdeal
    {K : Type*} [CommRing K]
    (D : Derivation ℤ K[X] K[X])
    (initial : K[X]) (bound : ℕ)
    (coefficientMap : K →+* S) (point : S)
    (generators_vanish : ∀ index : Fin (bound + 1),
      (((D : K[X] → K[X])^[index.1]) initial).eval₂
        coefficientMap point = 0)
    (member : K[X])
    (member_mem : member ∈ derivativePrefixIdeal D initial bound) :
    member.eval₂ coefficientMap point = 0 := by
  exact map_eq_zero_of_mem_derivativePrefixIdeal
    D initial bound (Polynomial.eval₂RingHom coefficientMap point)
    generators_vanish member member_mem

/-- Aggregated derivative-prefix evaluation certificate. -/
theorem derivative_prefix_evaluation_terminal_certificate :
    ∀ (D : Derivation ℤ R R) (initial : R) (bound : ℕ)
      (evaluation : R →+* S),
      (∀ index : Fin (bound + 1),
        evaluation (((D : R → R)^[index.1]) initial) = 0) →
      derivativePrefixIdeal D initial bound ≤ RingHom.ker evaluation ∧
        ∀ member : R,
          member ∈ derivativePrefixIdeal D initial bound →
          evaluation member = 0 := by
  intro D initial bound evaluation generators_vanish
  exact ⟨
    derivativePrefixIdeal_le_ker D initial bound evaluation
      generators_vanish,
    fun member member_mem =>
      map_eq_zero_of_mem_derivativePrefixIdeal
        D initial bound evaluation generators_vanish member member_mem⟩

end FormalDerivativePrefixEvaluation
