import Mathlib.RingTheory.PowerSeries.Derivative
import Mathlib.RingTheory.PowerSeries.Substitution
import Mathlib.Tactic

/-!
All-order Julia identity for autonomous formal substitution flows.

The governing object is a time-one substitution endomorphism commuting with
the derivation generated by the autonomous vector field.  This invariant is
universal over every germ; Julia's equation is derived by applying it to the
coordinate `X`.
-/

namespace FormalAutonomousFlow

open PowerSeries

section Ring

variable {k : Type*} [CommRing k]

/-- Action of the one-dimensional autonomous vector field `generator*d/dX`. -/
noncomputable def vectorFieldAction
    (generator germ : k⟦X⟧) : k⟦X⟧ :=
  generator * d⁄dX k germ

/-- A fixed-origin substitution commuting with an autonomous vector field.

`commutes_generator` is an all-germ derivation invariant.  It records the
autonomous commutant category and fixes the substitution orientation; it is
not Julia's coordinate consequence and does not by itself distinguish a
time-one map from the zero substitution. -/
structure AutonomousSubstitutionCommutant
    (generator endpoint : k⟦X⟧) : Prop where
  endpoint_constantCoeff : constantCoeff endpoint = 0
  commutes_generator : ∀ germ : k⟦X⟧,
    (vectorFieldAction generator germ).subst endpoint =
      vectorFieldAction generator (germ.subst endpoint)

/-- Identity of a normalized formal autonomous time-one substitution.

An autonomous flow fixing the origin is tangent to the identity.  Keeping
that normalization in the flow object rules out degenerate commutants and
makes substitution by the endpoint an automorphism. -/
structure AutonomousSubstitutionTimeOne
    (generator endpoint : k⟦X⟧) : Prop
    extends AutonomousSubstitutionCommutant generator endpoint where
  endpoint_coeff_one : coeff 1 endpoint = 1

theorem AutonomousSubstitutionTimeOne.hasSubst
    {generator endpoint : k⟦X⟧}
    (flow : AutonomousSubstitutionTimeOne generator endpoint) :
    HasSubst endpoint :=
  HasSubst.of_constantCoeff_zero' flow.endpoint_constantCoeff

/-- The coordinate Julia equation constructs the complete autonomous
commutant.  The chain rule upgrades the equation on `X` to commutation on
every formal germ. -/
theorem AutonomousSubstitutionTimeOne.of_julia
    (generator endpoint : k⟦X⟧)
    (hconstant : constantCoeff endpoint = 0)
    (hlinear : coeff 1 endpoint = 1)
    (hjulia : generator.subst endpoint =
      d⁄dX k endpoint * generator) :
    AutonomousSubstitutionTimeOne generator endpoint := by
  have hendpoint : HasSubst endpoint :=
    HasSubst.of_constantCoeff_zero' hconstant
  refine
    { endpoint_constantCoeff := hconstant
      endpoint_coeff_one := hlinear
      commutes_generator := ?_ }
  intro germ
  unfold vectorFieldAction
  rw [PowerSeries.subst_mul hendpoint, hjulia,
    PowerSeries.derivative_subst k hendpoint]
  ring

/-- The identity substitution is a normalized autonomous commutant for every
generator.  This is the padding object used when an actual exponential
specializes from the zero generator to the identity endpoint. -/
theorem AutonomousSubstitutionTimeOne.identity
    (generator : k⟦X⟧) :
    AutonomousSubstitutionTimeOne generator PowerSeries.X := by
  apply AutonomousSubstitutionTimeOne.of_julia
  · simp
  · simp
  · simp

/-- Coefficient extension commutes with the one-variable formal derivative. -/
theorem derivative_map
    {K : Type*} [CommRing K]
    (hom : k →+* K) (germ : k⟦X⟧) :
    PowerSeries.map hom (d⁄dX k germ) =
      d⁄dX K (PowerSeries.map hom germ) := by
  ext index
  simp [PowerSeries.coeff_derivative, PowerSeries.coeff_map]

/-- Every coefficient specialization preserves the complete normalized
autonomous-substitution object. -/
theorem AutonomousSubstitutionTimeOne.map
    {K : Type*} [CommRing K]
    (hom : k →+* K)
    {generator endpoint : k⟦X⟧}
    (flow : AutonomousSubstitutionTimeOne generator endpoint) :
    AutonomousSubstitutionTimeOne
      (PowerSeries.map hom generator)
      (PowerSeries.map hom endpoint) := by
  have mappedConstant :
      constantCoeff (PowerSeries.map hom endpoint) = 0 := by
    simpa [← PowerSeries.coeff_zero_eq_constantCoeff,
      PowerSeries.coeff_map] using congrArg hom flow.endpoint_constantCoeff
  have mappedLinear : coeff 1 (PowerSeries.map hom endpoint) = 1 := by
    simpa [PowerSeries.coeff_map] using congrArg hom flow.endpoint_coeff_one
  have sourceJulia :
      generator.subst endpoint = d⁄dX k endpoint * generator := by
    have coordinateCommutation := flow.commutes_generator X
    rw [vectorFieldAction, derivative_X, mul_one,
      vectorFieldAction, subst_X flow.hasSubst] at coordinateCommutation
    simpa [mul_comm] using coordinateCommutation
  apply AutonomousSubstitutionTimeOne.of_julia
    (PowerSeries.map hom generator) (PowerSeries.map hom endpoint)
    mappedConstant mappedLinear
  calc
    (PowerSeries.map hom generator).subst
        (PowerSeries.map hom endpoint) =
      PowerSeries.map hom (generator.subst endpoint) :=
        (PowerSeries.map_subst flow.hasSubst
          (h := hom) generator).symm
    _ = PowerSeries.map hom (d⁄dX k endpoint * generator) := by
      rw [sourceJulia]
    _ = d⁄dX K (PowerSeries.map hom endpoint) *
        PowerSeries.map hom generator := by
      rw [map_mul, derivative_map]

/-- A coefficient specialization preserves an exact two-endpoint
substitution composition. -/
theorem map_endpoint_composition
    {K : Type*} [CommRing K]
    (hom : k →+* K)
    {innerEndpoint outerEndpoint visible : k⟦X⟧}
    (inner_hasSubst : HasSubst innerEndpoint)
    (factorization :
      PowerSeries.subst innerEndpoint outerEndpoint = visible) :
    PowerSeries.subst (PowerSeries.map hom innerEndpoint)
        (PowerSeries.map hom outerEndpoint) =
      PowerSeries.map hom visible := by
  calc
    PowerSeries.subst (PowerSeries.map hom innerEndpoint)
        (PowerSeries.map hom outerEndpoint) =
      PowerSeries.map hom
        (PowerSeries.subst innerEndpoint outerEndpoint) :=
      (PowerSeries.map_subst inner_hasSubst
        (h := hom) outerEndpoint).symm
    _ = PowerSeries.map hom visible :=
      congrArg (PowerSeries.map hom) factorization

end Ring

section Field

variable {k : Type*} [Field k]

theorem AutonomousSubstitutionTimeOne.coeff_one_ne_zero
    {generator endpoint : k⟦X⟧}
    (flow : AutonomousSubstitutionTimeOne generator endpoint) :
    coeff 1 endpoint ≠ 0 := by
  rw [flow.endpoint_coeff_one]
  exact one_ne_zero

/-- A normalized time-one endpoint has a compositional inverse. -/
theorem AutonomousSubstitutionTimeOne.subst_injective
    {generator endpoint : k⟦X⟧}
    (flow : AutonomousSubstitutionTimeOne generator endpoint) :
    Function.Injective (fun germ : k⟦X⟧ ↦ germ.subst endpoint) := by
  letI : Invertible (coeff 1 endpoint) :=
    invertibleOfNonzero flow.coeff_one_ne_zero
  intro left right hequal
  have hinverse : HasSubst endpoint.substInv :=
    PowerSeries.hasSubst_substInv endpoint
  have hleft := congrArg
    (fun germ : k⟦X⟧ ↦ germ.subst endpoint.substInv) hequal
  simpa only [PowerSeries.subst_comp_subst_apply flow.hasSubst hinverse,
    PowerSeries.subst_substInv_right endpoint flow.endpoint_constantCoeff,
    PowerSeries.X_subst] using hleft

/-- No nonzero germ can vanish after substitution by a normalized time-one
endpoint. -/
theorem AutonomousSubstitutionTimeOne.subst_ne_zero
    {generator endpoint germ : k⟦X⟧}
    (flow : AutonomousSubstitutionTimeOne generator endpoint)
    (hgerm : germ ≠ 0) :
    germ.subst endpoint ≠ 0 := by
  intro hzero
  apply hgerm
  apply flow.subst_injective
  have hsubstZero : (0 : k⟦X⟧).subst endpoint = 0 := by
    rw [← PowerSeries.coe_substAlgHom flow.hasSubst]
    exact map_zero (PowerSeries.substAlgHom flow.hasSubst)
  change germ.subst endpoint = (0 : k⟦X⟧).subst endpoint
  rw [hzero, hsubstZero]

/-- Julia's identity follows at every formal coefficient from autonomous
derivation commutation. -/
theorem julia_identity
    (generator endpoint : k⟦X⟧)
    (flow : AutonomousSubstitutionTimeOne generator endpoint) :
    generator.subst endpoint = d⁄dX k endpoint * generator := by
  have h := flow.commutes_generator X
  rw [vectorFieldAction, derivative_X, mul_one,
    vectorFieldAction, subst_X flow.hasSubst] at h
  simpa [mul_comm] using h

/-- Polynomial generators are a special case of the all-series theorem. -/
theorem polynomial_julia_identity
    (generator : Polynomial k) (endpoint : k⟦X⟧)
    (flow : AutonomousSubstitutionTimeOne
      (generator : k⟦X⟧) endpoint) :
    (generator : k⟦X⟧).subst endpoint =
      d⁄dX k endpoint * (generator : k⟦X⟧) :=
  julia_identity (generator : k⟦X⟧) endpoint flow

end Field

end FormalAutonomousFlow
