import Mathlib.Analysis.Calculus.Deriv.Comp
import Mathlib.Algebra.Polynomial.Derivative
import Mathlib.Tactic

/-!
# Cross-Julia elimination for two polynomial autonomous factors

For endpoint maps `inner` and `outer` generated by polynomial vector fields
`f` and `g`, the two Julia identities and the chain rule eliminate both
spatial derivative factors.  The hidden inner endpoint is then a root of an
explicit polynomial.  A coefficient determinant witnessing that `f` and `g`
are not proportional proves that this polynomial is nonzero wherever
`g(outer(inner(x)))` is nonzero.

The module proves the eliminant and its nonzeroness.  It does not infer a
Newton--Puiseux parameterization from the pointwise root relation.
-/

namespace FormalPolynomialCrossJuliaElimination

open Polynomial

/-- The cross-Julia polynomial in the hidden inner endpoint value. -/
noncomputable def crossJuliaPolynomial
    (f g : ℂ[X]) (endpointValue endpointDerivative sourceValue : ℂ) :
    ℂ[X] :=
  C (g.eval endpointValue) * f -
    C (endpointDerivative * f.eval sourceValue) * g

/-- The two Julia identities and the chain rule eliminate the derivatives of
the individual factors. -/
theorem cross_julia_identity
    (f g : ℂ[X]) (inner outer : ℂ → ℂ) (x innerDerivative outerDerivative : ℂ)
    (hinnerDerivative : HasDerivAt inner innerDerivative x)
    (houterDerivative : HasDerivAt outer outerDerivative (inner x))
    (hinnerJulia : f.eval (inner x) = innerDerivative * f.eval x)
    (houterJulia :
      g.eval (outer (inner x)) = outerDerivative * g.eval (inner x)) :
    g.eval (outer (inner x)) * f.eval (inner x) =
      deriv (outer ∘ inner) x * f.eval x * g.eval (inner x) := by
  have hcompositionDerivative :
      deriv (outer ∘ inner) x = outerDerivative * innerDerivative := by
    exact (houterDerivative.comp x hinnerDerivative).deriv
  rw [hinnerJulia, houterJulia, hcompositionDerivative]
  ring

/-- The hidden inner endpoint is a root of the cross-Julia polynomial. -/
theorem crossJuliaPolynomial_eval_inner
    (f g : ℂ[X]) (inner outer : ℂ → ℂ) (x innerDerivative outerDerivative : ℂ)
    (hinnerDerivative : HasDerivAt inner innerDerivative x)
    (houterDerivative : HasDerivAt outer outerDerivative (inner x))
    (hinnerJulia : f.eval (inner x) = innerDerivative * f.eval x)
    (houterJulia :
      g.eval (outer (inner x)) = outerDerivative * g.eval (inner x)) :
    (crossJuliaPolynomial f g (outer (inner x))
      (deriv (outer ∘ inner) x) x).eval (inner x) = 0 := by
  rw [show (crossJuliaPolynomial f g (outer (inner x))
      (deriv (outer ∘ inner) x) x).eval (inner x) =
        g.eval (outer (inner x)) * f.eval (inner x) -
          deriv (outer ∘ inner) x * f.eval x * g.eval (inner x) by
    simp [crossJuliaPolynomial]]
  exact sub_eq_zero.mpr <|
    cross_julia_identity f g inner outer x innerDerivative outerDerivative
      hinnerDerivative houterDerivative hinnerJulia houterJulia

/-- A coefficient determinant of the cross-Julia polynomial cancels its
derivative-dependent scalar and retains the generator nonproportionality
witness. -/
theorem crossJuliaPolynomial_coefficient_determinant
    (f g : ℂ[X]) (endpointValue endpointDerivative sourceValue : ℂ)
    (i j : ℕ) :
    (crossJuliaPolynomial f g endpointValue endpointDerivative sourceValue).coeff i *
          g.coeff j -
        (crossJuliaPolynomial f g endpointValue endpointDerivative sourceValue).coeff j *
          g.coeff i =
      g.eval endpointValue *
        (f.coeff i * g.coeff j - f.coeff j * g.coeff i) := by
  simp only [crossJuliaPolynomial, coeff_sub, coeff_C_mul]
  ring

/-- An explicit coefficient determinant witnessing nonproportionality makes
the cross-Julia polynomial nonzero at every endpoint where `g` is nonzero. -/
theorem crossJuliaPolynomial_ne_zero_of_coefficient_determinant
    (f g : ℂ[X]) (endpointValue endpointDerivative sourceValue : ℂ)
    (i j : ℕ)
    (hdeterminant :
      f.coeff i * g.coeff j - f.coeff j * g.coeff i ≠ 0)
    (hendpoint : g.eval endpointValue ≠ 0) :
    crossJuliaPolynomial f g endpointValue endpointDerivative sourceValue ≠ 0 := by
  intro hzero
  have hdet := crossJuliaPolynomial_coefficient_determinant
    f g endpointValue endpointDerivative sourceValue i j
  exact (mul_ne_zero hendpoint hdeterminant) <| by
    rw [← hdet, hzero]
    simp

/-- Aggregated kernel surface: outside the proportional coefficient locus,
the hidden inner endpoint satisfies a derived nonzero polynomial equation. -/
theorem polynomial_cross_julia_elimination_terminal_certificate :
    ∀ (f g : ℂ[X]) (inner outer : ℂ → ℂ)
      (x innerDerivative outerDerivative : ℂ) (i j : ℕ),
      HasDerivAt inner innerDerivative x →
      HasDerivAt outer outerDerivative (inner x) →
      f.eval (inner x) = innerDerivative * f.eval x →
      g.eval (outer (inner x)) = outerDerivative * g.eval (inner x) →
      f.coeff i * g.coeff j - f.coeff j * g.coeff i ≠ 0 →
      g.eval (outer (inner x)) ≠ 0 →
      g.eval (outer (inner x)) * f.eval (inner x) =
          deriv (outer ∘ inner) x * f.eval x * g.eval (inner x) ∧
        (crossJuliaPolynomial f g (outer (inner x))
          (deriv (outer ∘ inner) x) x).eval (inner x) = 0 ∧
        crossJuliaPolynomial f g (outer (inner x))
          (deriv (outer ∘ inner) x) x ≠ 0 := by
  intro f g inner outer x innerDerivative outerDerivative i j
    hinnerDerivative houterDerivative hinnerJulia houterJulia
    hdeterminant hendpoint
  exact ⟨
    cross_julia_identity f g inner outer x innerDerivative outerDerivative
      hinnerDerivative houterDerivative hinnerJulia houterJulia,
    crossJuliaPolynomial_eval_inner f g inner outer x
      innerDerivative outerDerivative hinnerDerivative houterDerivative
      hinnerJulia houterJulia,
    crossJuliaPolynomial_ne_zero_of_coefficient_determinant f g
      (outer (inner x)) (deriv (outer ∘ inner) x) x i j
      hdeterminant hendpoint⟩

end FormalPolynomialCrossJuliaElimination
