import Mathlib.Tactic
import ZtareProofs.ns_discrete_recurrence_map

namespace ZtareProofs

/-!
`ns_fractional_dwell_bridge` records the post-Phase-5DB correction.

The static anisotropic fractional bridge tried to use metric collapse as a
pointwise pressure-Hessian cap. The ZTARE fractional-bridge audit falsified
that shortcut: the Euclidean projected pressure channel need not decay.

The remaining proof object is time-integrated. A high-normal pressure packet
must be multiplied by its effective dwell/lifetime, and by any material
resupply count. This file is an unbuilt theorem cage for that corrected object.
-/

/-- Abstract number of effective high-normal pressure packets regenerated
during a danger visit. -/
def ResupplyCount := Real → Real

/-- Abstract pointwise projected pressure-production cap. -/
def PressureRateCap := Real → Real

/-- Abstract effective lifetime/dwell of a single high-normal packet. -/
def PressureLifetime := Real → Real

/-- Dwell-renormalized pressure impulse cap. -/
def pressureDwellCap
    (N : ResupplyCount) (P : PressureRateCap) (τ : PressureLifetime) : cycleGain :=
  fun E => N E * P E * τ E

/-- Actual danger gain is bounded by the dwell-renormalized pressure impulse. -/
def gainBoundedByPressureDwell
    (G : cycleGain) (N : ResupplyCount) (P : PressureRateCap)
    (τ : PressureLifetime) : Prop :=
  ∀ E : Real, G E ≤ pressureDwellCap N P τ E

/-- Reset/exhaust loss dominates the dwell-renormalized pressure impulse. -/
def lossDominatesPressureDwell
    (L : cycleLoss) (N : ResupplyCount) (P : PressureRateCap)
    (τ : PressureLifetime) : Prop :=
  ∀ E : Real, pressureDwellCap N P τ E ≤ L E

/--
If danger gain is bounded by the dwell-renormalized pressure channel and reset
loss dominates that channel, the recurrence generated by `G,L` is non-expanding.
-/
theorem nonexpanding_of_pressure_dwell_bridge
    {Φ : CycleMap} {G : cycleGain} {L : cycleLoss}
    {N : ResupplyCount} {P : PressureRateCap} {τ : PressureLifetime}
    {EStar : Real}
    (hΦ : Φ = recurrenceFromGainLoss G L)
    (hGain : gainBoundedByPressureDwell G N P τ)
    (hLoss : lossDominatesPressureDwell L N P τ) :
    nonexpandingAbove Φ EStar := by
  intro E hE
  rw [hΦ]
  unfold recurrenceFromGainLoss
  have hG : G E ≤ pressureDwellCap N P τ E := hGain E
  have hL : pressureDwellCap N P τ E ≤ L E := hLoss E
  linarith

/--
Strict version: if loss beats the dwell-renormalized pressure channel by a
positive margin above threshold, recurrence is contractive there.
-/
def lossStrictlyDominatesPressureDwellAbove
    (L : cycleLoss) (N : ResupplyCount) (P : PressureRateCap)
    (τ : PressureLifetime) (EStar : Real) : Prop :=
  ∀ ⦃E : Real⦄, EStar ≤ E → pressureDwellCap N P τ E < L E

theorem contractive_of_pressure_dwell_bridge
    {Φ : CycleMap} {G : cycleGain} {L : cycleLoss}
    {N : ResupplyCount} {P : PressureRateCap} {τ : PressureLifetime}
    {EStar : Real}
    (hΦ : Φ = recurrenceFromGainLoss G L)
    (hGain : gainBoundedByPressureDwell G N P τ)
    (hLoss : lossStrictlyDominatesPressureDwellAbove L N P τ EStar) :
    contractiveAbove Φ EStar := by
  intro E hE
  rw [hΦ]
  unfold recurrenceFromGainLoss
  have hG : G E ≤ pressureDwellCap N P τ E := hGain E
  have hL : pressureDwellCap N P τ E < L E := hLoss hE
  linarith

/--
Target-shape statement for the no-resupply / viscous-erasure side.  The PDE
must provide the two premises; this theorem only connects them to the existing
recurrence spine.
-/
theorem pressure_dwell_exhaust_target_shape
    {Φ : CycleMap} {G : cycleGain} {L : cycleLoss}
    {N : ResupplyCount} {P : PressureRateCap} {τ : PressureLifetime}
    {EStar : Real}
    (hΦ : Φ = recurrenceFromGainLoss G L)
    (hGain : gainBoundedByPressureDwell G N P τ)
    (hLoss : lossDominatesPressureDwell L N P τ) :
    nonexpandingAbove Φ EStar :=
  nonexpanding_of_pressure_dwell_bridge hΦ hGain hLoss

/--
Ratchet-side witness shape: a profitable return ladder must beat the
dwell-renormalized cap, not only the pointwise pressure rate.  This is kept as
the exact inequality target rather than asserting it from NS.
-/
def pressureDwellRatchetWitness
    (G : cycleGain) (L : cycleLoss)
    (N : ResupplyCount) (P : PressureRateCap) (τ : PressureLifetime)
    (E : Real) : Prop :=
  L E < G E ∧ pressureDwellCap N P τ E < G E

end ZtareProofs
