import Mathlib.Tactic

/-!
# Low-beat operator norm receipt

Phase 5IP/5IQ isolate a small deterministic charge behind the coherent beat
falsifier.

If a high-high pair produces a unit low-frequency beat through a bilinear
operator with norm at most `opBound`, then any Sobolev reserve whose quadratic
AM-GM weight is `weightedProduct` must pay at least
`2 * weightedProduct / opBound`.

The first loose envelope uses `opBound = |k| + |l|`.  The stronger
incompressible low-beat envelope uses the exact symbol collapse

```text
a + b = q,  A.a = 0,  B.b = 0
  => A.b = A.q and B.a = B.q,
  => P_q N_q = P_q((A.q)B + (B.q)A).
```

Thus the low-beat multiplier is controlled by the output frequency `|q|`, not
by the high shell.  The PDE obligation is to instantiate these scalar receipts
inside a fixed Littlewood-Paley/Bony topology and then prove component
lower-semicontinuity.
-/

namespace ZtareProofs.NS

noncomputable section

/-- Abstract receipt for one low-frequency beat generated by two high modes.

`ampProduct` is the product of the two high-mode amplitudes.  `beatOutput` is
the low beat being requested.  `reservePrice` is a predeclared Sobolev/viscous
reserve price; it is not selected after observing the beat payoff. -/
structure LowBeatOperatorNormReceipt where
  beatOutput : Real
  ampProduct : Real
  opBound : Real
  weightedProduct : Real
  reservePrice : Real
  unit_beat_requested : 1 ≤ beatOutput
  op_bound_positive : 0 < opBound
  weighted_product_nonnegative : 0 ≤ weightedProduct
  operator_bound : beatOutput ≤ opBound * ampProduct
  reserve_amgm_bound : 2 * weightedProduct * ampProduct ≤ reservePrice

/-- Multiplicative lower-envelope form.  Avoiding division is useful when this
receipt is composed with shell-prefix estimates. -/
theorem low_beat_operator_norm_price_lower_bound_mul
    (R : LowBeatOperatorNormReceipt) :
    2 * R.weightedProduct ≤ R.opBound * R.reservePrice := by
  have hop_nonneg : 0 ≤ R.opBound := le_of_lt R.op_bound_positive
  have hbeat_to_amp : 1 ≤ R.opBound * R.ampProduct :=
    le_trans R.unit_beat_requested R.operator_bound
  have hreserve_scaled :
      R.opBound * (2 * R.weightedProduct * R.ampProduct) ≤
        R.opBound * R.reservePrice :=
    mul_le_mul_of_nonneg_left R.reserve_amgm_bound hop_nonneg
  nlinarith [hbeat_to_amp, hreserve_scaled, R.weighted_product_nonnegative]

/-- Division form of the same unit low-beat reserve price. -/
theorem low_beat_operator_norm_price_lower_bound
    (R : LowBeatOperatorNormReceipt) :
    (2 * R.weightedProduct) / R.opBound ≤ R.reservePrice := by
  have hmul : 2 * R.weightedProduct ≤ R.opBound * R.reservePrice :=
    low_beat_operator_norm_price_lower_bound_mul R
  have hop_pos : 0 < R.opBound := R.op_bound_positive
  rw [div_le_iff₀ hop_pos]
  nlinarith

/-- Incompressible low-beat collapse:
if the bilinear low-beat operator is bounded by twice the output frequency,
then a unit low beat pays at least `weightedProduct / outputFreq`.

For high modes `a+b=q`, divergence-free amplitudes give
`A.b=A.q` and `B.a=B.q`; this is the structural improvement over the loose
`|a|+|b|` derivative bound. -/
theorem low_beat_incompressible_symbol_price_lower_bound
    (R : LowBeatOperatorNormReceipt)
    {outputFreq : Real}
    (hfreq : 0 < outputFreq)
    (hopCollapse : R.opBound ≤ 2 * outputFreq) :
    R.weightedProduct / outputFreq ≤ R.reservePrice := by
  have hmain : (2 * R.weightedProduct) / R.opBound ≤ R.reservePrice :=
    low_beat_operator_norm_price_lower_bound R
  have hop_pos : 0 < R.opBound := R.op_bound_positive
  have hleft :
      R.weightedProduct / outputFreq ≤
        (2 * R.weightedProduct) / R.opBound := by
    rw [div_le_div_iff₀ hfreq hop_pos]
    nlinarith [R.weighted_product_nonnegative, hopCollapse]
  exact le_trans hleft hmain

/-- Fixed-output-frequency high-shell form.

If the Sobolev weight for the two high modes is at least
`outputFreq * shellReserve`, then the incompressible symbol receipt forces the
reserve price to dominate `shellReserve`.  In applications with fixed low
`q`, `shellReserve` is the high-shell growth such as `N^2` for vorticity
reserve or `N^4` for grad-vorticity reserve. -/
theorem low_beat_fixed_output_shell_reserve_lower_bound
    (R : LowBeatOperatorNormReceipt)
    {outputFreq shellReserve : Real}
    (hfreq : 0 < outputFreq)
    (hopCollapse : R.opBound ≤ 2 * outputFreq)
    (hshell : outputFreq * shellReserve ≤ R.weightedProduct) :
    shellReserve ≤ R.reservePrice := by
  have hprice :
      R.weightedProduct / outputFreq ≤ R.reservePrice :=
    low_beat_incompressible_symbol_price_lower_bound
      R hfreq hopCollapse
  have hshell_div : shellReserve ≤ R.weightedProduct / outputFreq := by
    rw [le_div_iff₀ hfreq]
    nlinarith
  exact le_trans hshell_div hprice

/-- A dyadic coherent beat schedule cannot keep the declared reserve bounded
if its required unit-beat lower envelopes have unbounded prefixes.

This is the sequence-space handoff from Phase 5IL/5IN/5IP/5IQ:
branch-square pricing alone misses coherent `b_j = 1/j` accumulation, but a
declared physical reserve must at least dominate the unit-beat envelopes. -/
structure LowBeatPrefixReserveStream where
  prefixBeatPayoff : ℕ → Real
  prefixReservePrice : ℕ → Real
  prefixEnvelope : ℕ → Real
  declared_topology_before_payoff : Prop
  declared_topology_before_payoff_paid :
    declared_topology_before_payoff
  reserve_declared_before_payoff : Prop
  reserve_declared_before_payoff_paid :
    reserve_declared_before_payoff
  no_posthoc_low_beat_stream_substitution : Prop
  no_posthoc_low_beat_stream_substitution_paid :
    no_posthoc_low_beat_stream_substitution
  envelope_charged :
    ∀ n, prefixEnvelope n ≤ prefixReservePrice n
  payoff_charged_by_reserve :
    ∀ n, prefixBeatPayoff n ≤ prefixReservePrice n

/-- Which fixed-before-payoff guard failed for the low-beat prefix reserve
stream. -/
inductive LowBeatPrefixReserveGuardBranch where
  | topologyDeclared
  | reserveDeclared
  | noPosthocStreamSubstitution
deriving DecidableEq, Repr

/-- Concrete falsifier for a low-beat prefix stream whose scalar reserve was
not actually fixed before payoff scoring. -/
structure LowBeatPrefixReserveGuardFalsifier
    (S : LowBeatPrefixReserveStream) where
  branch : LowBeatPrefixReserveGuardBranch
  missing :
    match branch with
    | LowBeatPrefixReserveGuardBranch.topologyDeclared =>
        ¬ S.declared_topology_before_payoff
    | LowBeatPrefixReserveGuardBranch.reserveDeclared =>
        ¬ S.reserve_declared_before_payoff
    | LowBeatPrefixReserveGuardBranch.noPosthocStreamSubstitution =>
        ¬ S.no_posthoc_low_beat_stream_substitution

/-- A guarded low-beat stream excludes missing-declaration and posthoc
stream-substitution falsifiers. -/
theorem no_low_beat_prefix_reserve_guard_falsifier
    (S : LowBeatPrefixReserveStream)
    (F : LowBeatPrefixReserveGuardFalsifier S) :
    False := by
  rcases F with ⟨branch, hmissing⟩
  cases branch with
  | topologyDeclared =>
      exact hmissing S.declared_topology_before_payoff_paid
  | reserveDeclared =>
      exact hmissing S.reserve_declared_before_payoff_paid
  | noPosthocStreamSubstitution =>
      exact hmissing S.no_posthoc_low_beat_stream_substitution_paid

/-- If the beat payoff is unbounded through prefixes, no finite reserve limit
can charge it. -/
theorem no_finite_low_beat_reserve_limit_of_unbounded_payoff
    (S : LowBeatPrefixReserveStream)
    {reserveLimit : Real}
    (hbounded : ∀ n, S.prefixReservePrice n ≤ reserveLimit)
    (hunbounded : ∀ B : Real, ∃ n, B < S.prefixBeatPayoff n) :
    False := by
  rcases hunbounded reserveLimit with ⟨n, hn⟩
  have hpay : S.prefixBeatPayoff n ≤ reserveLimit :=
    le_trans (S.payoff_charged_by_reserve n) (hbounded n)
  exact not_lt_of_ge hpay hn

end

end ZtareProofs.NS
