import Mathlib.Tactic
import ZtareProofs.ns_low_high_lipschitz_reserve_adapter
import ZtareProofs.ns_profile_lipschitz_clay_bridge

/-!
# Low-high fixed-topology receipt composed with Track B profile/Lipschitz closure

This file is intentionally only a composition layer.  It takes the generated
low-frequency Lipschitz ledger from `TrackBProfileLipschitzControlObligation` and
routes existing fixed-topology low-high receipts into that exact ledger.

The point is to prevent a low-high escape from changing topology, observable
class, shell index, or reserve entry after payoff is observed: the local
LP/Bony receipt and reserve link are fixed first, then the profile decomposition
and Lipschitz bridge price the generated ledger block.
-/

namespace ZtareProofs.NS

noncomputable section

/-- The low-frequency Lipschitz ledger generated by the composed Track B Clay
obligation for one smooth initial datum. -/
def trackBGeneratedLowFrequencyLipschitzLedger
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData) :
    LowFrequencyLipschitzLedger :=
  O.lipschitz_bridge.ledger_of_evolution
    (O.evolution_of_initial_data u0)

/-- The control certificate attached to the generated Lipschitz ledger. -/
def trackBGeneratedLowFrequencyLipschitzCertificate
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData) :
    LowFrequencyLipschitzControlCertificate
      (trackBGeneratedLowFrequencyLipschitzLedger O u0) := by
  unfold trackBGeneratedLowFrequencyLipschitzLedger
  exact O.lipschitz_bridge.certificate_of_evolution
    (O.evolution_of_initial_data u0)

/-- The audited control certificate attached to the generated Lipschitz
ledger.

The legacy certificate above is retained for older adapters, but final closure
routes should prefer this source-preserving certificate whenever they need the
continuation/BKM guard provenance. -/
def trackBGeneratedLowFrequencyLipschitzAuditedCertificate
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData) :
    LowFrequencyLipschitzAuditedControlCertificate
      (trackBGeneratedLowFrequencyLipschitzLedger O u0) := by
  unfold trackBGeneratedLowFrequencyLipschitzLedger
  exact O.lipschitz_bridge.audited_certificate_of_evolution
    (O.evolution_of_initial_data u0)

/-- The legacy generated Lipschitz certificate is the forgetful projection of
the audited certificate, so older low-high adapters cannot consume a detached
continuation source. -/
theorem trackBGeneratedLowFrequencyLipschitzCertificate_eq_audited_toControlCertificate
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData) :
    trackBGeneratedLowFrequencyLipschitzCertificate O u0 =
      (trackBGeneratedLowFrequencyLipschitzAuditedCertificate
        O u0).toControlCertificate := by
  rfl

/-- The generated Lipschitz block is ready both for branch pricing and for the
threshold-defect handoff, with both receipts attached to the same generated
block. -/
def TrackBGeneratedLipschitzBlockProfileHandoffReady
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (n : ℕ) : Prop :=
  TrackBProfileLipschitzGeneratedBlockHandoffSourceReady O u0 n

/-- The Track B profile/Lipschitz source receipts produce the stronger
generated-block handoff package consumed by the composition layer. -/
theorem trackB_generated_lipschitz_block_profile_handoff_ready
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (n : ℕ) :
    TrackBGeneratedLipschitzBlockProfileHandoffReady O u0 n := by
  exact
    trackB_profile_lipschitz_generated_block_handoff_source_ready
      O u0 n

/-- A generated block no-survivor proof that explicitly consumes both the
branch-source readiness and the threshold-handoff source receipt for the same
generated Lipschitz block. -/
theorem generated_lipschitz_block_no_survivor_of_trackB_profile_handoff_ready
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (n : ℕ)
    (hready :
      TrackBGeneratedLipschitzBlockProfileHandoffReady O u0 n) :
    FullLedgerNoSurvivor
      ((trackBGeneratedLowFrequencyLipschitzLedger O u0).block n) := by
  unfold trackBGeneratedLowFrequencyLipschitzLedger
  let U := O.evolution_of_initial_data u0
  let L := O.lipschitz_bridge.ledger_of_evolution U
  let B := L.block n
  have hthresholds :=
    threshold_defects_of_trackB_profile_lipschitz_generated_block_handoff_source
      O u0 n hready
  exact full_ledger_no_survivor_of_quartic_survival_projection
    B
    (O.generated_quartic_survival_projection U n)
    hthresholds.2.2.2

/-- Source-ready generated Lipschitz blocks are no-survivor once the fixed
profile decomposition and quartic pricing obligation are supplied.

The explicit `hsource` premise prevents this theorem from being used with a
posthoc profile family or a quartic projection detached from the generated
Lipschitz block. -/
theorem generated_lipschitz_block_no_survivor_of_trackB_profile_source_ready
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (n : ℕ)
    (hsource :
      TrackBProfileLipschitzGeneratedBlockSourceReady O u0 n) :
    FullLedgerNoSurvivor
      ((trackBGeneratedLowFrequencyLipschitzLedger O u0).block n) := by
  exact generated_lipschitz_block_no_survivor_of_trackB_profile_handoff_ready
    O u0 n
    ⟨hsource,
      trackB_profile_lipschitz_generated_block_threshold_handoff_source_ready
        O u0 n⟩

/-- Every block of the generated Lipschitz ledger is no-survivor once the fixed
profile decomposition, source coupling, and quartic pricing obligation are
supplied. -/
theorem generated_lipschitz_block_no_survivor_of_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (n : ℕ) :
    FullLedgerNoSurvivor
      ((trackBGeneratedLowFrequencyLipschitzLedger O u0).block n) :=
  generated_lipschitz_block_no_survivor_of_trackB_profile_handoff_ready
    O u0 n
    (trackB_generated_lipschitz_block_profile_handoff_ready O u0 n)

/-- Family form of generated no-survivor pricing. -/
theorem generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData) :
    ∀ n : ℕ,
      FullLedgerNoSurvivor
        ((trackBGeneratedLowFrequencyLipschitzLedger O u0).block n) := by
  intro n
  exact generated_lipschitz_block_no_survivor_of_trackB_profile_closure
    O u0 n

/-- A generated Track B low-high reserve link with a paid anti-tautology
receipt excludes the corresponding metadata-failure falsifier.

This is intentionally only a routing theorem: it makes the link receipt
load-bearing for generated profile/Lipschitz ledgers without adding a new
low-high estimate. -/
theorem no_low_high_lipschitz_reserve_link_anti_tautology_falsifier_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (L : LowHighKinematicDichotomyLedger)
    (R : LowHighLPBonyUnpaidEstimateReceipt L)
    (n : ℕ)
    (link :
      LowHighLipschitzReserveLink L R
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) n)
    (link_receipt : LowHighReserveLinkAntiTautologyReceipt link)
    (F : LowHighReserveLinkAntiTautologyFalsifier link) :
    False :=
  no_low_high_lipschitz_reserve_link_of_anti_tautology_falsifier
    L R (trackBGeneratedLowFrequencyLipschitzLedger O u0) n
    link link_receipt F

/-- A fixed-topology low-high local operator receipt is priced when its
predeclared reserve link lands in the generated Track B profile/Lipschitz
ledger. -/
theorem low_high_no_arbitrage_of_fixed_topology_receipt_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (L : LowHighKinematicDichotomyLedger)
    (R : FixedTopologyLowHighOperatorReceipt L)
    (n : ℕ)
    (link :
      LowHighLipschitzReserveLink L
        (unpaid_lp_bony_receipt_of_operator_reality_check L
          (operator_reality_check_of_fixed_topology_receipt L R))
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) n)
    (link_receipt : LowHighReserveLinkAntiTautologyReceipt link) :
    InteractionNoArbitrage L.interaction := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have _hlink_source :
      link.cost_identity_declared_before_payoff ∧
        link.reserve_identity_declared_before_payoff ∧
          link.same_lp_bony_topology :=
    ⟨link_receipt.cost_identity_paid,
      link_receipt.reserve_identity_paid,
      link_receipt.same_topology_paid⟩
  have hnosurvivor : FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_block_no_survivor_of_trackB_profile_closure
      O u0 n
  exact low_high_no_arbitrage_of_fixed_topology_operator_receipt
    L R G C n link hnosurvivor

/-- The same composition in the full fixed-topology form, including the
predeclared finite low-shell core receipt. -/
theorem low_high_no_arbitrage_of_full_fixed_topology_receipt_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (L : LowHighKinematicDichotomyLedger)
    (R : FullFixedTopologyLowHighOperatorReceipt L)
    (n : ℕ)
    (link :
      LowHighLipschitzReserveLink L
        (unpaid_lp_bony_receipt_of_operator_reality_check L
          (operator_reality_check_of_fixed_topology_receipt L
            R.highShellReceipt))
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) n)
    (link_receipt : LowHighReserveLinkAntiTautologyReceipt link) :
    InteractionNoArbitrage L.interaction := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have _hlink_source :
      link.cost_identity_declared_before_payoff ∧
        link.reserve_identity_declared_before_payoff ∧
          link.same_lp_bony_topology :=
    ⟨link_receipt.cost_identity_paid,
      link_receipt.reserve_identity_paid,
      link_receipt.same_topology_paid⟩
  have hnosurvivor : FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_block_no_survivor_of_trackB_profile_closure
      O u0 n
  exact low_high_no_arbitrage_of_full_fixed_topology_operator_receipt
    L R G C n link hnosurvivor

/-- Fixed-topology low-high pricing under the generated Track B ledger rules
out a same-ledger bilinear reserve shortfall. -/
theorem no_low_high_fixed_topology_bilinear_escape_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (L : LowHighKinematicDichotomyLedger)
    (R : FixedTopologyLowHighOperatorReceipt L)
    (n : ℕ)
    (link :
      LowHighLipschitzReserveLink L
        (unpaid_lp_bony_receipt_of_operator_reality_check L
          (operator_reality_check_of_fixed_topology_receipt L R))
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) n)
    (link_receipt : LowHighReserveLinkAntiTautologyReceipt link)
    (F : LowHighBilinearChargeFalsifier L) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have _hlink_source :
      link.cost_identity_declared_before_payoff ∧
        link.reserve_identity_declared_before_payoff ∧
          link.same_lp_bony_topology :=
    ⟨link_receipt.cost_identity_paid,
      link_receipt.reserve_identity_paid,
      link_receipt.same_topology_paid⟩
  have hnosurvivor : FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_block_no_survivor_of_trackB_profile_closure
      O u0 n
  exact no_low_high_fixed_topology_operator_receipt_with_bilinear_falsifier
    L R G C n link hnosurvivor F

/-- Full fixed-topology low-high pricing under the generated Track B ledger
rules out the corresponding same-ledger bilinear reserve shortfall. -/
theorem no_low_high_full_fixed_topology_bilinear_escape_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (L : LowHighKinematicDichotomyLedger)
    (R : FullFixedTopologyLowHighOperatorReceipt L)
    (n : ℕ)
    (link :
      LowHighLipschitzReserveLink L
        (unpaid_lp_bony_receipt_of_operator_reality_check L
          (operator_reality_check_of_fixed_topology_receipt L
            R.highShellReceipt))
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) n)
    (link_receipt : LowHighReserveLinkAntiTautologyReceipt link)
    (F : LowHighBilinearChargeFalsifier L) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have _hlink_source :
      link.cost_identity_declared_before_payoff ∧
        link.reserve_identity_declared_before_payoff ∧
          link.same_lp_bony_topology :=
    ⟨link_receipt.cost_identity_paid,
      link_receipt.reserve_identity_paid,
      link_receipt.same_topology_paid⟩
  have hnosurvivor : FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_block_no_survivor_of_trackB_profile_closure
      O u0 n
  exact no_low_high_full_fixed_topology_operator_receipt_with_bilinear_falsifier
    L R G C n link hnosurvivor F

/-- Explicit-commutator fixed-topology receipt composed with the generated
Track B profile/Lipschitz ledger. -/
theorem low_high_no_arbitrage_of_commutator_receipt_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (L : LowHighKinematicDichotomyLedger)
    (R : FixedTopologyLowHighOperatorReceiptWithCommutator L)
    (n : ℕ)
    (link :
      LowHighLipschitzReserveLink L
        (unpaid_lp_bony_receipt_of_operator_reality_check L
          (operator_reality_check_of_fixed_topology_receipt L R.base))
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) n)
    (link_receipt : LowHighReserveLinkAntiTautologyReceipt link) :
    InteractionNoArbitrage L.interaction := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have _hlink_source :
      link.cost_identity_declared_before_payoff ∧
        link.reserve_identity_declared_before_payoff ∧
          link.same_lp_bony_topology :=
    ⟨link_receipt.cost_identity_paid,
      link_receipt.reserve_identity_paid,
      link_receipt.same_topology_paid⟩
  have hnosurvivor : FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_block_no_survivor_of_trackB_profile_closure
      O u0 n
  exact low_high_no_arbitrage_of_fixed_topology_commutator_receipt
    L R G C n link hnosurvivor

/-- Geometry-only low-high LP/Bony energy budget composed with the generated
Track B profile/Lipschitz ledger.

This is the PDE-facing route that avoids using the paid
`ContinuumLowHighDeformationLift` as a hidden reserve assumption.  The local
estimate is only the standard transport/stretch/separation energy-form bound;
the global conclusion appears only after the exact budget cost is linked into
the generated low-frequency Lipschitz ledger and that ledger entry is priced by
the no-survivor block. -/
theorem low_high_no_arbitrage_of_energy_budget_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (L : LowHighKinematicDichotomyLedger)
    (R : FixedTopologyLowHighEnergyBudgetReceipt L)
    (n : ℕ)
    (link :
      LowHighEnergyBudgetReserveLink L R
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) n) :
    InteractionNoArbitrage L.interaction := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have hnosurvivor : FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_block_no_survivor_of_trackB_profile_closure
      O u0 n
  exact low_high_no_arbitrage_of_energy_budget_reserve_link
    L R G C n link hnosurvivor

/-- Receipt-strengthened geometry-only low-high energy-budget route.

This is the non-tautological variant downstream closure code should prefer:
the exact cost/reserve/topology/positive-energy-pairing declarations are paid
before the generated Track B ledger prices the linked entry. -/
theorem low_high_no_arbitrage_of_energy_budget_with_receipt_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (L : LowHighKinematicDichotomyLedger)
    (R : FixedTopologyLowHighEnergyBudgetReceipt L)
    (n : ℕ)
    (link :
      LowHighEnergyBudgetReserveLink L R
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) n)
    (link_receipt :
      LowHighEnergyBudgetReserveLinkAntiTautologyReceipt link) :
    InteractionNoArbitrage L.interaction := by
  have _hlink_source :
      link.cost_identity_declared_before_payoff ∧
        link.reserve_identity_declared_before_payoff ∧
          link.same_fixed_lp_bony_topology ∧
            link.same_positive_energy_pairing_observable :=
    ⟨link_receipt.cost_identity_paid,
      link_receipt.reserve_identity_paid,
      link_receipt.same_topology_paid,
      link_receipt.same_positive_energy_pairing_observable_paid⟩
  exact
    low_high_no_arbitrage_of_energy_budget_under_trackB_profile_closure
      O u0 L R n link

/-- A generated Track B geometry-only energy-budget reserve link with a paid
anti-tautology receipt excludes the corresponding source-metadata falsifier. -/
theorem no_low_high_energy_budget_reserve_link_anti_tautology_falsifier_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (L : LowHighKinematicDichotomyLedger)
    (R : FixedTopologyLowHighEnergyBudgetReceipt L)
    (n : ℕ)
    (link :
      LowHighEnergyBudgetReserveLink L R
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) n)
    (link_receipt :
      LowHighEnergyBudgetReserveLinkAntiTautologyReceipt link)
    (F : LowHighEnergyBudgetReserveLinkAntiTautologyFalsifier link) :
    False :=
  no_low_high_energy_budget_reserve_link_of_anti_tautology_falsifier
    L R (trackBGeneratedLowFrequencyLipschitzLedger O u0) n
    link link_receipt F

/-- A same-ledger low-high reserve shortfall cannot survive the geometry-only
LP/Bony energy-budget route once the exact cost is embedded into the generated
Track B Lipschitz ledger. -/
theorem no_low_high_energy_budget_escape_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (L : LowHighKinematicDichotomyLedger)
    (R : FixedTopologyLowHighEnergyBudgetReceipt L)
    (n : ℕ)
    (link :
      LowHighEnergyBudgetReserveLink L R
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) n)
    (F : LowHighEnergyBudgetReserveShortfallFalsifier L) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have hnosurvivor : FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_block_no_survivor_of_trackB_profile_closure
      O u0 n
  exact no_low_high_energy_budget_reserve_shortfall_of_link
    L R G C n link hnosurvivor F

/-- A shell-family low-high closure linked to the generated Lipschitz ledger
prices every shell interaction. -/
theorem low_high_shell_no_arbitrage_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (j : ℕ) :
    InteractionNoArbitrage (S.shellLedger j).interaction := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact low_high_shell_no_arbitrage_of_reserve_closure
    G C S hnosurvivor j

/-- A same-shell low-high bilinear shortfall is impossible under a shell-family
closure linked to the generated Track B profile/Lipschitz ledger. -/
theorem no_low_high_shell_bilinear_escape_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (j : ℕ)
    (F : LowHighBilinearChargeFalsifier (S.shellLedger j)) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact no_low_high_shell_reserve_closure_with_bilinear_falsifier
    G C S hnosurvivor j F

/-- A finite overbudget low-high shell market-impact prefix breaks the
generated fixed profile/Lipschitz ledger. -/
theorem no_low_high_market_impact_prefix_escape_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (F :
      LowHighShellPrefixReserveFalsifier
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) S) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact no_low_high_shell_reserve_closure_with_prefix_falsifier
    G C S hnosurvivor F

/-- Unbounded low-high shell market-impact prefixes are impossible under the
generated fixed profile/Lipschitz ledger. -/
theorem no_unbounded_low_high_market_impact_prefix_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (hunbounded :
      ∀ B : Real, ∃ N : ℕ, B < nsPrefixSum S.shellCost N) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact no_unbounded_low_high_shell_prefix_of_reserve_closure
    G C S hnosurvivor hunbounded

/-- Shell-cost nonnegativity is inherited by the generated Track B
profile/Lipschitz closure. -/
theorem low_high_shell_cost_nonnegative_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (j : ℕ) :
    0 ≤ S.shellCost j :=
  low_high_shell_cost_nonnegative_of_reserve_closure
    (trackBGeneratedLowFrequencyLipschitzLedger O u0) S j

/-- Pointwise-unbounded low-high shell market-impact costs are impossible under
the generated fixed profile/Lipschitz ledger. -/
theorem no_pointwise_unbounded_low_high_market_impact_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (hunbounded :
      ∀ B : Real, ∃ j : ℕ, B < S.shellCost j) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact no_pointwise_unbounded_low_high_shell_cost_of_reserve_closure
    G C S hnosurvivor hunbounded

/-- A geometry-only shell-family low-high closure linked to the generated
Lipschitz ledger prices every shell interaction. -/
theorem low_high_energy_budget_shell_no_arbitrage_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighEnergyBudgetShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (j : ℕ) :
    InteractionNoArbitrage (S.shellLedger j).interaction := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact low_high_energy_budget_shell_no_arbitrage_of_reserve_closure
    G C S hnosurvivor j

/-- A same-shell reserve shortfall is impossible under the geometry-only
shell-family closure. -/
theorem no_low_high_energy_budget_shell_shortfall_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighEnergyBudgetShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (j : ℕ)
    (F : LowHighEnergyBudgetReserveShortfallFalsifier (S.shellLedger j)) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact
    no_low_high_energy_budget_shell_reserve_closure_with_shortfall_falsifier
      G C S hnosurvivor j F

/-- A finite overbudget geometry-only shell prefix breaks the generated fixed
profile/Lipschitz ledger. -/
theorem no_low_high_energy_budget_market_impact_prefix_escape_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighEnergyBudgetShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (F :
      LowHighEnergyBudgetShellPrefixReserveFalsifier
        (trackBGeneratedLowFrequencyLipschitzLedger O u0) S) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzAuditedCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact no_low_high_energy_budget_shell_reserve_closure_with_audited_prefix_falsifier
    G C S hnosurvivor F

/-- Unbounded geometry-only low-high shell prefixes are impossible under the
generated fixed profile/Lipschitz ledger. -/
theorem no_unbounded_low_high_energy_budget_market_impact_prefix_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighEnergyBudgetShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (hunbounded :
      ∀ B : Real, ∃ N : ℕ, B < nsPrefixSum S.shellBudgetCost N) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzAuditedCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact no_unbounded_low_high_energy_budget_shell_prefix_of_audited_reserve_closure
    G C S hnosurvivor hunbounded

/-- Geometry-only shell-budget nonnegativity is inherited by the generated
Track B profile/Lipschitz closure. -/
theorem low_high_energy_budget_shell_cost_nonnegative_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighEnergyBudgetShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (j : ℕ) :
    0 ≤ S.shellBudgetCost j :=
  low_high_energy_budget_shell_cost_nonnegative_of_reserve_closure
    (trackBGeneratedLowFrequencyLipschitzLedger O u0) S j

/-- Pointwise-unbounded geometry-only shell costs are impossible under the
generated fixed profile/Lipschitz ledger. -/
theorem no_pointwise_unbounded_low_high_energy_budget_market_impact_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      LowHighEnergyBudgetShellReserveClosure
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (hunbounded :
      ∀ B : Real, ∃ j : ℕ, B < S.shellBudgetCost j) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzAuditedCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact no_pointwise_unbounded_low_high_energy_budget_shell_cost_of_audited_reserve_closure
    G C S hnosurvivor hunbounded

/-- The concrete Fourier latency symbol obstruction is priced by the generated
Track B profile/Lipschitz ledger.

This connects the `|k_j| / j` low-high latency read directly to the same
generated low-frequency reserve used by the global closure.  It remains a
routing theorem: the PDE burden is the concrete symbol receipt and its fixed
topology/Leray-output declarations. -/
theorem no_concrete_fourier_latency_symbol_escape_under_trackB_profile_closure
    (O : TrackBProfileLipschitzControlObligation)
    (u0 : SmoothNSInitialData)
    (S :
      ConcreteFourierLatencySymbolReceipt
        (trackBGeneratedLowFrequencyLipschitzLedger O u0))
    (hunbounded :
      ∀ B : Real, ∃ n : ℕ, B < S.shellOverIndex n) :
    False := by
  let G := trackBGeneratedLowFrequencyLipschitzLedger O u0
  let C := trackBGeneratedLowFrequencyLipschitzAuditedCertificate O u0
  have hnosurvivor :
      ∀ n : ℕ, FullLedgerNoSurvivor (G.block n) :=
    generated_lipschitz_blocks_no_survivor_of_trackB_profile_closure
      O u0
  exact no_unbounded_concrete_fourier_latency_symbol_under_audited_no_survivor
    G C S hnosurvivor hunbounded

end

end ZtareProofs.NS
