import Mathlib.Tactic
import ZtareProofs.ns_fractional_dwell_bridge
import ZtareProofs.ns_signed_escape_coordinate

namespace ZtareProofs

/-!
`ns_resupply_escape_pincer` records the post-Phase-5DD theorem object.

The static fractional bridge is dead.  A high-normal Euclidean pressure packet
can be pointwise large, so the remaining question is whether its integrated
impulse is erased by signed escape and viscosity before material recurrence can
resupply it.

This file is intentionally not imported by the umbrella build.  It is a small
unbuilt theorem cage for the corrected proof shape.
-/

/-- Abstract rate at which effective high-normal pressure packets are
regenerated during a danger visit. -/
def ResupplyRate := Real -> Real

/-- Abstract danger-section dwell time. -/
def SectionDwell := Real -> Real

/-- Abstract integrated impulse cap for one high-normal pressure packet. -/
def PacketImpulseCap := Real -> Real

/-- Resupply count is bounded by a rate times the section dwell. -/
def resupplyCountBoundedByRate
    (N : ResupplyCount) (rho : ResupplyRate) (T : SectionDwell) : Prop :=
  forall E : Real, N E <= rho E * T E

/-- A single packet's pressure impulse is bounded by `I`. -/
def packetImpulseBounded
    (P : PressureRateCap) (tau : PressureLifetime) (I : PacketImpulseCap) :
    Prop :=
  forall E : Real, P E * tau E <= I E

/-- The resupply-rate packet impulse is dominated by reset/exhaust loss. -/
def resupplyImpulseDominatedByLoss
    (L : cycleLoss) (rho : ResupplyRate) (T : SectionDwell)
    (I : PacketImpulseCap) : Prop :=
  forall E : Real, rho E * T E * I E <= L E

/--
If packet count is bounded by resupply rate times dwell, one-packet impulse is
bounded by `I`, and the resulting resupply impulse is loss-dominated, then the
older pressure-dwell loss premise follows.
-/
theorem lossDominatesPressureDwell_of_resupply_escape_bounds
    {L : cycleLoss} {N : ResupplyCount} {P : PressureRateCap}
    {tau : PressureLifetime} {rho : ResupplyRate} {T : SectionDwell}
    {I : PacketImpulseCap}
    (hN : resupplyCountBoundedByRate N rho T)
    (hI : packetImpulseBounded P tau I)
    (hDom : resupplyImpulseDominatedByLoss L rho T I)
    (hPNonneg : forall E : Real, 0 <= P E * tau E)
    (hRhoNonneg : forall E : Real, 0 <= rho E * T E) :
    lossDominatesPressureDwell L N P tau := by
  intro E
  unfold pressureDwellCap
  have h1 : N E * (P E * tau E) <= (rho E * T E) * (P E * tau E) := by
    exact mul_le_mul_of_nonneg_right (hN E) (hPNonneg E)
  have h2 : (rho E * T E) * (P E * tau E) <= (rho E * T E) * I E := by
    exact mul_le_mul_of_nonneg_left (hI E) (hRhoNonneg E)
  calc
    N E * P E * tau E = N E * (P E * tau E) := by ring
    _ <= (rho E * T E) * (P E * tau E) := h1
    _ <= (rho E * T E) * I E := h2
    _ <= L E := hDom E

/-- Above-threshold version of gain bounded by dwell-renormalized pressure. -/
def gainBoundedByPressureDwellAbove
    (G : cycleGain) (N : ResupplyCount) (P : PressureRateCap)
    (tau : PressureLifetime) (EStar : Real) : Prop :=
  forall {E : Real}, EStar <= E -> G E <= pressureDwellCap N P tau E

/-- Above-threshold version of loss dominating dwell-renormalized pressure. -/
def lossDominatesPressureDwellAbove
    (L : cycleLoss) (N : ResupplyCount) (P : PressureRateCap)
    (tau : PressureLifetime) (EStar : Real) : Prop :=
  forall {E : Real}, EStar <= E -> pressureDwellCap N P tau E <= L E

/--
Above-threshold pressure-dwell dominance implies nonexpansion of the recurrence
map generated by `G,L`.
-/
theorem nonexpanding_of_pressure_dwell_bridge_above
    {Phi : CycleMap} {G : cycleGain} {L : cycleLoss}
    {N : ResupplyCount} {P : PressureRateCap} {tau : PressureLifetime}
    {EStar : Real}
    (hPhi : Phi = recurrenceFromGainLoss G L)
    (hGain : gainBoundedByPressureDwellAbove G N P tau EStar)
    (hLoss : lossDominatesPressureDwellAbove L N P tau EStar) :
    nonexpandingAbove Phi EStar := by
  intro E hE
  rw [hPhi]
  unfold recurrenceFromGainLoss
  have hG : G E <= pressureDwellCap N P tau E := hGain hE
  have hL : pressureDwellCap N P tau E <= L E := hLoss hE
  linarith

/--
Final pincer shape.  The PDE side must supply the three resupply/packet/loss
premises.  Once it does, the existing recurrence spine is nonexpanding.
-/
theorem nonexpanding_of_resupply_escape_pincer
    {Phi : CycleMap} {G : cycleGain} {L : cycleLoss}
    {N : ResupplyCount} {P : PressureRateCap} {tau : PressureLifetime}
    {rho : ResupplyRate} {T : SectionDwell} {I : PacketImpulseCap}
    {EStar : Real}
    (hPhi : Phi = recurrenceFromGainLoss G L)
    (hGain : gainBoundedByPressureDwell G N P tau)
    (hN : resupplyCountBoundedByRate N rho T)
    (hI : packetImpulseBounded P tau I)
    (hDom : resupplyImpulseDominatedByLoss L rho T I)
    (hPNonneg : forall E : Real, 0 <= P E * tau E)
    (hRhoNonneg : forall E : Real, 0 <= rho E * T E) :
    nonexpandingAbove Phi EStar := by
  exact nonexpanding_of_pressure_dwell_bridge hPhi hGain
    (lossDominatesPressureDwell_of_resupply_escape_bounds
      hN hI hDom hPNonneg hRhoNonneg)

/--
Ratchet-side target: any blowup-facing recurrence has to beat the same pincer,
not merely exhibit a large instantaneous pressure rate.
-/
def resupplyEscapeRatchetWitness
    (G : cycleGain) (L : cycleLoss) (N : ResupplyCount)
    (P : PressureRateCap) (tau : PressureLifetime)
    (rho : ResupplyRate) (T : SectionDwell) (I : PacketImpulseCap)
    (E : Real) : Prop :=
  L E < G E /\
    pressureDwellCap N P tau E < G E /\
    rho E * T E * I E < G E

end ZtareProofs

