import Mathlib.Tactic
import ZtareProofs.ns_ergodic_no_null_lock

namespace ZtareProofs

/-!
`ns_self_generated_pressure_transversality` records the corrected PDE bridge
after the scale-separation objection.

The earlier "global CZ null set is slow, local `-Omega^2` jump is fast" story is
not valid near a putative singularity. The pressure Hessian is self-generated by
the same local high-intensity source that drives the jump. The real obligation
is algebraic: a configuration capable of a large local jump must be transverse
to the null space of its own Riesz-pressure footprint.

This file does not prove that PDE theorem. It names the exact finite-dimensional
projection object that would imply the no-null-lock average bound already used
by the gridlock spine.
-/

/-- Scalar strength of the local advective jump driver, e.g. `omega x S omega`. -/
abbrev LocalJumpDriver := Real

/-- Scalar strength of the self-generated Riesz pressure footprint. -/
abbrev SelfGeneratedPressureFootprint := Real

/--
Self-generated pressure transversality.

If the local jump driver is active above `driverFloor`, then its own pressure
footprint has average projected magnitude at least `pFloor` over the jump
prefix. This replaces the invalid scale-separation route.
-/
def selfGeneratedPressureTransversality
    (driver : LocalJumpDriver)
    (Pseq : ProjectedPressureSequence)
    (N : Nat)
    (driverFloor pFloor : Real) : Prop :=
  driverFloor ≤ |driver| →
    noNullLockAverageLowerBound Pseq N pFloor

/--
Active jump plus self-generated transversality gives the no-null-lock bound.
-/
theorem noNullLock_of_self_generated_pressure_transversality
    {driver : LocalJumpDriver}
    {Pseq : ProjectedPressureSequence}
    {N : Nat}
    {driverFloor pFloor : Real}
    (hactive : driverFloor ≤ |driver|)
    (htrans :
      selfGeneratedPressureTransversality driver Pseq N driverFloor pFloor) :
    noNullLockAverageLowerBound Pseq N pFloor := by
  exact htrans hactive

/--
Self-generated transversality routes into positive total pressure pollution.

This is the corrected replacement for any claim based on slow global null
planes. The lower bound comes from tensor-geometry transversality between the
jump driver and its own Riesz-pressure footprint.
-/
theorem positive_total_pollution_of_self_generated_transversality
    {driver : LocalJumpDriver}
    {Pseq : ProjectedPressureSequence}
    {N : Nat}
    {totalPollution κ driverFloor pFloor : Real}
    (hN : 0 < (N : Real))
    (hκ : 0 < κ)
    (hpFloor : 0 < pFloor)
    (hactive : driverFloor ≤ |driver|)
    (htrans :
      selfGeneratedPressureTransversality driver Pseq N driverFloor pFloor)
    (hbridge : sequenceProjectedPressureCreatesPollution Pseq N totalPollution κ) :
    0 < totalPollution := by
  have hnonnull : noNullLockAverageLowerBound Pseq N pFloor :=
    noNullLock_of_self_generated_pressure_transversality hactive htrans
  exact positive_total_pollution_of_no_null_lock
    hN hκ hpFloor hnonnull hbridge

/--
Clean-relay contradiction from the corrected self-generated pressure bridge.
-/
theorem clean_relay_contradiction_of_self_generated_transversality
    {driver : LocalJumpDriver}
    {Pseq : ProjectedPressureSequence}
    {N : Nat}
    {Vclean Vtotal totalPollution cleanupRate elapsedTime : Real}
    {κ driverFloor pFloor : Real}
    (hVclean_nonneg : 0 ≤ Vclean)
    (haccount :
      cleanVolumeAccounting
        Vclean
        Vtotal
        ((N : Real) * totalPollution)
        (cleanupRate * elapsedTime))
    (hN : 0 < (N : Real))
    (hκ : 0 < κ)
    (hpFloor : 0 < pFloor)
    (hactive : driverFloor ≤ |driver|)
    (htrans :
      selfGeneratedPressureTransversality driver Pseq N driverFloor pFloor)
    (hbridge : sequenceProjectedPressureCreatesPollution Pseq N totalPollution κ)
    (hcount :
      (Vtotal + cleanupRate * elapsedTime) / totalPollution < (N : Real)) :
    False := by
  have hnonnull : noNullLockAverageLowerBound Pseq N pFloor :=
    noNullLock_of_self_generated_pressure_transversality hactive htrans
  exact clean_relay_contradiction_of_no_null_lock_sequence
    hVclean_nonneg haccount hN hκ hpFloor hnonnull hbridge hcount

end ZtareProofs
