/-
  ZTARE → Lean 4 Proof Stubs
  Project: gp088_oeis_a000607
  Generated by src/ztare/formal/lean_compiler.py

  These stubs encode the ZTARE gate harness results as Lean 4 proof
  obligations. Each `sorry` is a proof goal to be discharged by
  native_decide, norm_num, or tactic automation.
-/

import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Data.Fin.Basic

open Real


/-- Evidence grid: visible_grid --/
def visible_grid : List (Float × Float) :=
  [ (5.0, 0.6931471805599453),
    (6.0, 0.6931471805599453),
    (7.0, 1.0986122886681098),
    (8.0, 1.0986122886681098),
    (9.0, 1.3862943611198906),
    (10.0, 1.6094379124341003),
    (11.0, 1.791759469228055),
    (12.0, 1.9459101490553132),
    (13.0, 2.1972245773362196),
    (14.0, 2.302585092994046),
    (15.0, 2.4849066497880004),
    (16.0, 2.6390573296152584),
    (17.0, 2.833213344056216),
    (18.0, 2.9444389791664403),
    (19.0, 3.1354942159291497),
    (20.0, 3.258096538021482),
    (21.0, 3.4011973816621555),
    (22.0, 3.5553480614894135),
    (23.0, 3.6888794541139363),
    (24.0, 3.828641396489095),
    (25.0, 3.9512437185814275),
    (26.0, 4.0943445622221),
    (27.0, 4.204692619390966),
    (28.0, 4.343805421853684),
    (29.0, 4.465908118654584),
    (30.0, 4.584967478670572),
    (31.0, 4.709530201312334),
    (32.0, 4.820281565605037),
    (33.0, 4.941642422609304),
    (34.0, 5.056245805348308),
    (35.0, 5.1647859739235145),
    (36.0, 5.2832037287379885),
    (37.0, 5.389071729816501),
    (38.0, 5.497168225293202),
    (39.0, 5.605802066295998),
    (40.0, 5.71042701737487),
    (41.0, 5.817111159963204),
    (42.0, 5.918893854273146),
    (43.0, 6.023447592961033),
    (44.0, 6.1224928095143865),
    (45.0, 6.222576268071369),
    (46.0, 6.322565239927284),
    (47.0, 6.419994928147142),
    (48.0, 6.517671272912275),
    (49.0, 6.612041034833092),
    (50.0, 6.70808408385307),
    (51.0, 6.80128303447162),
    (52.0, 6.894670039433482),
    (53.0, 6.9874902470009905),
    (54.0, 7.078341579557671),
    (55.0, 7.168579897264035),
    (56.0, 7.258412150595307),
    (57.0, 7.347299700743164),
    (58.0, 7.43543801981455),
    (59.0, 7.52294091807237),
    (60.0, 7.609862200913554) ]


/-- Evidence grid: holdout_grid --/
def holdout_grid : List (Float × Float) :=
  [ (61.0, 7.6953031349635665),
    (62.0, 7.780720886117918),
    (63.0, 7.865187954187467),
    (64.0, 7.949091499830517),
    (65.0, 8.0323601479245),
    (66.0, 8.114922974204593),
    (67.0, 8.196987927258897),
    (68.0, 8.277920258172143),
    (69.0, 8.358900612421644),
    (70.0, 8.439015410352214),
    (71.0, 8.518592212329946),
    (72.0, 8.597666575566114),
    (73.0, 8.676075516476429),
    (74.0, 8.754002933494261),
    (75.0, 8.83127373772255),
    (76.0, 8.9082888855571),
    (77.0, 8.984568369308281),
    (78.0, 9.060447282401565),
    (79.0, 9.135832319801121),
    (80.0, 9.21064032698518),
    (81.0, 9.2850767180902),
    (82.0, 9.359018964347545),
    (83.0, 9.432523462195268),
    (84.0, 9.505618521049591),
    (85.0, 9.578103612900335),
    (86.0, 9.65033572298117),
    (87.0, 9.722025626154055),
    (88.0, 9.79333780903514),
    (89.0, 9.864330837334935),
    (90.0, 9.93479240236454),
    (91.0, 10.00487016682473),
    (92.0, 10.074579627378533),
    (93.0, 10.143920772387299),
    (94.0, 10.21284549666577),
    (95.0, 10.281444421227691),
    (96.0, 10.349646646971848),
    (97.0, 10.417478162445276),
    (98.0, 10.484920743466072),
    (99.0, 10.552081829046976),
    (100.0, 10.61886089185424) ]


/-- Evidence grid: farther_tail_grid --/
def farther_tail_grid : List (Float × Float) :=
  [ (101.0, 10.685309309535713),
    (102.0, 10.751413786883626),
    (103.0, 10.81719495047468),
    (104.0, 10.882621619531593),
    (105.0, 10.947749246454157),
    (106.0, 11.012561592414833),
    (107.0, 11.077068157441543),
    (108.0, 11.141238400910993),
    (109.0, 11.205122314522226),
    (110.0, 11.268698716780495),
    (111.0, 11.331966978773314),
    (112.0, 11.394974915284154),
    (113.0, 11.457676990739749),
    (114.0, 11.520089740154246),
    (115.0, 11.582218291466178),
    (116.0, 11.644076526854011),
    (117.0, 11.705651045062906),
    (118.0, 11.76697060590374),
    (119.0, 11.828013538612462),
    (120.0, 11.888803837113372),
    (121.0, 11.949301211985935),
    (122.0, 12.009571025162385),
    (123.0, 12.069576863441636),
    (124.0, 12.129326581284857),
    (125.0, 12.188840012966631),
    (126.0, 12.248101911005493),
    (127.0, 12.30711635718226),
    (128.0, 12.36588441397189),
    (129.0, 12.42443277449961),
    (130.0, 12.482738006246748),
    (131.0, 12.540814815019354),
    (132.0, 12.59865850435484),
    (133.0, 12.65627845996815),
    (134.0, 12.713667054539942),
    (135.0, 12.770840851220333),
    (136.0, 12.827796324442142),
    (137.0, 12.884537567303978),
    (138.0, 12.941052509692053),
    (139.0, 12.997366887229644),
    (140.0, 13.053465501405164),
    (141.0, 13.10935513590442),
    (142.0, 13.16504731742771),
    (143.0, 13.220529475189851),
    (144.0, 13.275813812117194),
    (145.0, 13.330893470366416),
    (146.0, 13.385782469960393),
    (147.0, 13.440470866769923),
    (148.0, 13.494970527034988),
    (149.0, 13.549279426795087),
    (150.0, 13.603395963497798) ]


/-- Gate FAILURE (exclusion): holdout_global_residual
    Expression: ((ch0_ch0_a * math.log(n) + ch0_ch0_b * (n ** ch0_ch0_k) + ch0_ch0_c) + (ch0_ch1_a * math.log(n) + ch0_ch1_b * n / (n + ch0_ch1_c) + ch0_ch1_d)) + (((ch1_a_a * math.log(n) + ch1_a_b) + (ch1_b_a * n + ch1_b_b)) / (ch1_d2_a * math.log(n) + ch1_d2_b))
    Parameters: ch0_ch0_a := -11626.968849526504, ch0_ch0_b := -0.2855064054933554, ch0_ch0_k := 1.0, ch0_ch0_c := -28055.53192081984, ch0_ch1_a := 11625.866660058204, ch0_ch1_b := -10.410346775934011, ch0_ch1_c := 92.07966780919507, ch0_ch1_d := 28053.116459802117, ch1_a_a := 7.048122146516863, ch1_a_b := -16.783186216177967, ch1_b_a := -6.521391827463612, ch1_b_b := 38.046595418922685, ch1_d2_a := -3.8376336994638214, ch1_d2_b := 6.176428066073128
    Max residual: 10.618861 >= threshold 0.08
    Grid: holdout_grid
    Certification: native_decide on Float bounds --/
def check_holdout_global_residual_excluded : Bool :=
  holdout_grid.any fun (n, v) =>
    (Float.abs (((((-11626.968849526504) * Real.log(n) + (-0.2855064054933554) * (n ^ (1.0)) + (-28055.53192081984)) + ((11625.866660058204) * Real.log(n) + (-10.410346775934011) * n / (n + (92.07966780919507)) + (28053.116459802117))) + ((((7.048122146516863) * Real.log(n) + (-16.783186216177967)) + ((-6.521391827463612) * n + (38.046595418922685))) / ((-3.8376336994638214) * Real.log(n) + (6.176428066073128)))) - v)) >= 0.08

#eval check_holdout_global_residual_excluded  -- should print true


/-- Gate FAILURE (exclusion): holdout_upper_residual
    Expression: ((ch0_ch0_a * math.log(n) + ch0_ch0_b * (n ** ch0_ch0_k) + ch0_ch0_c) + (ch0_ch1_a * math.log(n) + ch0_ch1_b * n / (n + ch0_ch1_c) + ch0_ch1_d)) + (((ch1_a_a * math.log(n) + ch1_a_b) + (ch1_b_a * n + ch1_b_b)) / (ch1_d2_a * math.log(n) + ch1_d2_b))
    Parameters: ch0_ch0_a := -11626.968849526504, ch0_ch0_b := -0.2855064054933554, ch0_ch0_k := 1.0, ch0_ch0_c := -28055.53192081984, ch0_ch1_a := 11625.866660058204, ch0_ch1_b := -10.410346775934011, ch0_ch1_c := 92.07966780919507, ch0_ch1_d := 28053.116459802117, ch1_a_a := 7.048122146516863, ch1_a_b := -16.783186216177967, ch1_b_a := -6.521391827463612, ch1_b_b := 38.046595418922685, ch1_d2_a := -3.8376336994638214, ch1_d2_b := 6.176428066073128
    Max residual: 10.618861 >= threshold 0.06
    Grid: holdout_grid
    Certification: native_decide on Float bounds --/
def check_holdout_upper_residual_excluded : Bool :=
  holdout_grid.any fun (n, v) =>
    (Float.abs (((((-11626.968849526504) * Real.log(n) + (-0.2855064054933554) * (n ^ (1.0)) + (-28055.53192081984)) + ((11625.866660058204) * Real.log(n) + (-10.410346775934011) * n / (n + (92.07966780919507)) + (28053.116459802117))) + ((((7.048122146516863) * Real.log(n) + (-16.783186216177967)) + ((-6.521391827463612) * n + (38.046595418922685))) / ((-3.8376336994638214) * Real.log(n) + (6.176428066073128)))) - v)) >= 0.06

#eval check_holdout_upper_residual_excluded  -- should print true


/-- Gate FAILURE (exclusion): farther_tail_global_residual
    Expression: ((ch0_ch0_a * math.log(n) + ch0_ch0_b * (n ** ch0_ch0_k) + ch0_ch0_c) + (ch0_ch1_a * math.log(n) + ch0_ch1_b * n / (n + ch0_ch1_c) + ch0_ch1_d)) + (((ch1_a_a * math.log(n) + ch1_a_b) + (ch1_b_a * n + ch1_b_b)) / (ch1_d2_a * math.log(n) + ch1_d2_b))
    Parameters: ch0_ch0_a := -11626.968849526504, ch0_ch0_b := -0.2855064054933554, ch0_ch0_k := 1.0, ch0_ch0_c := -28055.53192081984, ch0_ch1_a := 11625.866660058204, ch0_ch1_b := -10.410346775934011, ch0_ch1_c := 92.07966780919507, ch0_ch1_d := 28053.116459802117, ch1_a_a := 7.048122146516863, ch1_a_b := -16.783186216177967, ch1_b_a := -6.521391827463612, ch1_b_b := 38.046595418922685, ch1_d2_a := -3.8376336994638214, ch1_d2_b := 6.176428066073128
    Max residual: 13.603396 >= threshold 0.1
    Grid: farther_tail_grid
    Certification: native_decide on Float bounds --/
def check_farther_tail_global_residual_excluded : Bool :=
  farther_tail_grid.any fun (n, v) =>
    (Float.abs (((((-11626.968849526504) * Real.log(n) + (-0.2855064054933554) * (n ^ (1.0)) + (-28055.53192081984)) + ((11625.866660058204) * Real.log(n) + (-10.410346775934011) * n / (n + (92.07966780919507)) + (28053.116459802117))) + ((((7.048122146516863) * Real.log(n) + (-16.783186216177967)) + ((-6.521391827463612) * n + (38.046595418922685))) / ((-3.8376336994638214) * Real.log(n) + (6.176428066073128)))) - v)) >= 0.1

#eval check_farther_tail_global_residual_excluded  -- should print true


/-- Gate FAILURE (exclusion): farther_tail_upper_residual
    Expression: ((ch0_ch0_a * math.log(n) + ch0_ch0_b * (n ** ch0_ch0_k) + ch0_ch0_c) + (ch0_ch1_a * math.log(n) + ch0_ch1_b * n / (n + ch0_ch1_c) + ch0_ch1_d)) + (((ch1_a_a * math.log(n) + ch1_a_b) + (ch1_b_a * n + ch1_b_b)) / (ch1_d2_a * math.log(n) + ch1_d2_b))
    Parameters: ch0_ch0_a := -11626.968849526504, ch0_ch0_b := -0.2855064054933554, ch0_ch0_k := 1.0, ch0_ch0_c := -28055.53192081984, ch0_ch1_a := 11625.866660058204, ch0_ch1_b := -10.410346775934011, ch0_ch1_c := 92.07966780919507, ch0_ch1_d := 28053.116459802117, ch1_a_a := 7.048122146516863, ch1_a_b := -16.783186216177967, ch1_b_a := -6.521391827463612, ch1_b_b := 38.046595418922685, ch1_d2_a := -3.8376336994638214, ch1_d2_b := 6.176428066073128
    Max residual: 13.603396 >= threshold 0.08
    Grid: farther_tail_grid
    Certification: native_decide on Float bounds --/
def check_farther_tail_upper_residual_excluded : Bool :=
  farther_tail_grid.any fun (n, v) =>
    (Float.abs (((((-11626.968849526504) * Real.log(n) + (-0.2855064054933554) * (n ^ (1.0)) + (-28055.53192081984)) + ((11625.866660058204) * Real.log(n) + (-10.410346775934011) * n / (n + (92.07966780919507)) + (28053.116459802117))) + ((((7.048122146516863) * Real.log(n) + (-16.783186216177967)) + ((-6.521391827463612) * n + (38.046595418922685))) / ((-3.8376336994638214) * Real.log(n) + (6.176428066073128)))) - v)) >= 0.08

#eval check_farther_tail_upper_residual_excluded  -- should print true


/-- Iteration 1 candidate: a * math.log(n) + b
    Visible max_res: 1.290442
    Status: reverted (failed holdout or score not improved) --/
-- exclusion witness available in fit_result_iter_001.json


/-- Iteration 2 candidate: a * math.log(n) + b * (n ** k) + c
    Visible max_res: 0.119030
    Status: reverted (failed holdout or score not improved) --/
-- exclusion witness available in fit_result_iter_002.json


/-- Iteration 3 candidate: (ch0_a * math.log(n) + ch0_b * (n ** ch0_k) + ch0_c) + (ch1_
    Visible max_res: 0.119030
    Status: reverted (failed holdout or score not improved) --/
-- exclusion witness available in fit_result_iter_003.json


/-- Iteration 4 candidate: (ch1_a * math.log(n) + ch1_b) + (ch0_a * math.log(n) + ch0_b
    Visible max_res: 0.119030
    Status: reverted (failed holdout or score not improved) --/
-- exclusion witness available in fit_result_iter_004.json


/-- Iteration 5 candidate: a * math.log(n) + b * n / (n + c) + d
    Visible max_res: 0.652923
    Status: reverted (failed holdout or score not improved) --/
-- exclusion witness available in fit_result_iter_005.json


/-- Iteration 6 candidate: (ch0_a * math.log(n) + ch0_b * (n ** ch0_k) + ch0_c) + (ch1_
    Visible max_res: 0.111983
    Status: reverted (failed holdout or score not improved) --/
-- exclusion witness available in fit_result_iter_006.json


/-- Iteration 7 candidate: ((a_a * math.log(n) + a_b) + (b_a * n**b_b + b_c)) + (d2_a *
    Visible max_res: 0.119029
    Status: reverted (failed holdout or score not improved) --/
-- exclusion witness available in fit_result_iter_007.json


/-- Iteration 8 candidate: ((ch0_ch0_a * math.log(n) + ch0_ch0_b * (n ** ch0_ch0_k) + c
    Visible max_res: 0.128618
    Status: reverted (failed holdout or score not improved) --/
-- exclusion witness available in fit_result_iter_008.json


/-- PSLQ Conjecture: Empirical constants mapped to exact expressions
    ch0_ch0_a = -11626.968849526504 ≈ -11627
    ch0_ch0_b = -0.2855064054933554 ≈ -((2/7))
    ch0_ch0_k = 1.0 ≈ 1
    ch0_ch0_c = -28055.53192081984 ≈ -28056
    ch0_ch1_a = 11625.866660058204 ≈ 11626
    ch0_ch1_b = -10.410346775934011 ≈ -10
    ch0_ch1_c = 92.07966780919507 ≈ 92
    ch0_ch1_d = 28053.116459802117 ≈ 28053
    ch1_a_a = 7.048122146516863 ≈ 7
    ch1_a_b = -16.783186216177967 ≈ -17
    ch1_b_a = -6.521391827463612 ≈ -2*pi
    ch1_b_b = 38.046595418922685 ≈ 38
    ch1_d2_a = -3.8376336994638214 ≈ -4
    ch1_d2_b = 6.176428066073128 ≈ 2*pi

    This is a CONJECTURE, not a proof. The numerical bounds above
    are sorry-free (certified by evaluation). The exact-constant
    identification is a hypothesis generated by PSLQ integer
    relation algorithm. The epistemic boundary is explicit. --/

-- axiom pslq_ch0_ch0_a : ch0_ch0_a = -11627  -- CONJECTURE (sorry)
-- axiom pslq_ch0_ch0_b : ch0_ch0_b = -((2/7))  -- CONJECTURE (sorry)
-- axiom pslq_ch0_ch0_k : ch0_ch0_k = 1  -- CONJECTURE (sorry)
-- axiom pslq_ch0_ch0_c : ch0_ch0_c = -28056  -- CONJECTURE (sorry)
-- axiom pslq_ch0_ch1_a : ch0_ch1_a = 11626  -- CONJECTURE (sorry)
-- axiom pslq_ch0_ch1_b : ch0_ch1_b = -10  -- CONJECTURE (sorry)
-- axiom pslq_ch0_ch1_c : ch0_ch1_c = 92  -- CONJECTURE (sorry)
-- axiom pslq_ch0_ch1_d : ch0_ch1_d = 28053  -- CONJECTURE (sorry)
-- axiom pslq_ch1_a_a : ch1_a_a = 7  -- CONJECTURE (sorry)
-- axiom pslq_ch1_a_b : ch1_a_b = -17  -- CONJECTURE (sorry)
-- axiom pslq_ch1_b_a : ch1_b_a = -2*pi  -- CONJECTURE (sorry)
-- axiom pslq_ch1_b_b : ch1_b_b = 38  -- CONJECTURE (sorry)
-- axiom pslq_ch1_d2_a : ch1_d2_a = -4  -- CONJECTURE (sorry)
-- axiom pslq_ch1_d2_b : ch1_d2_b = 2*pi  -- CONJECTURE (sorry)


/-- Topology class exhaustion: log_polynomial
    2 iterations attempted, all failed farther-tail gate.
    No form in this class generalizes beyond the visible window. --/
theorem log_polynomial_class_exhausted :
  ∀ f ∈ topology_class_log_polynomial,
    ∃ (n v) ∈ farther_tail_grid,
      |f n - v| ≥ farther_tail_threshold := by
  -- Induction over 2 iteration witnesses
  sorry


/-- Topology class exhaustion: power_law
    6 iterations attempted, all failed farther-tail gate.
    No form in this class generalizes beyond the visible window. --/
theorem power_law_class_exhausted :
  ∀ f ∈ topology_class_power_law,
    ∃ (n v) ∈ farther_tail_grid,
      |f n - v| ≥ farther_tail_threshold := by
  -- Induction over 6 iteration witnesses
  sorry

