/-
  ZTARE → Lean 4 Proof Stubs
  Project: ztare_on_ztare
  Generated by src/ztare/formal/lean_compiler.py

  STRICT MODE (P4 gate): warningAsError is on; unclosed `sorry`
  goals compile-fail. Post-compile, `scripts/public/lean/verify_lean_stub.py`
  enforces the axiom allowlist {propext, Classical.choice, Quot.sound}
  and the schema-pinned theorem headers.

  These stubs encode the ZTARE gate harness results as Lean 4 proof
  obligations. In non-strict mode, each `sorry` is a proof goal to be
  discharged by native_decide, norm_num, or tactic automation. In
  strict mode, `sorry` is a compile error and every theorem must be
  closed before the gate passes.
-/

set_option warningAsError true  -- GP-135 strict: sorry becomes error
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Data.Fin.Basic

open Real


/-- Evidence grid: visible_grid --/
def visible_grid : List (Float × Float) :=
  [  ]

