import importlib.util
import sys
from pathlib import Path


DECL_INDEX_PATH = Path(__file__).resolve().parents[2] / "scripts" / "lean_decl_index.py"
CLOSED_LOOP_PATH = Path(__file__).resolve().parents[2] / "scripts" / "llm_theorem_closed_loop.py"
LEAN_GATE_PATH = Path(__file__).resolve().parents[2] / "src" / "ztare" / "gates" / "lean_proof_gate.py"


def _load(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def test_decl_index_includes_structure_fields_and_local_binders(tmp_path):
    mod = _load(DECL_INDEX_PATH, "lean_decl_index_test_fields")
    lean_dir = tmp_path / "ZtareProofs"
    lean_dir.mkdir()
    (lean_dir / "sample.lean").write_text(
        "structure LeraySelfTaxProfilePriceStream where\n"
        "  payoffLimit : Real\n\n"
        "def leraySelfTaxLimitPrice (_S : LeraySelfTaxProfilePriceStream) : Real := 0\n",
        encoding="utf-8",
    )

    idx = mod.build_index(lean_dir)
    result = mod.check_nomination(
        "theorem candidate_name (S : LeraySelfTaxProfilePriceStream) : "
        "S.payoffLimit ≤ leraySelfTaxLimitPrice S := by\n"
        "  exact le_rfl",
        idx,
    )

    assert result["valid"] is True
    assert "candidate_name" not in result["unresolved"]
    assert "S.payoffLimit" not in result["unresolved"]
    assert "le_rfl" not in result["unresolved"]


def test_decl_index_rejects_unbound_field_head(tmp_path):
    mod = _load(DECL_INDEX_PATH, "lean_decl_index_test_unbound")
    lean_dir = tmp_path / "ZtareProofs"
    lean_dir.mkdir()
    (lean_dir / "sample.lean").write_text(
        "structure LeraySelfTaxProfilePriceStream where\n"
        "  payoffLimit : Real\n\n"
        "def sharpTarget : Real := 0\n",
        encoding="utf-8",
    )

    idx = mod.build_index(lean_dir)
    result = mod.check_nomination(
        "theorem missing_stream_object : S.payoffLimit ≤ sharpTarget := by\n"
        "  exact le_rfl",
        idx,
    )

    assert result["valid"] is False
    assert "S.payoffLimit" in result["unresolved"]


def test_decl_index_rejects_fake_field_on_local_binder(tmp_path):
    mod = _load(DECL_INDEX_PATH, "lean_decl_index_test_fake_field")
    lean_dir = tmp_path / "ZtareProofs"
    lean_dir.mkdir()
    (lean_dir / "sample.lean").write_text(
        "structure KnownStream where\n"
        "  payoffLimit : Real\n",
        encoding="utf-8",
    )

    idx = mod.build_index(lean_dir)
    result = mod.check_nomination(
        "theorem fake_field (S : KnownStream) : S.fakeField = S.payoffLimit := by\n"
        "  rfl",
        idx,
    )

    assert result["valid"] is False
    assert "S.fakeField" in result["unresolved"]
    assert "S.payoffLimit" not in result["unresolved"]


def test_decl_index_rejects_unbound_long_quantities(tmp_path):
    mod = _load(DECL_INDEX_PATH, "lean_decl_index_test_unbound_quantities")
    lean_dir = tmp_path / "ZtareProofs"
    lean_dir.mkdir()
    (lean_dir / "sample.lean").write_text(
        "def threeProfilePositiveCoherencePrice : Real := 0\n",
        encoding="utf-8",
    )

    idx = mod.build_index(lean_dir)
    result = mod.check_nomination(
        "theorem fantasy_rhs : "
        "threeProfilePositiveCoherencePrice ≤ branchA + branchB := by\n"
        "  exact le_rfl",
        idx,
    )

    assert result["valid"] is False
    assert {"branchA", "branchB"}.issubset(set(result["unresolved"]))


def test_decl_index_excludes_generated_scratch_files_by_default(tmp_path):
    mod = _load(DECL_INDEX_PATH, "lean_decl_index_test_generated")
    lean_dir = tmp_path / "ZtareProofs"
    lean_dir.mkdir()
    (lean_dir / "real_spine.lean").write_text(
        "def realDecl : Prop := True\n",
        encoding="utf-8",
    )
    (lean_dir / "hallucination_smoke_iter.lean").write_text(
        "def fakeDecl : Prop := True\n",
        encoding="utf-8",
    )

    idx = mod.build_index(lean_dir)

    assert "realDecl" in idx["decls"]
    assert "fakeDecl" not in idx["decls"]


def test_decl_index_excludes_ztare_lean_compiler_stubs_by_default(tmp_path):
    mod = _load(DECL_INDEX_PATH, "lean_decl_index_test_compiler_stub")
    lean_dir = tmp_path / "ZtareProofs"
    lean_dir.mkdir()
    (lean_dir / "compiler_stub.lean").write_text(
        "/-\n  Generated by src/ztare/formal/lean_compiler.py\n-/\n"
        "def poisonedDecl : Prop := True\n",
        encoding="utf-8",
    )

    idx = mod.build_index(lean_dir)

    assert "poisonedDecl" not in idx["decls"]


def test_decl_index_ignores_import_module_paths(tmp_path):
    mod = _load(DECL_INDEX_PATH, "lean_decl_index_test_imports")
    lean_dir = tmp_path / "ZtareProofs"
    lean_dir.mkdir()
    (lean_dir / "sample.lean").write_text(
        "def knownTarget : Prop := True\n",
        encoding="utf-8",
    )

    idx = mod.build_index(lean_dir)
    result = mod.check_nomination(
        "import ZtareProofs.some_project_module\n\n"
        "theorem imported_surface_candidate : knownTarget := by\n"
        "  trivial",
        idx,
    )

    assert result["valid"] is True
    assert "ZtareProofs.some_project_module" not in result["unresolved"]


def test_revision_prompt_forbids_sorry():
    mod = _load(CLOSED_LOOP_PATH, "llm_theorem_closed_loop_test_prompt")
    prompt = mod.revise_prompt(
        "theorem bad : True := by trivial",
        "unknown identifier",
        [],
    )

    assert "Do NOT use `sorry`" in prompt
    assert "sorry` is acceptable" not in prompt


def test_closed_loop_loads_jsonl_proof_sketches(tmp_path):
    mod = _load(CLOSED_LOOP_PATH, "llm_theorem_closed_loop_test_jsonl")
    nominations = tmp_path / "nominations.jsonl"
    nominations.write_text(
        '{"proof_sketch": "theorem jsonl_candidate : True := by\\n  trivial"}\n',
        encoding="utf-8",
    )

    blocks = mod.load_nominations_from_file(nominations)

    assert blocks == ["theorem jsonl_candidate : True := by\n  trivial"]


def test_lean_proof_audit_rejects_compilable_non_theorem_block(tmp_path):
    mod = _load(LEAN_GATE_PATH, "lean_proof_gate_test_non_theorem")
    proofs_root = tmp_path / "ztare_proofs"
    target_dir = proofs_root / "ZtareProofs"
    target_dir.mkdir(parents=True)
    lean_path = target_dir / "non_theorem.lean"
    lean_path.write_text("def helperOnly : True := True.intro\n", encoding="utf-8")

    audit = mod.audit_axioms(lean_path, proofs_root)

    assert audit["axiom_audit_passed"] is False
    assert "<no-theorem-or-lemma-declarations>" in audit["extra_axioms"]
